(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// stage content:
(lib._7rof = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{},true);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(2));

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0099FF").s().p("AAYhQQgLgGgNAAQgRAAgNAKQgMAKgGATQgGATgBAcQAAAxARAVQAPARAXAAQATAAAMgKQAMgJAGgTQAGgTAAgeQAAgYgDgPQgEgPgHgKQgHgLgKgFIAAAAAAiAAQAAAqgKAOQgKAOgOAAQgNAAgKgOQgKgOAAgqQAAgoALgQQAJgMANgBQAOAAAKAOQAKAPAAAoIAAAA").cp();
	this.shape.setTransform(89.6,130.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0099FF").s().p("AAXhQQgMgGgMAAQgUAAgOAMQgOALgEAWIAVADQADgPAIgIQAIgIAMAAQALAAAIAIQAHAIAAALQAAAPgKAHQgLAHgMAAIgDAAIgCAQIANgCQAOAAAKAJQAKAKgBAOQAAAPgKALQgKAKgNAAQgNAAgIgIQgJgIgEgSIgVADQACAVAPAOQAPAOAXgBQAXAAAQgPQARgQAAgWQAAgRgJgLQgIgJgQgEQAMgFAGgJQAGgJAAgLQAAgMgGgLQgGgJgMgHIAAAA").cp();
	this.shape_1.setTransform(76.7,130.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1},{t:this.shape}]},1).to({state:[]},1).wait(1));

	// Layer 2
	this.instance = new lib.Symbol6();
	this.instance.setTransform(279,155);
	this.instance.cache(-227,-63,456,128);

	this.start = new lib.Symbol21();
	this.start.setTransform(268.3,375.7,1,1,0,0,0,98.8,98.8);
	this.start.cache(-1,-1,202,202);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.start},{t:this.instance}]}).to({state:[]},1).wait(2));

	// Layer 7
	this.markb = new lib.Symbol1_1();
	this.markb.setTransform(212,537.2,1,1,0,0,0,70.5,54.6);
	this.markb._off = true;
	this.markb.cache(-1,-1,145,113);

	this.timeline.addTween(cjs.Tween.get(this.markb).wait(1).to({_off:false},0).to({_off:true},1).wait(1));

	// Layer 11
	this.eldarga = new cjs.Text("", "38px Arial", "#FF0000");
	this.eldarga.textAlign = "right";
	this.eldarga.lineHeight = 20;
	this.eldarga.lineWidth = 135;
	this.eldarga.setTransform(97.7,28.9);

	this.txt1 = new cjs.Text("", "38px Arial", "#FFFFFF");
	this.txt1.textAlign = "right";
	this.txt1.lineHeight = 20;
	this.txt1.lineWidth = 68;
	this.txt1.setTransform(93,59);

	this.natega = new lib.Symbol8copy();
	this.natega.setTransform(86.2,89);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.natega},{t:this.txt1},{t:this.eldarga}]},1).to({state:[]},1).wait(1));

	// Layer 1
	this.text = new cjs.Text("", "38px Arial", "#FFFFFF");
	this.text.textAlign = "right";
	this.text.lineHeight = 20;
	this.text.lineWidth = 55;
	this.text.setTransform(53,54);

	this.text_1 = new cjs.Text("", "38px Arial", "#E8F8FF");
	this.text_1.textAlign = "right";
	this.text_1.lineHeight = 20;
	this.text_1.lineWidth = 99;
	this.text_1.setTransform(34,47);

	this.ans8 = new lib.Symbol18();
	this.ans8.setTransform(76.8,203,0.883,0.883);
	this.ans8.alpha = 0;
	this.ans8.cache(-52,-52,106,106);

	this.ans2 = new lib.Symbol17();
	this.ans2.setTransform(262.8,217.8,0.883,0.883);
	this.ans2.alpha = 0;
	this.ans2.cache(-52,-52,106,106);

	this.ans0 = new lib.Symbol16();
	this.ans0.setTransform(230.3,328.4,0.883,0.883);
	this.ans0.alpha = 0;
	this.ans0.cache(-52,-52,106,106);

	this.ans6 = new lib.Symbol15();
	this.ans6.setTransform(400.7,149.4,0.883,0.883);
	this.ans6.alpha = 0;
	this.ans6.cache(-52,-52,106,106);

	this.ans9 = new lib.Symbol14();
	this.ans9.setTransform(127.3,288.4,0.883,0.883);
	this.ans9.alpha = 0;
	this.ans9.cache(-52,-52,106,106);

	this.ans3 = new lib.Symbol13();
	this.ans3.setTransform(482.4,63,0.883,0.883);
	this.ans3.alpha = 0;
	this.ans3.cache(-52,-52,106,106);

	this.ans5 = new lib.Symbol12();
	this.ans5.setTransform(199.7,61.3,0.883,0.883);
	this.ans5.alpha = 0;
	this.ans5.cache(-52,-52,106,106);

	this.ans4 = new lib.Symbol11();
	this.ans4.setTransform(304.7,98.4,0.883,0.883);
	this.ans4.alpha = 0;
	this.ans4.cache(-52,-52,106,106);

	this.ans7 = new lib.Symbol10();
	this.ans7.setTransform(393.9,266.4,0.883,0.883);
	this.ans7.alpha = 0;
	this.ans7.cache(-52,-52,106,106);

	this.ans1 = new lib.Symbol9();
	this.ans1.setTransform(456.8,323.4,0.883,0.883);
	this.ans1.alpha = 0;
	this.ans1.cache(-52,-52,106,106);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.ans1},{t:this.ans7},{t:this.ans4},{t:this.ans5},{t:this.ans3},{t:this.ans9},{t:this.ans6},{t:this.ans0},{t:this.ans2},{t:this.ans8},{t:this.text_1},{t:this.text}]},1).to({state:[]},1).wait(1));

	// Layer 9
	this.sea = new lib.Symbol25();
	this.sea.setTransform(276.2,639.8,1.001,1.058,0,0,0,268.7,47.5);
	this.sea.cache(-1,-1,541,99);

	this.instance_1 = new lib.Symbol1();
	this.instance_1.setTransform(545.6,638.2,1.391,1.436,0,0,0,190,0);
	this.instance_1.alpha = 0.422;
	this.instance_1.cache(-200,-39,392,80);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_1},{t:this.sea}]},1).to({state:[]},1).wait(1));

	// Layer 12
	this.instance_2 = new lib.Symbol24();
	this.instance_2.setTransform(276.9,498.1);
	this.instance_2.cache(-239,-33,479,68);

	this.instance_3 = new lib.Symbol4("synched",0);
	this.instance_3.setTransform(52.9,429,0.355,0.909,180,0,0,-10.1,-2.7);

	this.instance_4 = new lib.Symbol3("synched",0);
	this.instance_4.setTransform(74.1,427.6,0.336,0.653,0,180,-179.6,-0.8,4.4);

	this.reset_btn = new lib.Symbol7();
	this.reset_btn.setTransform(292.9,589.1,1,1,0,0,0,76.5,24.5);
	this.reset_btn.cache(-30,-10,197,124);

	this.pannel = new lib.Symbol4copy();
	this.pannel.setTransform(273.5,336.7,1,1,0,0,0,245.5,143.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.pannel},{t:this.reset_btn},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2}]},2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(52.9,93,452.1,381.4);


// symbols:
(lib.Symbol26 = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#3399FF").s().p("ALBiSIgFARIgCATIAIADIARB7IgwAAIAAgXQAAgVgGgPQgIgTgPAAQgNAAgJAPQgIAOAAAPQAAASARAFQAHADAZAEIgdAEIgnAAQAAgigIgWQgLgbgZgNIgCAdQAVAHAJATQAHARAAAYIg4AAQgHAAgDgDQgEgCgCgGIgDAAIgDAUQAAAHAHAEQAHAFAIAAIDOAAIAAgdIgRhwIAHACIADgNIABgPIgPgGQgJgEgBgJIgCgBAJ7hvIgRgMIgNAUIASAMIAMgUAKQhkIANgUIgTgMIgMAUIASAMAKPgZIAHARIgUgDQgLgDAAgMQAAgEADgDQADgDAEAAQAIAAAGALIAAAAAElgQQAMAAAMAEQAKAEANAIIAZAQIhpAAIAAgMQAAgRgKgLQgJgLgVgBQgMAAgLAEQgKADgMAIIgZASQgOAHgRAGQgRAGgMAAQgNAAgJgMQgJgJgGgUIgGAJIADAQQAAAKgJAEIghACIAAgEIgQhwIAHACIABgNIACgPIgNgGQgKgEAAgJIgCgBIgFARIgCATIAHADIASB7IgrAAIAAgPQAAgdgKgRIgIgKIgLAYQAJAIAEAKQAEAKAAAPIAAAEIh8AAQgZAAgQgJQgSgHAAgSQAAgIAEgKIAGgOIgEgDIgLAUQgGAOAAAOQAAAYAVAMQARAKAcAAIDEAAIAAAAIAkgCIAMgHIANAGQAHADAIAAIFLAAIAAgZIgJAAQgGgCgSgOIghgcQgUgOgPAAQgPAAgKAJQgHAHgEALIAPgBADsAEQAAAGgHADQgIADgQAAIhDAAIAhgQQAVgJAOAAQAMAAAJAEQAJAEAAAFIAAAAAiOhmIgKAVIAXAMIAMgVIgZgMAi6hEIAYAMIALgVIgYgMIgLAVAoViSIgFARIgCATIAHADIASB7IhNAAIgXADQgOAEgKAKQgKAMAAASQAAAEAEADQAEACAJAAIAfADIACAEQAAAHgUADQgQADgVAAQgfAAgSgIQgSgJgBgTQAAgJAJgRIALgTIgGgDIgSAeQgJATAAARQAAAUAUAMQASAKAgAAQAtAAAUgNQASgMAAgcQAAgFgFgCIgJgCIgZgCQgOAAAAgFQAAgDALgCICWgBQAZAAAcgFQAegGAVgIIALgZIhTARQgMgGgHgIQgGgJgBgHQAAgHAMgEQALgFAUAAIARABIASAFIADgDIgRgSQgMgJgSAAQgWAAgPAMQgOAMAAARQAAAJADAGIAGAQIgWAAIAAgEIgShwIAHACIADgNIABgPIgOgGQgKgEAAgJIgCgBAqiB7IgNAOIARAKIANgNIgRgLApzCGIgQgLIgOAOIARAKIANgN").cp();
	this.shape.setTransform(-5.7,-72.5);

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FEFCE7","#FFFFFF","#FEFCEA"],[0,0.553,1],0,-108.1,0,108.2).s("#0099FF").ss(1.5,1,1).p("EAkCgR8MAAhAj5MhJFAAAMAAAgj5MA9VAAAILPAA").cp();

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-233.9,-114.9,468,230);


(lib.Symbol24 = function() {
	this.initialize();

	// Layer 1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#009900").s().p("EgkogBhIgHArIgQAAIgIgrIAAgkIAfAAIAAAkEgj1gCFIAAAkIgIArIgQAAIgIgrIAAgkIAgAAEgh9AAEIAKgWIgCgBIAJgZIAhASQASANAAANQAAATgHALQgLARgcAAQgLAAgHgFQgJgFAAgJQAAgLAFgNIAAAAEghugACQgEAEAAAFQAAAIAEAEQAEAEAIAAQAIAAAKgEQAKgFAAgEQAAgGgRgHIgPgJIgIAKEghqgBYIALgWIAZANIgMAWIgYgNEgiNgBKIALgWIAZANIgLAWIgZgNA+pgIIgHgSQgGgMgJAAQgEABgDADQgDADAAAFQAAALAMAEIAUADA/LhtIAMgVIAWAOIgNAWIgVgPA4ggTQAEAKAAAPIAAAlIgMAAQgKAAgHgDIgMgHIgNAHQgIADgNAAIgKAAQgHAAgJgDIgMgHIgOAIIgiABIAAABIlEAAQgKAAgHgJQgFgHgDgOIgJhgIgEgPIgJgNIASgdQAHASACAZIADBKQADAZAFAIQAEAGAFAAIAKAAQAFAAAGAAIA4AAIAPgDQgbgEgHgDQgSgGAAgSQABgQAIgOQAJgQAOAAQAPAAAIAUQAGAPAAAVIAAAYIBwAAIgagQIgYgMQgMgFgNAAIgQABQAFgLAHgHQAKgJAQAAQAPAAAVAPIAiAcQATAPAGABIA2AAIgSh+IgIgEIACgTIAFgSIADABQAAAJAJAFIAQAGIgEAdIgIgDIASB1IAAADIAPAAQAMABAFgDQAJgDAAgLIAAgHIgCgJIAGgJIAHAUQAFAJAGAFQAHAHAJAAIAKAAQAMABAFgEQAGgEAAgJIAAgHIgCgJIAGgJIAEAOQAEAPAGAGQAFAGAIAAQAEAAADgDQADgCAAgEQgBgHgGgJQgDgEgEgGIAKgQIAIAQAzhgeQgHAGgGAIIAIACIALABQAJAAAIgKIgCgRQgOAFgHAFIAAAAA18AYQAAAIgGAGQgGAHgKAAQgMgBgHgKQgIgLAAgQQAAgVANgRQAHgIANgJIAFAIIgOAOQgIALAAAIQAAAHAQADQARAEAAARIAAAAA0ChxIALgWIAZAMIgLAWIgZgMAzfh/IALgWIAZANIgMAWIgYgNAwkBsIgZgNIALgVIAZANIgLAVAwPA8IAZANIgMAVIgYgMIALgWAx1hWIALgWIAZANIgMAWIgYgNAutgIIgHgSQgGgMgJAAQgEABgDADQgDADAAAFQAAALAMAEIAUADAuth0IgNAWIgVgPIAMgVIAWAOApyAtQgLgBgIgKQgIgLAAgQQAAgVAOgRQAHgIAMgJIAFAIIgNAOQgJALAAAIQAAAHARADQAQAEAAARQAAAIgGAGQgGAHgKAAIAAAAAsIgjIAJAQQADAKAAAPIAAAlIgMAAQgJAAgHgDIgNgHIgMAHQgIADgOAAIgJAAQgIAAgIgDIgNgHIgNAIIgmABIAAABIkKAAQgLgBgJgSQgGgOgEgUQgEAJgHACQgHAFgIAAQgRAAgMgCQgLgCAAgCQAAgNARgQQARgQAZgMIgCgMQAAgGADgGIAIgLIASBdQAFAPAFAAIBaAAQAAgQgFgJQgCgHgMgMIAMgYQALANADAIQAEAMAAAZIAAAKIBFAAQAAgQgFgJQgCgHgMgMIAMgYQALANADAIQAEAMAAAZIAAAKIA9AAIAPgDQgbgEgHgDQgSgGAAgSQABgQAIgOQAJgQAOAAQAPAAAIAUQAGAPAAAVIAAAYIASAAQANABAFgDQAIgDAAgLIAAgHIgCgJIAHgJIAHAUQAEAJAGAFQAHAHAKAAIAKAAQAMABAFgEQAGgEAAgJIgBgHIgCgJIAHgJIADAOQAEAPAGAGQAGAGAIAAQAEAAADgDQACgCAAgEQAAgHgGgJQgDgEgFgGIAKgQAk2BMQAAgMgSgLQgOgJgOgDQAAARAIALQAJANAUAAIAGgCQADgBAAgDIAAAAAlHAEQALgFAAgGQAAgPgHAAQgGABgJAOIgNAUQAOgDAKgGIAAAAAh0gjIAJAQQADAKAAAPIAAAlIgMAAQgJAAgHgDIgNgHIgMAHQgIADgOAAIgJAAQgIAAgIgDIgNgHIgNAIIgkABIAAABIg4AAQAKAEAHAJQAIAKAAAMQABALgEAIQgFAJgJAAQgTgBgPgMQgSgOAAgZIAAgLIgkAAQgZAAgTAEQgXAGAAALIADAWIAHAWQADAMAAAJIAAALIgDAMIgYhUQAAgTAIgLQAIgKARgFIAogHIgMgLQgIgFgHAAIgKACIgJAIIgHgEQAFgJAGgHQAJgMANAAQAKABAJAGQAIAGAIAJIALAQIAXAAIAMgYQAIgPAJgKQAKgLAJAAQAFAAADAIQAEAIAAAKQAAANgHAGQgEAGgVAJIBTAAQANABAFgDQAIgDAAgLIAAgHIgCgJIAHgJIAHAUQAEAJAGAFQAHAHAKAAIAKAAQAMABAFgEQAGgEAAgJIgBgHIgCgJIAHgJIADAOQAEAPAGAGQAGAGAIAAQAEAAADgDQACgCAAgEQAAgHgGgJQgDgEgFgGIAKgQAArgoIgNAOQgJALAAAIQAAAHARADQAQAEAAARQAAAIgGAGQgGAHgKAAQgLgBgIgKQgIgLAAgQQAAgVAOgRQAHgIAMgJIAFAIAGLgVQgDgJgHAAQgFAAgDADQgCAEAAAFQAAAIAGADIARAGQAAgNgDgHIAAAAAFzhXIgYgNIAMgWIAZANIgNAWAG3BsIgZgNIALgVIAZANIgLAVAHMA8IAZANIgMAVIgYgMIALgWAMZAtQgMgBgHgKQgIgLAAgQQAAgVANgRQAHgIANgJIAFAIIgOAOQgIALAAAIQAAAHAQADQARAEAAARQAAAIgGAGQgGAHgKAAIAAAAAJ5gTIAKgQIAIAQQAEAKAAAPIAAAlIgMAAQgKAAgHgDIgMgHIgNAHQgIADgNAAIgKAAQgHAAgJgDIgMgHIgOAIIj9ACQggAAgTgEQgYgFgMgLQgNgLAAgTQAAgNAIgSIAIgTIAHAEIgJAUIgCAMQAAAUAWAIQAWAJAvAAIBvAAQgRgFgJgGQgJgFAAgLQAAgOAJgQQALgSANAAQAPAAAGASQAGAPAAAaIAAAQIA9AAQAAgQgFgJQgCgHgMgMIAMgYQALANADAIQAEAMAAAZIAAAKIAXAAQAMABAFgDQAJgDAAgLIAAgHIgCgJIAGgJIAHAUQAFAJAGAFQAHAHAJAAIAKAAQAMABAFgEQAGgEAAgJIAAgHIgCgJIAGgJIAEAOQAEAPAGAGQAFAGAIAAQAEAAADgDQADgCAAgEQgBgHgGgJQgDgEgEgGIAAAAAPFgOIALABQAJAAAIgKIgCgRQgOAFgHAFQgHAGgGAIIAIACAOphxIALgWIAZAMIgLAWIgZgMAPkhyIgYgNIALgWIAZANIgMAWARfg5QATAAAMAJQAFADAMAPIgDADIgSgEIgSgCQgUAAgMAFQgMAEAAAIQAAAHAHAJQAIAIAMAHIBVgSIgLAaQgXAJgeAFQgeAGgZAAIg0AAQgLgBgJgSQgGgOgEgUQgEAJgHACQgHAFgIAAQgRAAgMgCQgLgCAAgCQAAgNARgQQARgQAZgMIgCgMQAAgGADgGIAIgLIASBdQAFAPAFAAIAzAAQgFgHgCgJIgDgPQAAgSAPgMQAPgMAXAAIAAAAAY6goIgOAOQgIALAAAIQAAAHAQADQARAEAAARQAAAIgGAGQgGAHgKAAQgMgBgHgKQgIgLAAgQQAAgVANgRQAHgIANgJIAFAIAWZgjIAIAQQAEAKAAAPIAAAlIgMAAQgKAAgHgDIgMgHIgNAHQgIADgNAAIgKAAQgHAAgJgDIgMgHIgOAIIglABIAAABIgVAAQgKAAgHgJQgFgHgDgOIgJhgIgEgPIgJgNIASgdQAHASACAZIADBKQADAZAFAIQAEAGAFAAIAnAAQAMABAFgDQAJgDAAgLIAAgHIgCgJIAGgJIAHAUQAFAJAGAFQAHAHAJAAIAKAAQAMABAFgEQAGgEAAgJIAAgHIgCgJIAGgJIAEAOQAEAPAGAGQAFAGAIAAQAEAAADgDQADgCAAgEQgBgHgGgJQgDgEgEgGIAKgQAfMACQAAAIAHADQAFAEAMAAIAAgBIAEAAQgCgNgGgEQgEgFgGAAIgHADQgDADAAACIAAAAAcnAAQAAgPAJgQQALgSAMAAQATAAAJAYQAJAVAAAZIAAAdQAAAfgcAPQgaAOgrAAQgiAAgSgMQgUgNAAgaQAAgRAFgVQAGgSAJgQIAHADIgNAkIgDAUQAAATARAKQAPAIAeAAQAhAAAYgKQAcgNAAgVIgBgLIgBgHIgMAFIgMABQgNAAgIgGQgLgHAAgOIAAAAAdPgPQgFgHgGAAQgHABgEADQgDAEAAAFQAAAEAEADIAKACIAIAAIAIgEIgFgLAdPhYIgZgNIAMgWIAZANIgMAWAc4hgIgMAWIgYgNIALgWIAZANEAgfgAZIAHAUQAFAJAGAFQAHAHAJAAIAKAAQAMABAFgEQAGgEAAgJIAAgHIgCgJIAGgJIAEAOQAEAPAGAGQAFAGAIAAQAEAAADgDQADgCAAgEQgBgHgGgJQgDgEgEgGIAKgQIAIAQQAEAKAAAPIAAAlIgMAAQgKAAgHgDIgMgHIgNAHQgIADgNAAIgKAAQgHAAgJgDIgMgHIgOAIIgjABQgCAVgQAUQgUAbgbAAQgKABgLgDIgngNIACgFIAjAGQASAAARgJQANgHAMgOIATgXQgCAAgCAAQgRAAgKgHQgLgHAAgRQAAgNAHgOQAJgPAMAAQAOAAAFAPQAFAMAAATIAPAAQAMABAFgDQAJgDAAgLIAAgHIgCgJIAGgJEAj2gCFIAfAAIAAAkIgHArIgQAAIgIgrIAAgkEAlAgA2IgQAAIgIgrIAAgkIAgAAIAAAkIgIAr").cp();
	this.shape_2.setTransform(0,16.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#5BBCF9").s().p("AHWA/IATALIgJARIgUgKIAKgSAKEAkIgBgFIgFgKIgLAMIgOALIAVgBQAKgCAAgFIAAAAAJhBTIgFACQgCAAgBACQACADAEACIAJADIAEAAIAFgCQAAAEgEACIgHADIgXAIQAAgFAMgFIgGgDIgCgFQAAgEAGgGQAIgIAFAAIAEACQACACAAACQAAABgBACIgCAEQgEgEgEAAIAAAAAKkhQIgGAWIgHgEIAAAMQAAAQgEAPQgFARgKAPIAHANQADAIAAAHIgCAQIgbAFIgdABIAAgEIADgRQAVgLAOgSIgbgrIgGgJIgHgFIgFACQgBABgCABQgDAAgGgGIgKgLIgGgKIgCgJIABgLQACgHADAAQAFAAAKAKQAJAIAJAOIAqBBQAIgOADgSQADgNAAgYIgHgEIACgOIAEgNIACABQABAGAFADIAPAHALDhNIALgYIAMB1QABAKgEAJIgIAQIgCgCIAAgIQAAgDABgDIgLhwAFHBDIAVAKIgKARIgUgKIAJgRADkAaIAAgDQAAgOgEgJQgDgHgIgFIAKgUIAGAIQAIAOAAAYIAAAhIh0AAQgYABgNgJQgSgKAAgXQAAgIAFgMIAJgQIAEABIgGAMQgDAJAAAGQAAANAPAIQANAHAVAAIBoAAAD5hDIgIgKIAPgYQAFAPACAUIACA9QADAUAEAGQAEAFADAAIBIAAQAAgPgDgHIgMgNIAKgUQAJALACAGQADAKAAATIAAAeIhRAAQgIgBgFgFQgEgGgDgMIgHhNIgDgNAC0g+IgKASIgTgLIAJgRIAUAKAB7gsIAJgRIAUAKIgJASIgUgLAFphNIAPgYQAFAPACAUIACA9QADAUAEAGQAEAFADAAIBvAAIgVgPIgTgKQgKgBgKAAIgNAAQADgJAGgFQAJgIAMAAQANAAARAMIAbAVQAPAOAFABIAHAAIAAAVIiYAAQgIgBgFgFQgEgGgDgMIgHhNIgDgNIgIgKAi2AMIgbAOIA4AAIAUgCQAGgDAAgFQAAgGgIgDQgHgDgKAAQgMAAgSAIIAAAAAgphNIALgYIAMB1QABAKgEAJIgIAQIgCgCIAAgIQAAgDABgDIgLhwAnxBIIAUALIgJARIgUgKIAJgSAneBPIAJgSIAUALIgKARIgTgKAq0AAQAIAAAGgFIgCgOIgRAIQgGAEgEAHIAGAAIAJAAAqpg0IAGgJIAOBKQAFANADAAIBoAAIgVgPIgTgKQgKgBgKAAIgNAAQAEgJAGgFQAIgIANAAQAMAAARAMIAcAVQAPAOAFABIA5AAQgBgPgDgHIgLgNIAJgUQAJALACAGQAEAKAAATIAAAJIBaAAIgVgPIgTgKQgKgBgKAAIgNAAQADgJAGgFQAJgIAMAAQANAAARAMIAbAVQAPAOAFABIAUAAIAOgCQAHgDAAgIIgBgNIAFgHQAEAOAHAJQAIAKALAAQAKAAAOgFQAPgFALgHIAVgNIASgKQAJgDALAAQARAAAIAKQAIAIAAAPIAAAKIAlAAIgPhmIgGgDIACgPIAEgPIACACQAAAGAIAEIAMAFIgBANIgCAKIgGgCIAOBeIAAAYIjEAAIgNgCIgKgFIgLAGIgdAAIAAABIlQAAQgIAAgHgPQgFgLgDgSQgEAHgGAEQgFAEgGAAQgPAAgJgCQgJgCAAgDQAAgKAOgLQAOgNAUgKIgCgKIADgJAqahhIgKASIgTgLIAJgRIAUAKArThPIAJgRIAUAKIgJASIgUgL").cp();
	this.shape_3.setTransform(156.3,-21);

	this.addChild(this.shape_3,this.shape_2);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-237.5,-32,475.3,64.3);


(lib.Symbol22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{},true);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(2));

	// Layer 1
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#999999").ss(1.5,1,1).p("AB/hPQAGAIADAJQAOAdAAAhQAAApgTAgQgKASgPAPQgsAsg+AAQg9AAgsgsQgPgPgKgSQgTggAAgpQAAgbAKgZQAFgOAIgNQADgEAEgFQAGgJAIgIQAFgFAGgEQAogjA2AAQA3AAApAjQAFAEAFAFQALALAIANQACABAAABIAAAA").cp();
	this.shape_4.setTransform(1.3,-0.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.rf(["#C60000","#9A2929"],[0,1],-2.8,-3.1,0,-2.9,-3.1,13.8).s().p("ABphIQAGAIAEAIQACAEACAEQAJAXAAAZQAAAlgTAeQgIANgLALQglAlg1AAQg0AAgmglQgLgLgHgNQgTgeAAglQAAgZAJgXQAEgIAEgIQADgEACgEQAHgJAIgIQAJgJAJgGQAggXAoAAQApAAAgAXQAJAGAIAJQAJAIAGAJIAAAA").cp();
	this.shape_5.setTransform(1.3,-0.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).to({state:[]},1).wait(1));

	// Layer 2
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s("#F5855D").ss(1,1,1).p("AC0izQBLBLAABoQAABphLBLQhLBLhpAAQhoAAhLhLQhLhLAAhpQAAhoBLhLQBLhLBoAAQBpAABLBLIAAAA").cp();
	this.shape_6.setTransform(1.7,-0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6}]}).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-23.7,-26.2,51,51);


(lib.Symbol21 = function() {
	this.initialize();

	// Layer 1
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgrjGIAhEkQAHBWAAAwIgDA2IAGAEQAXgnAHgTQANgiAAglQAAgugIhbQgGhHgMhbIgRiPIgrBX").cp();
	this.shape_7.setTransform(132.8,91.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AApifQAiAkAJAUQANAdAAA2IjiAAIAABOIEDAAIAAhuQAAhSgMgjQgIgYghgpIgkBLAAHCCIgfBDIBHAmIAlhBIhNgo").cp();
	this.shape_8.setTransform(108.6,113);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABVgTQAYAxgBBSIivAAQgUAAgLgHQgNgIgFgTIgLAAIgHAfIgBAgQAAAUAUAPQAVAPAbABIDLAAIAAhQQAAhvgahDQghhWhOgnIgHBZQBBAVAcA+IAAAA").cp();
	this.shape_9.setTransform(84.8,99.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAukNIgPAAQgPAAgTgLQgVgNAAgGQAAgFAJgFQALgFAHABQARAAAOANIAIgPQADgHAAgHQAAgJgHgGQgGgHgKAAQgVAAgZAcQgYAbAAANQAAAKAKAJQAHAHAOAHQgtAQgBAVIBUgdQATgHAKgGQAOgJAAgLIgSAGAgjiEIAhEkQAFBWAAAwIgDA2IAIAEQAXgnAHgTQANgiAAgmQAAgtgIhbQgGhJgMhZIgSiPIgqBX").cp();
	this.shape_10.setTransform(58.1,84.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#5EB7B5").s().p("APbAAQAAGZkhEhQkhEhmZAAQmYAAkhkhQkhkhAAmZQAAmYEhkhQEhkhGYAAQGZAAEhEhQEhEhAAGYIAAAA").cp();
	this.shape_11.setTransform(98.8,98.8);

	this.addChild(this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,197.5,197.5);


(lib.Symbol20 = function() {
	this.initialize();

	// Layer 2
	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AEPkOQBwBwAACeQAACfhwBwQhwBwifAAQieAAhwhwQhwhwAAifQAAieBwhwQBwhwCeAAQCfAABwBwIAAAA").cp();

	this.addChild(this.shape_12);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-38.3,-38.3,76.7,76.7);


(lib.Symbol19 = function() {
	this.initialize();

	// Layer 1
	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#C6FFFF").ss(1,1,1).p("AghiLIAsCAQAtCCAAAVAg3hZIA0C8");
	this.shape_13.setTransform(218.3,-104.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#999999").ss(1,1,1).p("EAhjgUHIoZgCIAAHgIKiACQgEgNgEgNQAAgDgBgBIgDgNIpkADIgDmNIH1gDIAAgDQgDgIgCgHIgGgWEAjsgMnIDJLEI2gAKIAA20IQGAKIBID8EAhugTfIByGNAPyBpIgPi9Ie8AAIBrBmIA6A5IhpBbQiCB6h9CZQg6BHg1BKQhrCThbCeQixE1hyFeMhNzgAKQhqj8hekzQgOgvgNgsQh7mwAKj9QADhCAMg3MBAmAAVIgUBtUhAGgAIgAbgABEgvSAN6MBV5AAB");

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#AD5E13").s().p("EAgbgArIgUBsUhAGgAJgAbAAAQADhBAMg3MBAmAAV").cp();
	this.shape_15.setTransform(-106.4,15);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#282828").s().p("Egq8gFJMBV5AABQixE1hyFdMhN0gALQhqj7hekyQgOgugMgtIAAAA").cp();
	this.shape_16.setTransform(-27.7,122);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#AE280F").s().p("EAoLAGUMhV5gABQh7mtAKj9UAAbAAABAGAAJIAUhuIIzgXIVXAmQgiADh1DMQg5Blg/CdQhrCThbCdIAAAA").cp();
	this.shape_17.setTransform(-9.9,48.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#E6724B").s().p("AsOjcIXjg/IA6A5IhpBbQiCB7h9CXQg6BHg1BKQA/ifA5hmQB1jKAigDI1Vgm").cp();
	this.shape_18.setTransform(235.7,30.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#A5240E").s().p("AQTAII3jA/IozAYIgPi9Ie6AAIBrBm").cp();
	this.shape_19.setTransform(203.9,1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#87D2D5").s().p("ADBjHIByGMIpiADIgDmMIHzgDAC3iNIAtCAQAuCDgBAVQABgVguiDIgtiAACghbIA1C8Ig1i8").cp();
	this.shape_20.setTransform(196.5,-104.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#B9BABC").s().p("AIGAMIDKLEI2fAKIAA2zIQFAKIBID9IoYgDIAAHfIKgAC").cp();
	this.shape_21.setTransform(176.6,-81.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#8F9998").s().p("ADIjtIAGAVQACAIACAIIABACInzADIADGMIJigDIADAMQABACAAACQAEANADAOIqfgCIAAnfIIXAD").cp();
	this.shape_22.setTransform(194.8,-104.8);

	this.addChild(this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-314,-155,628.2,310.1);


(lib.Symbol18 = function() {
	this.initialize();

	// Layer 1
	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f().s("#FBCC0A").ss(3,1,1).p("AFqlpQCWCWAADTQAADUiWCWQiWCWjUAAQjTAAiWiWQiWiWAAjUQAAjTCWiWQCWiWDTAAQDUAACWCWIAAAA").cp();

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#3399CC").s().p("AFtiIIgPAbIgegQIAOgaIAfAPAFYhHQAOARADAJQAFAOAAAfIAAAuIhwAAQgMAAgQgGQgSgGgOgMQgKAOgMAFQgLAFgWAAIgcAAQgMAAgJgEQgIgDgHgGQgIAHgHACQgKAEgQAAIgMAAQgKAAgKgEIgNgIIgRAJQgHADgRAAIgzAAQgNAAgHgLQgHgIgEgSQgDgPgCgbIgFhMIgGgTQgEgIgHgHIAXgkQAHAWADAfIAEBbQADAhAGAIQAGAHAGAAIAzAAQAQAAAGgCQALgEAAgLIgBgLIgCgMIAIgLIAIAZQAGANAFAFQAJAIAMAAIAMAAQAOAAAHgEQAHgFAAgIIgDgXIAIgLIAEARQAFAVAHAGQAHAHAKAAQAFAAADgDQADgDAAgFQAAgIgHgMQgEgFgFgHIAMgUQAHALADAJQAEAMAAATIAAAMIAOAAQARABANgJQAKgFAJgMQALgQAQgMQAPgLANgDIAUAjQAKAUAAAMIBPAAQAAgTgFgMQgEgIgNgPIAOgeAEWhsIAOgbIAeAQIgOAbIgegQADjAEQANAHAKAAIACgCQgCgJgGgKIgLgSQgJACgGAGIgKANQAHAHAMAEIAAAAAjag3IAfgCIgGAfQgnAHgcAIQgoALgYASQgcAXAAAfQAAAnAqAUQAkARA8AAIAiAAIABADIgpAdIgLAAQgoAAgbgHQgggJgQgUQgSgXAAgkQgBgfAPgZQALgSAWgQIAggWIgVgBIg1AHQAHgVAHgGQAOgOAhAAIAyAFQASACAMAAIAAAA").cp();
	this.shape_24.setTransform(-1.9,3.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("ADHi4QAEBigTAxQgZBAhUBDQiiCDhUg4QhTg5CjgyQDWhSAChDQABhEBJgdIAAAA").cp();
	this.shape_25.setTransform(16,27.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FDFFE7").s().p("AEChLIAeAPIAOgaIgegQIgOAbAFEgnIgOAeQANAOAEAIQAFAMAAAVIhPAAQAAgMgKgWIgUgiQgNADgPALQgQALgLAQQgJAMgKAHQgNAJgRgBIgOAAIAAgMQAAgVgEgMQgDgIgHgLIgMATQAFAHAEAFQAHAMAAAKQAAAFgDADQgDADgFAAQgKAAgHgHQgHgIgFgVIgEgQIgIAKIADAXQAAAKgHAFQgHAEgOAAIgMAAQgLAAgIgIQgIgHgFgNIgJgYIgHAKIACAMIAAALQAAANgLAEQgGACgPAAIg0AAQgGAAgFgHQgGgKgEgfIgDhcQgDgegIgXIgWAkQAHAHAEAJIAFASIAGBNQABAZAEARQAEASAGAIQAIALAMAAIA0AAQAQAAAIgDIAQgJIAQAIQAKAEAIAAIAMAAQAQAAAKgEQAHgCAIgHQAHAGAIADQAJAEAMAAIAcAAQAWAAALgFQAMgFAKgOQAOAMASAGQAQAGAMAAIBwAAIAAguQAAghgFgMQgDgKgOgRIAAAAAFZhnIgfgQIgOAbIAeAQIAPgbAFqlpQCWCWAADTQAADUiWCWQiWCWjUAAQjTAAiWiWQiWiWAAjUQAAjTCWiWQCWiWDTAAQDUAACWCWIAAAAADPAlQgMgFgHgIIAKgNQAGgGAJgCIALASQAGAKACALIgCACQgKAAgNgHIAAAAAFoBYQhKAdgBBEQgCBDjXBUQiiAyBTA5QBSA4CliDQBThDAZhCQATgxgDhiIAAAAAjugWQgNAAgSgDIgygFQghAAgOAOQgGAGgIAUIA1gHIAWABIghAWQgVASgLASQgPAZAAAfQAAAkATAXQAQAUAgAJQAaAHAoAAIALAAIAqgdIgBgDIgiAAQg9AAgkgRQgqgUAAgnQAAgfAdgXQAXgSAogNQAcgIAngHIAHgeIgfAD").cp();

	this.addChild(this.shape_26,this.shape_25,this.shape_24,this.shape_23);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-51.1,-51.1,102.4,102.4);


(lib.Symbol17 = function() {
	this.initialize();

	// Layer 1
	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f().s("#FBCC0A").ss(3,1,1).p("AFqlpQCWCWAADTQAADUiWCWQiWCWjUAAQjTAAiWiWQiWiWAAjUQAAjTCWiWQCWiWDTAAQDUAACWCWIAAAA").cp();

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#336699").s().p("ACDhsIAPgaIAbARIgQAbIgagSAF9BOIgEAAQgMABgJgEQgFgCgFgEQgDgBgCgCQgIAHgHACQgKADgQAAIgMAAQgKAAgKgEIgPgIIgRAKQgHACgRAAInlAAQgNABgKgYQgIgRgEgbQgGALgIAFQgJAGgJAAQgWAAgOgDQgOgDAAgEQAAgQAVgRQAUgUAggOIgCgIIgBgIQAAgGAEgIIAJgNIAXByQAFATAGAAIEIAAQgBgWgEgMQgEgIgOgNIAPgeQANARADAKQADAMAAAhIAAANIBNAAQgBgWgEgMQgEgIgOgNIAPgeQANARADAKQAFAMAAAhIAAANIBEgBIARgEQgfgEgKgEQgVgKAAgWQgBgRALgSQALgTARAAQASAAALAYQAHATAAAYIAAAgIAXAAQAQAAAGgDQALgEAAgNIgBgLIgCgMIAIgJIAIAXQAGAOAHAGQAJAJAMAAIAMAAQAOAAAHgEQAHgFAAgLIgDgXIAIgJIAEAQQAFAUAHAIQAHAHAKAAQAFAAADgDQADgCAAgGQAAgKgHgMQgEgFgFgHIAMgSQAHALADAHQAEANAAAVIAAAsIgKAAAlMAHQAMAAAJgKIgDgUQgRAGgJAGQgJAHgGAHIAJADIAOABAg3hQIAOgbIAeAQIgOAaIgegPAlehiIgegQIAOgaIAeAPIgOAbAlEidIAfAPIgOAbIgegQIANgaAAxCEIgOAaIgegPIANgbIAfAQAA9BjIAeAQIgOAaIgegPIAOgbACFgHQAAAMAPAFIAZADQgEgNgFgHQgHgOgLAAQgFABgEADQgEAEAAAGIAAAA").cp();
	this.shape_28.setTransform(-2,3.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("ADIimQAABNgQArQgZA/hTBDQijCEhUg5QhTg4CkgzQDVhSAChDQABgxAngdQAFADAGADQAJAEALgBIAEAA").cp();
	this.shape_29.setTransform(16,28.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FDFFE7").s().p("ABuhHIAaASIARgbIgbgRIgQAaAFqlpQCWCWAADTQAADUiWCWQiWCWjUAAQjTAAiWiWQiWiWAAjUQAAjTCWiWQCWiWDTAAQDUAACWCWIAAAAAFFBrQgnAdgBAxQgCBDjXBUQiiAyBTA5QBSA4CliDQBThDAZhCQAQgqAAhNIALAAIAAgtQAAgVgEgMQgDgJgIgLIgMAUQAFAHAEAFQAIAMAAAKQAAAFgDADQgDADgFAAQgLAAgGgHQgIgIgFgVIgDgRIgIALIADAXQAAAKgIAFQgGAEgPAAIgMAAQgMAAgIgIQgIgHgFgNIgJgZIgHALIACAMIAAALQAAANgLAEQgGACgPAAIgXAAIAAgfQAAgagIgTQgKgXgTAAQgQAAgMASQgKARAAAUQAAAWAVAJQAKAEAgAFIgSAEIhDAAIAAgNQAAghgFgOQgDgJgOgQIgOAdQANAPAEAIQAFAMAAAVIhLAAIAAgNQAAghgFgOQgDgJgNgQIgPAdQAOAPAEAIQAEAMABAVIkIAAQgGAAgFgTIgXhyIgJANQgEAIAAAGIABAIIACAIQggANgUATQgVAUAAAQQAAAEAOADQAOADAWAAQAJAAAJgGQAIgFAGgLQAEAbAIARQAKAXANAAIHmAAQAQAAAIgDIAQgJIAQAIQAKAEAJAAIAMAAQARAAAJgEQAHgCAIgHQACACADACIAAAAABxAdQAAgGAEgEQAEgEAFAAQAKAAAIAOQAEAHAEAPIgYgDQgPgFAAgOIAAAAAAoCJIgOAbIAeAPIAPgaIgfgQAAcCpIgdgPIgNAaIAcAQIAOgbAlZh4IgNAaIAeAQIAOgbIgfgPAlzg9IAOgbIgegPIgOAaIAeAQAhMgrIAeAPIAOgaIgegQIgOAbAlhAsIgOgBIgJgCQAGgKAJgHQAJgGARgGIADAVQgJALgMAAIAAAA").cp();

	this.addChild(this.shape_30,this.shape_29,this.shape_28,this.shape_27);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-51.1,-51.1,102.4,102.4);


(lib.Symbol15 = function() {
	this.initialize();

	// Layer 1
	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f().s("#FBCC0A").ss(3,1,1).p("AFqlpQCWCWAADTQAADUiWCWQiWCWjUAAQjTAAiWiWQiWiWAAjUQAAjTCWiWQCWiWDTAAQDUAACWCWIAAAA").cp();

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#99CC00").s().p("AFZiEIgPAbIgegQIAOgbIAfAQAE8guQgFAAgEAFQgDAEAAAFQAAAPARAAIAJgBIAJgFQgDgGgFgHQgIgKgHAAIAAAAADAhmQgEgJgHgGIAXglQAHAXADAeIAEBcQADAfAGAKQAGAHAGAAIByAAQABgQgEgPIgPAFIgPACQgOAAgIgHQgKgIAAgMQAAgaAJgTQAKgWARAAQAXgBAMAlQAKAdAAAlIAAAxIiCAAQgNAAgHgLQgHgIgEgSQgDgRgCgZIgFhNIgGgSAClhiIgOAbIgegQIAOgbIAeAQACfgtQANARADAJQAFAOAAAfIAAAuIhYAAQgEAYgSAZQgaAighAAQgLAAgMgDIgxgQIADgGIAWAFIAVADQAVAAAUgMQAQgIAPgSIAXgcQgZAAgNgIQgOgJAAgVQAAgTAJgPQALgSAPAAQAQAAAIASQAFANAAAaIBLAAQgBgVgEgMQgEgGgOgPIAPgeAhIgFQAEAKAAAWIAAAtIgPAAQgLAAgIgDQgIgDgJgHQgIAHgGACQgJAEgRAAIgWAAQAAARgJAQQgKAUgWANQgbAPgpAAQglAAgUgNQgVgOAAgdQAAgQADgRIALggIAOgfIAIADQgNAbgFAPQgEAQAAAMQAAAXARAMQAQAMAeAAQAkABAcgNQAjgPAAgcQAAgTgHgQQgFgOgKgMIAPgkQAKAPADAMQAFAPAAAcIAWAAQASABAHgGQAHgEAAgKIgBgLIgCgKIAIgLIADAQQAEASAHAIQAHAJAOAAQAFAAACgDQACgCAAgFQAAgIgGgMIgLgNIAMgUIALATABLAnIAGAAQgEgRgGgGQgFgGgIAAQgFAAgEADQgDAEAAAFQAAAJAIAFQAHADAOABIAAgB").cp();
	this.shape_32.setTransform(-1.4,1.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("ADHi4QAEBigTAxQgZBAhUBDQiiCDhUg4QhTg5CjgyQDWhSAChDQABhEBJgdIAAAA").cp();
	this.shape_33.setTransform(16,27.4);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FDFFE7").s().p("ACQgiIgOAeQANAOAEAIQAFAMAAAVIhKAAQAAgagGgOQgHgRgQgBQgQAAgKASQgJAQAAATQAAAVAOAJQANAIAYAAIgWAcQgQASgQAIQgSAMgXAAIgVgDIgWgFIgDAGIAxAQQANADAMAAQAgAAAZgiQASgZAEgYIBZAAIAAguQAAghgFgMQgDgKgOgRIAAAAACXhWIgegQIgOAbIAeAPIAOgaACyhaIAFASIAGBLQABAbAEARQAEASAGAIQAIALAMAAICDAAIAAgxQAAglgLgeQgMgkgWABQgRAAgKAVQgKAUAAAZQAAANAKAIQAJAHANAAIAPgCIAPgFQAEAPAAAQIhzAAQgGAAgFgHQgGgKgEghIgDhaQgDgegIgXIgWAkQAHAHAEAJIAAAAAEtgiQAHAAAIAJQAGAHACAHIgJAEIgJACQgQAAAAgPQAAgFADgFQAEgEAEAAIAAAAAFKh4IgegQIgOAbIAeAQIAOgbAFqlpQCWCWAADTQAADUiWCWQiWCWjUAAQjTAAiWiWQiWiWAAjUQAAjTCWiWQCWiWDTAAQDUAACWCWIAAAAAFoBYQhKAdgBBEQgCBDjXBUQiiAyBTA5QBSA4CliDQBThDAZhCQATgxgDhiIAAAAAA9AzIAAABQgPgBgHgDQgIgFAAgJQAAgFAEgEQAEgDAFAAQAHAAAFAGQAGAGAEARIgFAAAhXAFIgLgSIgMATIALAPQAGAMAAAIQAAAFgCACQgCADgFAAQgOAAgHgJQgHgIgEgSIgDgRIgIAKIACAMIABALQAAAKgHAEQgHAGgSgBIgWAAQAAgcgFgRQgDgKgKgPIgPAkQAKAMAFAOQAHAQAAATQAAAcgjAPQgcANgkgBQgeAAgQgMQgRgMAAgXQAAgMAEgQQAFgPANgbIgIgDIgOAfIgLAgQgDARAAAQQAAAdAVAOQAUANAlAAQApAAAbgPQAWgNAKgUQAJgQAAgRIAWAAQARAAAJgEQAGgCAIgHQAJAHAIADQAIADALAAIAPAAIAAgtQAAgWgEgMIAAAA").cp();

	this.addChild(this.shape_34,this.shape_33,this.shape_32,this.shape_31);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-51.1,-51.1,102.4,102.4);


(lib.Symbol14 = function() {
	this.initialize();

	// Layer 1
	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f().s("#FBCC0A").ss(3,1,1).p("AFqlpQCWCWAADTQAADUiWCWQiWCWjUAAQjTAAiWiWQiWiWAAjUQAAjTCWiWQCWiWDTAAQDUAACWCWIAAAA").cp();

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("ADHi4QAEBigTAxQgZBAhUBDQiiCDhUg4QhTg5CjgyQDWhSAChDQABhEBJgdIAAAA").cp();
	this.shape_36.setTransform(16,27.4);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FDFFE7").s().p("ACqgUQAMAPAHALQAJAQgBAOQAAASgQAVQgRAVgXAOQgaAOgYABIgxgIIgDAIIA1ASQAPAEANAAQAOAAAVgNQAYgOAOgTQASgWAAgUICaAAIAAghQgOgagXgYQgVgXgcgWIgPgLQgMgJAAgEQAAgEASgIIBNgbIAAggIg1AUQgjANgOARQgQASAAAgQAAAGALAJIAWARIAGgGQAdARARAPQAQANANATIiEAAIAAgMQAAgTgIgQQgIgNgPgPIgKAdAAMgmIgMAUQAFAHAEAFQAIALAAAKQAAAFgDADQgDADgFAAQgJAAgHgHQgHgIgFgTIgEgSIgIALIADAWQAAAKgHAFQgHAEgOAAIgMAAQgMAAgJgIQgHgHgGgMIgIgZIgIALIACAMIABAKQAAANgLAEQgGACgQAAIgzAAQgQAAgOAFQgTAFgLAMQgNAPAAAXQAAAGAFADQAEADAMAAIAnAEQADABAAADQAAAJgZAFQgUAEgbAAQgnAAgXgLQgYgMAAgXQAAgNALgUIAOgYIgHgEIgXAlQgMAYAAAWQAAAaAZAPQAYANAoAAQA5AAAZgRQAXgQAAgiQAAgHgGgDIgMgCIgfgDQgRAAgBgGQAAgEAPgCIBegBQARAAAHgDIARgJIAPAIQAKAEAKAAIAMAAQAQAAAKgEQAHgCAIgHQAHAGAIADQAIAEALAAIAPAAIAAgtQAAgTgEgNQgDgJgIgLIAAAAAFqlpQCWCWAADTQAADUiWCWQiWCWjUAAQjTAAiWiWQiWiWAAjUQAAjTCWiWQCWiWDTAAQDUAACWCWIAAAAAlEC0IAWANIARgQIgVgPIgSASAkdC0IAVANIARgQIgVgPIgRASAFoBYQhKAdgBBEQgCBDjXBUQiiAyBTA5QBSA4CliDQBThDAZhCQATgxgDhiIAAAA").cp();

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FF3300").s().p("AAXg0QAIALADAJQAEANAAATIAAAtIgPAAQgLAAgJgEQgGgDgIgGQgIAHgHACQgJAEgRAAIgMAAQgJAAgKgEIgQgIIgQAJQgIADgQAAIhfABQgOACAAAEQAAAGARAAIAgADIAMACQAFADAAAHQABAigYAPQgZASg5AAQgoAAgXgNQgZgPAAgaQAAgWAMgYIAWglIAHADIgNAYQgLAVAAANQAAAXAYAMQAWALAoAAQAbAAAUgEQAYgFAAgJQABgDgDgCIgngDQgMAAgFgDQgFgEAAgFQAAgXAOgPQALgMASgGQAPgEAPAAIA0AAQAPAAAGgDQALgEAAgLIAAgLIgCgMIAHgLIAJAZQAFAOAIAEQAIAJAMAAIAMAAQAPAAAGgEQAIgFAAgJIgDgXIAIgLIADASQAFAUAGAGQAGAHALAAQAFAAADgDQADgCAAgGQAAgIgIgMQgEgFgFgHIAMgUAC1giIALgdQAPAPAHANQAIAQAAATIAAAMICFAAQgOgSgQgOQgRgPgcgRIgGAGIgWgRQgMgJAAgGQAAggAQgSQAPgRAjgNIA0gUIAAAgIhMAbQgSAIAAAEQAAAEAMAJIAPALQAcAWAVAXQAXAZANAZIAAAhIiaAAQAAAUgRAWQgPATgXAOQgWANgNAAQgOAAgPgEIg1gSIADgIIAxAIQAZgBAZgOQAXgOARgVQARgVAAgSQAAgPgJgOQgHgMgMgPIAAAAAkRCmIAQgSIAWAPIgRAQIgVgNAk4CmIARgSIAVAPIgRAQIgVgN").cp();
	this.shape_38.setTransform(-1.1,1.4);

	this.addChild(this.shape_38,this.shape_37,this.shape_36,this.shape_35);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-51.1,-51.1,102.4,102.4);


(lib.Symbol13 = function() {
	this.initialize();

	// Layer 1
	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f().s("#FBCC0A").ss(3,1,1).p("AFqFqQiWCWjUAAQjTAAiWiWQiWiWAAjUQAAjTCWiWQCWiWDTAAQDUAACWCWQCWCWAADTQAADUiWCWIAAAA").cp();

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FF6600").s().p("ADZAJIAAgJIgCgMIAHgLIAJAXQAFANAIAHQAIAIAMAAIAMAAQAPAAAGgEQAIgFAAgKIgDgVIAIgLIADARQAFATAIAIQAGAHALAAQAFAAADgDQADgDAAgFQAAgKgIgKQgEgFgFgHIAMgUQAIALADAJQAEAMAAATIAAAtIgPAAQgLAAgJgEQgIgDgIgGQgIAHgHACQgJAEgRAAIgMAAQgJAAgKgEIgQgIIgQAJQgIADgQAAIizAAQgDAZgRAYQgZAighAAQgMAAgNgDIgxgQIADgGIAWAFIAUADQAXAAAUgMQAQgIAQgSIAWgcQgYAAgNgIQgOgJAAgVQAAgTAJgOQAKgTAQAAQAQAAAFATQAGAMAAAaICyAAQAPAAAGgCQALgEAAgNIAAAAAgiACQgEAEAAAFQAAAJAIAFQAIAEAOAAIAAgBIAFAAQgEgQgGgHQgFgFgHAAQgFAAgEACIAAAAAjCAFIAKgEIgHgMQgFgIgIAAQgJAAgEAFQgEAEAAAGQAAAEAFADQAFAEAIAAIAJgCAlRgIIAIADIgQAtQgDAMAAAMQAAAZAUALQATAKAlAAQAnABAegOQAjgPAAgZIgBgOIgCgIIgPAFIgOACQgQAAgLgIQgMgIAAgSQAAgTALgUQAMgVAQAAQAWAAANAeQAKAXAAAhIAAAkQABAlgkATQggARg0AAQgpAAgXgPQgZgQAAgfQAAgWAIgYQAGgXAMgUIAAAAAj5h+IAeAQIgOAbIgegQIAOgbAjdh0IAOgbIAfAQIgPAbIgegQ").cp();
	this.shape_40.setTransform(-3.1,-2.1);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FDFFE7").s().p("AC7gMQAAAMgMAEQgGACgPAAIiwAAQAAgYgGgPQgHgSgQgBQgQAAgKATQgJARAAARQAAAVAOAJQANAIAYAAIgWAcQgQASgQAIQgUAMgXAAIgUgDIgWgFIgDAGIAxAQQANADAMAAQAhAAAZgiQATgZADgYICxAAQAQAAAIgDIAQgJIAQAIQAKAEAJAAIANAAQAQAAAKgEQAGgCAJgHQAHAGAIADQAJAEAMAAIAOAAIAAgrQAAgVgEgNQgDgJgHgLIgMAUQAFAHAEAFQAHAMAAAKQAAAEgDADQgDADgFAAQgKAAgHgGQgHgIgFgUIgEgSIgIALIADAXQAAALgHADQgHAEgPAAIgLAAQgMAAgJgHQgIgGgFgOIgIgZIgIALIACAMIABALAFoBYQhJAegCBDQgCBDjYBUQiiAyBUA5QBSA4CkiDQBUhDAZhCQATgxgDhiIAAAAAFqFqQiWCWjUAAQjTAAiWiWQiWiWAAjUQAAjTCWiWQCWiWDTAAQDUAACWCWQCWCWAADTQAADUiWCWIAAAAAj8iLIAeAQIAPgaIgfgQIgOAaAkYiUIgOAbIAeAPIAOgbIgegPAlwgeQgMAWgGAVQgIAYAAAWQAAAfAZAQQAXAPApAAQA0AAAggRQAkgTgBglIAAgkQAAgggKgZQgNgegWAAQgQAAgMAWQgLATAAAVQAAARAMAIQALAIAQAAIAOgCIAPgFIACAIIABAOQAAAZgjAPQgeAOgngBQglAAgTgKQgUgLAAgZQAAgMADgMIAQgtIgIgDAjhgPIgJABQgIAAgFgDQgFgDAAgGQAAgGAEgFQAEgEAJAAQAIAAAFAHIAHAPIgKAEAhBgSQAEgEAFAAQAHAAAFAGQAGAHAEAPIgFAAIAAABQgOgBgIgDQgIgEAAgJQAAgFAEgDIAAAA").cp();

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("ADHi4QAEBigTAxQgZBAhUBDQiiCDhUg4QhUg5CkgyQDWhSAChDQABhDBJgeIAAAA").cp();
	this.shape_42.setTransform(15.9,27.4);

	this.addChild(this.shape_42,this.shape_41,this.shape_40,this.shape_39);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-51.2,-51.1,102.4,102.4);


(lib.Symbol12 = function() {
	this.initialize();

	// Layer 1
	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f().s("#FBCC0A").ss(3,1,1).p("AFqlpQCWCWAADTQAADUiWCWQiWCWjUAAQjTAAiWiWQiWiWAAjUQAAjTCWiWQCWiWDTAAQDUAACWCWIAAAA").cp();

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#4A78FF").s().p("AFhA+QgDAAgDgBQgGgBgEgCQgIgDgIgGQgIAHgHACQgJAEgRAAIgMAAQgJAAgKgEIgQgIIgQAJQgIADgQAAIm5AAQgoAAgYgFQgcgGgOgNQgRgPAAgXQAAgQAKgWIAKgXIAHAFIgKAYIgDAPQABAXAaAMQAbALA6AAICJAAQgWgGgKgHQgMgJAAgLQAAgSAMgTQANgWAQAAQASAAAIAVQAHATAAAfIAAAVIDtAAQAAgVgFgKQgEgIgNgPIAOgeQAOARADAJQAFAOAAAfIAAANIAUAAQAPAAAGgCQALgEAAgNIAAgKIgCgLIAHgLIAJAXQAFANAIAHQAIAIAMAAIAMAAQAPAAAGgEQAIgFAAgKIgDgVIAIgLIADARQAFATAIAIQAGAHAKAAQAFAAAEgDQADgDAAgFQAAgKgIgKQgEgFgFgHIAMgUQAIALADAJQAEAMAAATIAAAtIgPAAQgCAAgCAAIAAAAAhhAFQAAgOgEgIQgEgLgJAAQgGAAgEAEQgCAEAAAHQAAAJAHAEQAGACAQADIAAAAAiChhIgfgRIAQgbIAeAQIgPAcACsBjIgPAaIgegPIAOgbIAfAQABjBkIAeAPIgOAbIgegQIAOga").cp();
	this.shape_44.setTransform(0.7,2.9);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("ADIi3QADBggTAxQgZA/hTBDQijCEhUg5QhTg4CkgzQDVhSAChDQABhABEgeQADAAADAAIAAAA").cp();
	this.shape_45.setTransform(16,27.5);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FDFFE7").s().p("AFiBaQhEAegBBBQgCBDjXBUQiiAyBTA5QBSA4CliDQBThDAZhCQATgxgDhfQACAAACAAIAPAAIAAgtQAAgVgEgMQgDgJgIgKIgMATQAFAHAEAFQAIAMAAAKQAAAFgDADQgDADgFAAQgLAAgGgHQgIgIgFgVIgDgRIgIALIADAXQAAAKgIAFQgGAEgPAAIgMAAQgMAAgIgIQgIgHgFgNIgJgZIgHALIACAMIAAALQAAANgLAEQgGACgPAAIgUAAIAAgNQAAghgFgMQgDgKgOgRIgOAdQANAPAEAIQAFAMAAAVIjtAAIAAgVQAAghgHgRQgIgWgTAAQgPAAgNAWQgMASAAASQAAANAMAJQAKAHAWAGIiJAAQg6AAgbgLQgagMgBgZIADgNIAKgZIgHgEIgKAWQgKAVAAAQQAAAZAQAPQAPANAcAGQAYAFAoAAIG5AAQAQAAAIgDIAQgJIAQAIQAKAEAJAAIAMAAQARAAAJgEQAHgCAIgHQAIAGAIADQAEACAGABIAAAAAFqlpQCWCWAADTQAADUiWCWQiWCWjUAAQjTAAiWiWQiWiWAAjUQAAjTCWiWQCWiWDTAAQDUAACWCWIAAAAABqCBIgOAaIAeAQIAOgbIgegPACzCAIgfgQIgOAbIAeAPIAPgaAh7hFIAPgbIgegQIgQAbIAfAQAhbAiQgPgDgGgEQgIgEAAgJQAAgHADgEQAEgDAGAAQAJAAAEAKQAEAIgBAQIAAAA").cp();

	this.addChild(this.shape_46,this.shape_45,this.shape_44,this.shape_43);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-51.1,-51.1,102.4,102.4);


(lib.Symbol11 = function() {
	this.initialize();

	// Layer 1
	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f().s("#FBCC0A").ss(3,1,1).p("AFqlpQCWCWAADTQAADUiWCWQiWCWjUAAQjTAAiWiWQiWiWAAjUQAAjTCWiWQCWiWDTAAQDUAACWCWIAAAA").cp();

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#993333").s().p("AFgBwQgCgBgCgBQgEgCgEgDQgIAHgHACQgKADgQAAIgMAAQgKAAgKgEIgPgIIgRAKQgHACgRAAImtAAQgNAAgHgKQgHgJgEgSQgDgRgCgaIgFhLIgGgTQgEgIgHgHIAXgkQAHAWADAfIAEBaQADAhAGAJQAGAIAGAAIBjgBIARgEQgfgEgKgEQgVgKAAgWQgBgTALgSQALgRARAAQASAAALAWQAHATAAAaIAAAgICJAAIgggXQgPgKgNgFQgOgFgQAAIgTABQAGgNAIgJQAMgMAUAAQARAAAaATIApAjQAXAUAIACIBFAAIgWicIgJgFIACgYIAHgVIACACQAAALAMAFIATAHIgBAUIgEAQIgJgDIAWCQIAAAEIAYAAQAQAAAGgDQALgEAAgNIgBgLIgCgMIAIgLIAIAZQAGAOAHAGQAJAJAMAAIAMAAQAOAAAHgEQAHgFAAgLIgDgXIAIgLIAEASQAFAUAHAIQAHAHAKAAQAFAAADgDQADgCAAgGQAAgKgHgMQgEgFgFgHIAMgUQAHALADAJQAEANAAAVIAAAsIgOAAQgMABgJgEQgBgBgCgBIAAAAAlDA6IgTgKIgKAMQgFAHAAAGQAAAKAFAFQAGAFAJAAQAKAAAMgFQANgGAAgFQAAgHgVgMIAAAAAkeA+QAAAagJAOQgNAUgjAAQgOAAgJgFQgKgGAAgMQAAgMAHgSIAMgdIgDgBIALgfIAoAWQAXAQAAAQIAAAAAiUhGIAPgZIAbARIgQAaIgagSAiFAQQgFABgEADQgEAEAAAGQAAAOAPAFIAZADIgJgWQgHgOgLAAIAAAAAk9gbIgegRIAOgaIAeAPIgOAcAmFgbIANgbIAfARIgOAaIgegQ").cp();
	this.shape_48.setTransform(0.8,-2.1);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("ADIi2QADBggTAwQgZBAhTBDQijCDhUg4QhTg5CkgyQDVhSAChDQABhCBGgeQACABACABIAAAA").cp();
	this.shape_49.setTransform(16,27.5);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FDFFE7").s().p("AFkBZQhGAegBBCQgCBDjXBUQiiAyBTA5QBSA4CliDQBThDAZhCQATgxgDhfQABAAACABQAJAEAMAAIAOAAIAAgtQAAgVgEgMQgDgJgHgKIgMATQAFAHAEAFQAHAMAAAKQAAAFgDADQgDADgFAAQgKAAgHgHQgHgIgFgVIgEgRIgIALIADAXQAAAKgHAFQgHAEgOAAIgMAAQgMAAgJgIQgHgHgGgNIgIgZIgIALIACAMIABALQAAANgLAEQgGACgQAAIgYAAIAAgEIgWiQIAJADIAEgQIABgTIgTgIQgMgFAAgLIgCgCIgHAWIgCAYIAJAFIAWCbIhFAAQgIgBgXgVIgpgjQgagRgSAAQgTAAgNALQgIAIgGAOIATgCQAQAAAPAGQAMAEAQALIAgAWIiJAAIAAgfQAAgagIgSQgKgYgTAAQgQAAgMATQgKARAAATQAAAWAVAJQAKAEAgAFIgSAEIhjAAQgGAAgFgHQgGgKgEghIgDhaQgDgegIgXIgWAkQAHAHAEAJIAFASIAGBLQABAbAEARQAEASAGAIQAIALAMAAIGuAAQARAAAHgDIARgJIAPAIQAKAEAKAAIAMAAQAQAAAKgEQAHgCAIgHQAEADAEADIAAAAAFqlpQCWCWAADTQAADUiWCWQiWCWjUAAQjTAAiWiWQiWiWAAjUQAAjTCWiWQCWiWDTAAQDUAACWCWIAAAAAl+gwIAeAPIAOgaIgegQIgOAbAk2gxIAPgbIgfgQIgOAbIAeAQAh9gEQAKAAAIANIAIAWIgYgDQgPgFAAgOQAAgGAEgDQAEgDAFgBIAAAAAiNhbIAaASIARgbIgbgRIgQAaAkXApQAAgRgWgPIgogVIgLAeIACABIgMAdQgGARAAANQAAALAKAGQAJAGANAAQAkAAANgVQAIgNAAgaIAAAAAk7AlQAUALAAAHQAAAGgMAFQgMAGgLAAQgJAAgFgFQgFgFAAgKQAAgGAFgIIAKgLIATAK").cp();

	this.addChild(this.shape_50,this.shape_49,this.shape_48,this.shape_47);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-51.1,-51.1,102.4,102.4);


(lib.Symbol10 = function() {
	this.initialize();

	// Layer 1
	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f().s("#FBCC0A").ss(3,1,1).p("AFqlpQCWCWAADTQAADUiWCWQiWCWjUAAQjTAAiWiWQiWiWAAjUQAAjTCWiWQCWiWDTAAQDUAACWCWIAAAA").cp();

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#CC6600").s().p("AESAOQAIAQAAAUIAAAtQAAAVgSAVQgOATgYAOQgVAOgOAAQgNAAgPgEIg1gTIACgHIAyAHQAYAAAagPQAXgOARgVQAQgVAAgRQABgPgJgQQgIgMgLgPIAKgbQAPANAIANIAAAAAArheIASgkIASCyQAAAPgGAOIgMAXIgDgCIABgWIgQiqABNiWQADgBADgBQAAAEgFAEIgMAFIgjAMQABgIATgHIgKgGQgDgDAAgEQAAgGAKgKQAKgMAJAAQAEAAACADQADADAAADIgBAGIgDAGQgGgGgHAAIgIACQgEACAAACQABADAIAFQAJAEAGAAIAGAAAASAzIAAAsIgPAAQgJAAgJgDQgIgDgJgHQgIAIgGACQgJADgQAAIgXAAQAAASgIAPQgKAVgWAMQgbAPgqAAQglABgTgOQgWgNAAgeQAAgQAEgQIAKghIAPgfIAHAEQgNAagEAQQgEAPAAANQAAAXAQAMQARAMAeAAQAjAAAdgNQAigPAAgcQABgSgHgRQgGgNgKgMIAQgkQAJANADAMQAFAQAAAdIAXAAQARAAAIgGQAGgEAAgKIAAgLIgCgMIAHgLIADASQAFATAGAHQAIAJANAAQADAAACgCQADgDAAgEQAAgJgGgLIgJgQIAKgSIALASQAEALAAAXIAAAA").cp();
	this.shape_52.setTransform(-1.5,-6.3);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AB9hXQABhEBJgdQAEBigTAxQgZBAhUBDQiiCDhUg4QhTg5CjgyQDWhSAChDIAAAA").cp();
	this.shape_53.setTransform(16,27.4);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FDFFE7").s().p("AA9jWIgGAAQgGAAgJgEQgIgFgBgDQAAgCAEgCIAIgCQAHAAAGAGIADgGIABgGQAAgDgDgDQgCgDgEAAQgJAAgKAMQgKAKAAAGQAAAEAEADIAJAGQgTAHAAAIIAigMIAMgFQAGgEAAgEQgEABgDABIAAAAAAbieIAQCrIgBAWIADACIAMgYQAGgNAAgOIgSi0IgSAkAECgwQgIgNgPgPIgKAdQAMAPAHAMQAJAQgBANQAAASgQAVQgRAVgXAOQgaAOgYABIgxgIIgDAIIA1ASQAPAEANAAQAOAAAVgNQAYgOAOgTQASgWAAgUIAAgsQAAgUgIgQIAAAAAFqlpQCWCWAADTQAADUiWCWQiWCWjUAAQjTAAiWiWQiWiWAAjUQAAjTCWiWQCWiWDTAAQDUAACWCWIAAAAAEdC5QgCBDjXBUQiiAyBTA5QBSA4CliDQBThDAZhCQATgxgDhiQhKAdgBBEIAAAAAACgLQAAgXgCgLIgLgUIgMAUIALAQQAGALAAAJQAAAEgDADQgCACgEAAQgOAAgIgJQgGgHgFgTIgDgSIgHALIACAMIAAALQAAAKgGAEQgIAFgRAAIgXAAQAAgcgFgQQgDgMgJgPIgQAmQAKAMAGANQAHAPgBATQAAAcgiAPQgdANgjgBQgeAAgRgMQgQgMAAgXQAAgMAEgQQAEgOANgaIgHgEIgPAfIgKAfQgEARAAAQQAAAdAWAOQATANAlAAQAqAAAbgPQAWgNAKgUQAIgQAAgRIAXAAQAQAAAJgEQAGgCAIgHQAJAHAIADQAJADALAAIANAAIAAgr").cp();

	this.addChild(this.shape_54,this.shape_53,this.shape_52,this.shape_51);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-51.1,-51.1,102.4,102.4);


(lib.Symbol9 = function() {
	this.initialize();

	// Layer 1
	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f().s("#FBCC0A").ss(3,1,1).p("AFqlpQCWCWAADTQAADUiWCWQiWCWjUAAQjTAAiWiWQiWiWAAjUQAAjTCWiWQCWiWDTAAQDUAACWCWIAAAA").cp();

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#9A9B0B").s().p("ABbhrQAHAXADAeIAEBaQADAhAGAJQAGAIAGAAIAzAAQAQAAAGgDQALgEAAgNIgBgLIgCgMIAIgLIAIAZQAGAOAHAGQAJAJAMAAIAMAAQAOAAAHgEQAHgFAAgLIgDgXIAIgLIAEASQAFAUAHAIQAHAHAKAAQAFAAADgDQADgCAAgGQAAgKgHgMQgEgFgFgHIAMgUQAHALADAJQAEANAAAVIAAAsIgOAAQgMABgJgEQgIgDgHgGQgIAHgHACQgKADgQAAIgMAAQgKAAgKgEIgPgIIgRAKQgHACgRAAIgzAAQgNAAgHgKQgHgJgEgSQgDgRgCgaIgFhLIgGgSQgEgJgHgHIAXgkAkXAPQgRAGgJAGQgJAHgGAJIAJADIAOABQAMAAAJgMIgDgUAk7g6IgegQIAOgaIAeAPIgOAbAkhh1IAfAPIgOAbIgegQIANgaAArA8IgNAiQgbALgjAGQglAHgfAAIiKAAQgNABgKgYQgIgRgEgbQgGALgIAFQgJAGgJAAQgWAAgOgDQgOgDAAgEQAAgQAVgTQAUgUAggMIgCgIIgBgIQAAgGAEgIIAJgNIAXByQAFATAGAAICIAAQgFgJgEgLQgDgLAAgKQAAgWASgPQATgNAcAAQAYAAAOAJQAGAFANASIgDADIgVgFIgVgCQgaABgPAFQgOAGAAAJQAAAJAJALQAKAMAOAIIBmgY").cp();
	this.shape_56.setTransform(-1,-3);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("ADHi4QAEBigTAxQgZBAhUBDQiiCDhUg4QhTg5CjgyQDWhSAChDQABhEBJgdIAAAA").cp();
	this.shape_57.setTransform(16,27.4);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FDFFE7").s().p("ABQiKIgXAkQAHAHAEAJIAGASIAFBLQACAbADARQAEASAHAIQAHALANAAIAzAAQARAAAHgDIARgJIAPAIQAKAEAKAAIAMAAQAQAAAKgEQAHgCAIgHQAHAGAIADQAJAEAMAAIAOAAIAAgtQAAgVgEgMQgDgJgHgKIgMATQAFAHAEAFQAHAMAAAKQAAAFgDADQgDADgFAAQgKAAgHgHQgHgIgFgVIgEgRIgIALIADAXQAAAKgHAFQgHAEgOAAIgMAAQgMAAgJgIQgHgHgGgNIgIgZIgIALIACAMIABALQAAANgLAEQgGACgQAAIgzAAQgGAAgGgHQgGgKgDghIgEhaQgDgegHgXIAAAAAFqlpQCWCWAADTQAADUiWCWQiWCWjUAAQjTAAiWiWQiWiWAAjUQAAjTCWiWQCWiWDTAAQDUAACWCWIAAAAAFoBYQhKAdgBBEQgCBDjXBUQiiAyBTA5QBSA4CliDQBThDAZhCQATgxgDhiIAAAAAAgAeIhnAXQgOgIgJgLQgKgLAAgKQAAgJAPgEQAPgFAZgBIAVACIAXAEIAEgCQgPgSgHgFQgOgLgXAAQgdAAgSAPQgSAPgBAUQAAALAEALQAEAKAFAJIiIAAQgGAAgGgTIgWhyIgJANQgFAIAAAGIABAIIACAIQgfAOgVAUQgVASABAQQAAAEAOADQANADAWAAQAJAAAJgGQAJgFAFgLQAFAbAHARQALAXANAAICJAAQAfAAAlgHQAlgHAagKIANgiAksiUIgOAaIAeAQIAPgbIgfgPAlGhZIAOgbIgfgPIgNAaIAeAQAkjgOIAEATQgKALgLAAIgPgBIgJgCQAGgKAKgFQAJgGAQgGIAAAA").cp();

	this.addChild(this.shape_58,this.shape_57,this.shape_56,this.shape_55);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-51.1,-51.1,102.4,102.4);


(lib.Symbol6 = function() {
	this.initialize();

	// Layer 1
	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f().s("#11C1EA").ss(0.1,1,1).p("AfkprMg/HAAAQhkAAhGBGQhGBHAABjIAAL3QAABjBGBGQBGBHBkAAMA/HAAAQBkAABGhHQBGhGAAhjIAAr3QAAhjhGhHQhGhGhkAAIAAAA").cp();

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#0099FF").s().p("AE1AsIgJguIAAgpIAjAAIAAApIgIAuIgSAAAEXgrIAAApIgIAuIgTAAIgIguIAAgpIAjAAAj7AsIgSAAIgJguIAAgpIAjAAIAAApIgIAuAkrgCIgIAuIgTAAIgIguIAAgpIAjAAIAAAp").cp();
	this.shape_60.setTransform(-108.7,6.8);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#990000").s().p("AB4grIAKASQADAMAAARIAAApIgNAAQgKAAgJgDQgHgDgHgGQgIAHgGACQgJADgPAAIgLAAQgJAAgJgDIgOgIIgNAJQgHACgPAAIhnAAIAAgeIBnAAQANAAAGgCQAKgEAAgKIAAgKIgCgLIAFgKIAIAXQAFAKAHAGQAIAIAKAAIAMAAQANAAAGgEQAHgEAAgIIgBgKIgCgLIAHgKIAEAQQAFARAGAHQAGAHAKAAQAFAAACgDQADgDAAgEQAAgJgHgKIgIgLIALgS").cp();
	this.shape_61.setTransform(-109.7,17.9);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#6666CC").s().p("AbpkbQAAgHAIgHIAzgVQAAAHgJAIIgyAUAceliQADgIAAgHIADgBIACAPQABANgFAIQgFAJgJAAIgFgBIgGgDIgHAIQgGAGgFAAQgIAAgDgEQgEgFAAgJIACgJIADgKIAEgBQAAACgBACIAAAGIACAGQABADADAAQAHAAAEgJIAGgRIAEgCIACALQACAFAFAAQAGAAAEgIIAAAAAeGjQQAMgMASAAQARABAYAQIAmAhQAVATAHABIAKAAIAAAdIi4AAQAAAUgQAUQgOARgVANQgUAMgMAAQgNABgNgEIgxgRIACgHIAuAHQAWgBAYgNQAVgNAQgUQAOgTABgPIAAgBQAAgBAAgCQgBgMgIgNQgFgMgMgNIAKgbQAOANAHAOQAHAOAAASIAAAMIB+AAIgdgVQgPgKgNgEQgNgEgOAAIgSABQAFgNAIgHIAAAAAVTkpIAQggIARClQAAAOgFAMIgLAWIgDgBIABgVIgPifAX9jbIAFADIgHAUIgBAOQAAATATAHQAOAGAdAAIBtAAIgViRIgJgFIACgWIAGgUIADADQAAAKALAFIATAGIgCARIgEAQIgIgDIAUCGIAAAhIh+AAQgoABgSgKQgSgLAAgZQAAgPAHgTIAKgTAYbjDIADgDIAaACQAUAAAOgHQAOgFAAgIQAAgDgDgDQgDgCgEAAIgSABQgFAAgDgDQgDgCAAgFQAAgPAPgUQAPgTARgGIgEAWIgSAHQgKAGAAAJQAAADACAAIAHACIAPgCQAIAAAEAFQAEAFAAAMQAAASgNAKQgMAKgXAAIgXgCIgWgHATXitIgKgRQgIACgGAFIgJANQAHAHALAFQALAFAKABIABgCQgBgJgGgKIAAAAAQFlJQAGgKALAAQAJAAAGAIQAHAJAAAJQgBALgHAIQgIAIgMAAQgJABgEgGQgFgFAAgJQAAgNAHgLIAAAAAQbk/QgHgFgFAAQgEAAgDADIgDAIQAAAGAFACQAFADAIAAIAHgCQADgBAAgDQABgFgHgGIAAAAARNjdQAOANAHAOQAHAOAAASIAAAMIANAAQAQABAMgJQAJgGAIgLQAKgPAQgLQAOgKALgDIATAhQAJATAAAMIA5AAIgUiRIgKgFIADgWQACgKAEgKIADADQAAAKALAFIARAGIgBASIgEAPIgIgDIAUCGIAAAhIhcAAQgLABgPgGQgQgFgNgLQgKANgKAEQgLAEgTAAIgOAAQAAAUgQAUQgOARgVANQgTAMgNAAQgMABgOgEIgxgRIACgHIAuAHQAWgBAYgNQAVgNAQgUQAOgTABgPIAAgBQAAgBAAgCQgBgMgHgNQgGgMgMgNIAKgbASWkuIAzgVQAAAIgIAIIgyAUQAAgIAHgHIAAAAAKzhdIAdAOIgOAZIgbgPIAMgYANYlTQAAgHAHgHIA0gVQAAAIgJAHIgyAUAMdjqIAJALQAMAUAAAkIAAARIB2AAQgLgSgRgNQgPgNgagRIgFAFIgVgPQgKgIAAgFQAAgeAOgRQANgPAhgMIAwgTIAAAeIhGAYQgRAIAAADQAAAEALAJIAOAKQAaAUATAVQAVAYANAYIAAAdIktAAQghABgUgMQgYgOAAgeQAAgRAHgQIAMgXIAGAEIgIAPQgFAMAAAKQAAAUAVALQAUAKAcAAICRAAIAAgEQAAgUgEgMQgFgMgMgIIAOgcAEmAUIAGACQADADAAADIgCAFIgCAGQgFgFgHAAIgHACQgEABAAACQAAADAIAEQAJAFAFAAQACAAADgBIAHgCQAAAEgGAEIgKAFIggAKQAAgHARgGIgIgGQgDgDAAgDQAAgFAIgKQAKgLAIAAIAAAAAFditIgKgRQgJACgFAFIgJANQAHAHALAFQALAFAKABIABgCQgBgJgGgKIAAAAAGlhMIANgYIAdAOIgOAYIgcgOAGLhVIAcAOIgNAZIgbgPIAMgYAC/hMIANgYIAcAOIgNAYIgcgOAClhVIAcAOIgNAZIgcgPIANgYABZkMIAMgZIAcAPIgNAZIgbgPABWlTQAAgIAHgHIAzgVQABAIgDACIgGAGIgyAUACQmRQABAIgJAHIgyAUQAAgGAHgHIAzgWAG7jmQAMAQAEAIQAEANAAAfIAAApIhpAAQgMABgOgGQgQgFgNgLQgKANgKAEQgLAEgUAAIjaAAQgMAAgHgIQgFgJgEgQIgIhvIgFgRQgDgIgHgGIATghQAGAUADAcIAEBVQADAeAFAJQAGAHAFAAIBgAAQAAgVgEgKQgDgHgNgOIANgcQAMAQADAIQAFANAAAfIAAAMIBNAAQAAgVgEgKQgDgHgNgOIANgcQAMAQAEAIQAEANAAAfIAAAMIATAAQAQABALgJQAKgGAHgLQALgPAQgLQANgKAMgDIASAhQAJATAAAMIBLAAQAAgVgEgKQgDgHgNgOIANgcAl9BzIAOgZIAbAOIgOAaIgbgPAkxDlIAAAxIidAAQgkAAgWgFQgbgEgNgNQgPgOAAgWQABgPAIgVIAJgVIAHAEIgKAXIgCAOQAAAXAZAKQAZALA1AAIB+AAQgUgFgKgHQgKgJAAgMQAAgQAKgSQANgUAOAAQARAAAHAUQAHAQAAAgIAAAAAlHDLQgEgJgHAAQgGAAgDADQgDAEAAAGQAAAIAHAFQAGADAOADQAAgOgEgJIAAAAAlYhVIAcAOIgNAZIgbgPIAMgYAk9hMIAMgYIAdAOIgOAYIgbgOAiyibQAAgSAIgPQAJgRAPAAQAPABAHAQQAFAOAAAYIAAATQAAAdgVAcQgXAegfAAIgXgCIgtgOIADgGIAnAHQAVAAASgLQAPgHAOgRIAVgaQgXAAgLgIQgNgIAAgTIAAAAAiiimQAAAIAHAFQAIAEARAAQgEgQgFgHQgEgGgHAAQgFAAgEAEQgDADAAAFIAAAAArrkgQAAgHAIgHIAzgWQAAAJgCACIgHAFIgyAUAqwldQAAAHgJAIIgyAUQAAgHAIgHIAzgVAl7jTIAKASQAEANAAATIAAALIBNAAQAAgVgFgKQgDgHgNgOIANgcQANAQADAIQAEANAAAfIAAApIhmAAQgLAAgIgCQgIgDgHgGQgIAGgGADQgIACgPAAIgMAAIgRgCIgPgIIgPAJQgHABgPAAIgtAAQgLAAgHgIQgGgJgEgQIgJhvIgFgRQgEgIgHgGIAVghQAHAUADAcIADBVQAEAeAFAJQAFAHAFAAIAtAAQAOAAAGgDQAKgDAAgMIgBgKIgCgLIAHgKIAIAXQAGAMAGAGQAIAIALAAIALAAQANAAAGgEQAHgEAAgKIAAgKIgCgLIAHgKIADAQQAFATAHAHQAGAGAJAAQAGAAACgCQADgDAAgFQAAgKgHgKIgJgLIALgTAsUg7IADgHIAtAHQAWgBAYgNQAVgNAQgUQAPgTAAgQQAAgNgIgPQgGgMgMgNIAKgbQAOANAHAOQAHAOAAASIAAApQAAAUgQAUQgOARgVANQgTAMgNAAQgMABgOgEIgxgRAxmkHIAMgZIAcAOIgNAZIgbgOAwkkJIgbgPIAMgXIAdAOIgOAYAtOkpIAQggIARClQAAAOgFAMIgLAWIgDgBIABgVIgPifA18ijQAAgJgJgEQgJgFgRAAQgNAAgPAFQgOAFgPAIIgXANIBKAAQApAAAAgNIAAAAAzEkJIgbgPIAMgXIAdAOIgOAYA0xjVQgEAAgEAEQgDADAAAFQAAANANAFIAXADIgIgVQgHgMgKAAIAAAAA1Mk6IAUANIgNAYIgVgOIAOgXA0fkgIgVgOIAPgWIAVANIgPAXA0GkHIAMgZIAcAOIgNAZIgbgOA44h5IAAgdIAZAAQAMgBAKgCQALgEAPgJIAFgQIACgRQAAgSgDgWIgPhCIgLgFIAEgTIAGgTQAEAIAJAEQAIAEANABIgEAXIgDALQgDAAgDgBIgCgBIAKApQADAWAAANQABAMgDAPIgDARIAmgVQAagMASAAQAWAAANAOQAKAMAAAXIAAANIA9gBIAQgDQgdgEgJgEQgTgJAAgUQAAgSAIgQQAMgSAPAAQARAAAJAWQAHASAAAYIAAAdIBHAAQAAgVgFgKQgDgHgNgOIANgcQANAQADAIQAEANAAAfIAAAMIA8AAIgUiRIgJgFIACgWQACgKAEgKIADADQAAAKALAFIARAGIgBASIgEAPIgIgDIAUCGIAAAEIBHAAQAAgVgFgKQgDgHgNgOIANgcQANAQADAIQAEANAAAfIAAAMIA8AAIgUiRIgJgFIACgWQACgKAEgKIADADQAAAKALAFIARAGIgBASIgEAPIgIgDIAUCGIAAAhIpvAAA8ZjRQgEADAAAFQAAANAOAFIAWADIgHgVQgHgMgKAAQgFAAgDAEIAAAAA8mkVIgVgOIAPgXIAUANIgOAYA7/kgIgVgOIAOgWIAVANIgOAXA6/jmQgEAAgDAEQgDADAAAGQAAAOAPAAIAIgCIAJgEQgCgHgFgFQgIgJgHAAIAAAAA6xkdIgcgPIANgYIAcAOIgNAZA+4ijIgXANIBKAAQApAAAAgNQAAgJgJgEQgJgFgRAAQgNAAgPAFQgOAFgPAIIAAAAA/OlQQAIAEANABIgEAXIgDALQgDAAgDgBIgCgBIAKApQADAWAAANQABAMgDAPIgDARIAmgVQAagMASAAQAWAAANAOQAKAMAAAXIAAANIA8gBIAQgDQgdgEgJgEQgTgJAAgUQAAgSAJgQQALgSAPAAQARAAAJAWQAHASAAAYIAAAdIBOAAQAAgPgDgNIgOAEIgNABQgOABgHgHQgJgHAAgNQAAgYAIgSQAKgUAPAAQAWAAAKAhQAKAbAAAkIAAAsImLAAIAAgdIAZAAQAMgBAKgCQALgEAPgJIAFgQIACgRQAAgSgDgWIgPhCIgLgFIAEgTIAGgTQAEAIAJAEIAAAAAB9E/IgOAZIgbgPIAMgYIAdAOACODsIAAAqIkQAAQAAATgQAUQgOARgVANQgUAMgNAAQgMABgNgEIgygRIADgHIAuAHQAVgBAYgNQAWgNAPgTQAPgUAAgPIAAgBQABgBgBgCQAAgMgIgNQgGgMgLgNIAJgaQAPAMAGAOQAIAOAAASIAAAMIB+AAIgegVQgPgJgMgFQgNgEgPAAIgRABQAFgNAIgHQALgMASAAQARABAYARIAlAgQAUATAIABIBXAAQAAgUgEgLQgDgHgNgOIANgcQAMAQADAJQAFANAAAeIAAAAAERBmIAQghIAQClQABAOgGANIgLAWIgDgCIABgUIgOifAMyGGIAPgRIAUAOIgQAPIgTgMAMOGGIAQgRIATAOIgPAPIgUgMAHRFJIAMgYIAcAOIgNAZIgbgPAILDsIAAAMIBNAAQAAgUgEgLQgDgHgNgOIANgcQAMAQADAJQAFANAAAeIAAAqIj+AAQgKAAgIgGQgHgFAAgIIAAgMIACgLIAEAAQADAHAFADQADACAIAAIBCAAQAAgegJgTQgKgXgZgIIADghQAdAPAMAfQAKAaAAApIBLAAQAAgUgFgLQgCgHgNgOIANgcQAMAQADAJQAFANAAAeIAAAAAIwCVIgcgOIANgZIAcAOIgNAZAJIBfIAcAOIgNAZIgcgPIANgYAOkCHIANgZIAcAOIgNAZIgcgOAPXBfIAdAOIgOAZIgbgPIAMgYARZBmIAQghIAQClQABAOgGANIgLAWIgDgCIABgUIgOifAQ5BjIgDAOIgIgDIAUCGIAAAiIjtABQgMACAAAEQAAAFAQAAIAdADIALACQAFADAAAGQAAAfgVAPQgXAQg1AAQglAAgVgNQgYgNAAgYQAAgUAMgWIAUgiIAHADIgNAWQgJATAAAMQAAAVAVALQAVAKAkAAQAZAAATgEQAXgEAAgIIgDgFIgkgDQgLAAgEgCQgFgDAAgGQAAgVAMgOQALgKARgGQAMgEAPAAIBrAAQAAgUgEgLQgDgHgNgOIANgcQAMAQADAJQAFANAAAeIAAAMIA8AAIgViRIgJgEIADgWQABgKAFgKIACACQAAAKALAFIASAGIgCATAVsCKIgNAZIgcgOIANgZIAcAOAWFCTIgbgOIAMgZIAdAPIgOAYAXPCkIAJAMQALATAAAkIAAAvIijAAQghAAgTgMQgZgOAAgeQAAgQAIgRIAMgXIAFAEIgHAPQgFANAAAJQAAAUAVALQATAKAcAAICRAAIAAgEQAAgUgEgMQgEgMgMgIIAOgcAaiDhIgKgRQgIADgFAFIgJAMQAGAHALAFQAMAGAJAAIACgCQgCgJgGgKIAAAAAfxBmIAQghIAQClQABAOgGANIgLAWIgDgCIABgUIgOifAfOBxIgIgDIAUCGIAAAiIkuAAQgMAAgOgFQgQgGgNgLQgKANgLAEQgKAFgUAAIgnAAQgLAAgHgJQgFgJgEgQIgKhuIgFgSQgDgIgHgGIAVghQAGAUADAdIAEBUQADAeAFAJQAFAHAFAAIAnAAQAPABAMgJQAJgGAIgLQALgPAPgLQAOgKALgDIATAhQAJATAAAMIA6AAIgViRIgJgEIADgWQABgKAFgKIACACQAAAKALAFIASAGIgCATIgDAOIgIgDIAUCGIAAAEIB0AAQgMgSgQgNQgPgNgagQIgGAFIgUgPQgLgJAAgFQABgeAOgQQANgPAhgNIAvgTIAAAeIhGAYQgQAIAAAEQAAAEALAIIAOAKQAaAUATAVQAVAYAMAYIA6AAIgViRIgJgEIADgWQABgKAFgKIACACQAAAKALAFIASAGIgCATIgDAO").cp();
	this.shape_62.setTransform(-5.7,-5.3);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FFFFFF").s().p("AGBkcIgNAcQANANADAIQAFAKAAAVIhLAAQAAgMgJgUIgTggQgLADgOAJQgQAMgKAPQgIAKgJAHQgMAIgQAAIgTAAIAAgMQAAgfgEgNQgDgJgNgPIgNAcQANANADAIQAFAKAAAVIhOAAIAAgMQAAgfgEgNQgDgJgNgPIgNAcQANANADAIQAFAKAAAVIhfAAQgFAAgGgHQgFgJgDgeIgEhVQgDgcgGgVIgVAiQAHAGADAIIAFARIAKBvQAEAQAFAIQAHAJAMAAIDZAAQATAAALgEQAKgFAKgMQANAKAQAGQAPAGALgBIBpAAIAAgpQAAgfgEgNQgDgJgNgPIAAAAABXnHIgzAVQgIAHAAAHIAygUQAJgHAAgIIAAAAAAcmKIAygUIAHgFQACgCAAgIIgzAVQgIAHAAAHIAAAAAAflCIAcAOIANgZIgcgOIgNAZABriLIgMAYIAbAOIANgYIgcgOACGiCIAbAOIAOgYIgdgPIgMAZAFRiLIgMAYIAbAOIANgYIgcgOAFsiCIAbAOIAOgYIgdgPIgMAZAEjjkQAGAKABAKIgBACQgKgBgLgGQgLgFgHgGIAJgNQAGgFAIgCIAKAQADsggQgHAAgKAKQgJAKAAAFQAAADADAEIAIAEQgRAGAAAHIAggKIALgFQAFgCAAgEIgHACQgDAAgCAAQgFAAgJgEQgHgFgBgCQAAgCAEgCIAHgBQAHAAAFAEIADgFIABgFQAAgEgDgCIgGgCALjkhIgNAcQALAJAFAMQAEAMAAATIAAAFIiRAAQgcAAgUgKQgVgLAAgUQAAgKAFgMIAIgQIgGgDIgMAXQgHAQAAAQQAAAeAYAPQAUAMAhgBIEtAAIAAgdQgNgZgVgXQgSgWgbgTIgOgLQgLgIAAgEQAAgDARgIIBGgZIAAgdIgwASQghANgNAPQgOARAAAdQAAAGAKAIIAVAPIAFgFQAbAQAPANQAQAOALASIh2AAIAAgRQAAgkgMgUIgJgMAMemJIAygUQAJgHAAgIIgzAVQgIAHAAAHIAAAAAJ5iUIgMAZIAbAOIAOgYIgdgPARclkQgHAHAAAHIAygUQAIgHAAgIIgzAVAQTkTIgKAbQAMANAGAMQAHANABAMQAAACAAABIAAABQgBAPgOATQgQAUgVANQgYANgWAAIgtgHIgDAHIAxARQAOAEAMAAQANAAATgNQAVgMAOgSQAQgUAAgTIAOAAQATAAALgEQAKgFAKgMQANAKAQAGQAPAGALgBIBcAAIAAghIgUiGIAIADIAEgPIABgSIgRgHQgLgFAAgKIgDgCQgEAKgCAKIgCAWIAJAFIAUCRIg5AAQAAgMgJgUIgTggQgLADgOAJQgQAMgKAPQgIAKgJAHQgMAIgQAAIgNAAIAAgMQAAgSgHgPQgHgNgOgNIAAAAAPhl1QAHAGgBAFQAAADgDABIgHABQgIAAgFgCQgFgCAAgGIADgIQADgEAEAAQAFAAAHAGIAAAAAPLl/QgHALAAANQAAAJAFAFQAEAGAJgBQAMAAAIgIQAHgIABgLQAAgKgHgIQgGgIgJAAQgLAAgGAKIAAAAASdjkQAGAKABAKIgBACQgKgBgLgGQgLgFgHgGIAJgNQAGgFAIgCIAKAQAXhj5IAWAGIAXADQAXAAAMgKQANgKAAgTQAAgMgEgEQgDgFgJAAIgPACIgGgCQgDAAAAgEQAAgIAKgGIASgHIAEgXQgRAGgPAUQgPAUAAAOQAAAGADACQADACAFAAIASgBQAEAAADADQADACAAAEQAAAHgOAGQgOAGgUAAIgagCIgDAEAXDkSIgJAUQgIATAAAPQAAAZASALQASAKAogBIB+AAIAAghIgUiGIAIADIAEgQIACgRIgSgHQgMgFAAgKIgDgCIgGAUIgCAWIAJAFIAVCRIhtAAQgcAAgPgGQgTgHAAgTIABgOIAIgUIgGgEAUZlfIAPCfIgBAUIADACIALgWQAFgMAAgOIgRimIgQAhAdMkHQgIAIgFAMIASgBQAOAAAOAFQAMAEAPAKIAdAVIh+AAIAAgMQAAgSgHgPQgHgNgOgNIgKAbQAMANAGAMQAHANABAMQAAACAAABIAAABQgBAPgOATQgQAUgVANQgYANgWAAIgtgHIgDAHIAxARQAOAEAMAAQANAAATgNQAVgMAOgSQAQgUAAgTIC4AAIAAgdIgKAAQgHgCgVgSIgmghQgYgRgRAAQgSAAgMALIAAAAAbkmZQgEAJgGAAQgFAAgCgFIgCgLIgEACIgFARQgFAJgHAAQgDAAgBgDIgCgGIAAgGQABgCAAgCIgEABIgDAJIgCAKQAAAIAEAFQADAFAIAAQAGAAAFgGIAHgJIAGAEIAFABQAJAAAFgKQAFgHgBgNIgBgPIgEABQAAAHgDAHIAAAAAavlRIAygUQAJgIAAgIIgzAWQgIAHAAAHIAAAAAfkprQBkAABGBGQBGBHAABjIAAL3QAABjhGBGQhGBHhkAAMg/HAAAQhkAAhGhHQhGhGAAhjIAAr3QAAhjBGhHQBGhGBkAAMA/HAAAAeUA7IADgOIACgTIgSgGQgLgFAAgKIgCgCQgFAKgBAKIgDAWIAJAEIAVCRIg6AAQgMgYgVgYQgTgVgagUIgOgKQgLgIAAgEQAAgEARgIIBGgYIAAgeIgwATQghANgNAPQgOAQgBAeQAAAFALAJIAUAPIAGgFQAaAQAPANQAQANAMASIh0AAIAAgEIgUiGIAIADIADgOIACgTIgSgGQgLgFAAgKIgCgCQgFAKgBAKIgDAWIAJAEIAVCRIg6AAQAAgMgJgTIgTghQgLADgOAKQgPALgLAPQgHALgKAGQgMAJgPgBIgmAAQgFAAgGgHQgFgJgDgeIgEhUQgDgdgGgUIgVAhQAHAGADAIIAFASIAKBuQAEAQAFAJQAHAJAMAAIAmAAQAUAAAKgFQALgEAKgNQANALAQAGQAOAFAMAAIEuAAIAAgiIgUiGIAIADAe3AwIAOCfIgBAUIADACIALgWQAGgNgBgOIgQilIgQAhAZpCrQAFAKACAJIgCACQgJAAgMgGQgLgFgGgHIAJgMQAFgFAJgDIAKARAWVBuIgOAcQAMAIAEAMQAFAMAAAUIAAAEIiRAAQgdAAgTgKQgVgLAAgUQAAgJAFgNIAHgPIgFgEIgMAXQgIARAAAQQAAAeAZAOQATAMAhAAICjAAIAAgvQAAgkgLgTIgJgMAVMBdIANgYIgcgPIgNAZIAcAOAUyBUIgcgOIgNAZIAcAOIANgZAP/AtIACgTIgSgGQgLgFAAgKIgCgCQgFAKgBAKIgDAWIAJAEIAVCRIg8AAIAAgMQAAgegFgNQgDgJgMgQIgNAcQANAOADAHQAEALAAAUIhqAAQgPAAgNAEQgRAGgKAKQgNAOAAAVQAAAGAFADQAEACALAAIAkADIADAFQAAAIgXAEQgTAEgYAAQglAAgVgKQgVgLAAgVQAAgMAJgTIANgWIgHgDIgUAiQgLAWAAAUQAAAYAXANQAWANAkAAQA1AAAXgQQAVgPAAgfQAAgGgFgDIgLgCIgdgDQgQAAAAgFQAAgEANgCIDsgBIAAgiIgUiGIAIADIADgOAQfAwIAOCfIgBAUIADACIALgWQAGgNgBgOIgQilIgQAhAOeApIgNAYIAcAPIANgZIgcgOANqBRIAcAOIANgZIgcgOIgNAZAIOApIgNAYIAcAPIANgZIgcgOAH2BfIANgZIgcgOIgNAZIAcAOAHRC2QAAgegFgNQgDgJgMgQIgNAcQANAOADAHQAEALAAAUIhKAAQAAgpgKgaQgNgfgdgPIgDAhQAZAIALAXQAIATAAAeIhCAAQgHAAgEgCQgFgDgCgHIgEAAIgDALIAAAMQAAAIAIAFQAHAGAKAAID+AAIAAgqQAAgegFgNQgDgJgMgQIgNAcQANAOADAHQAEALAAAUIhNAAIAAgMAGXETIAbAPIAOgZIgdgOIgMAYALUFQIAUAMIAPgPIgTgOIgQARAL4FQIATAMIAQgPIgUgOIgPARADXAwIAOCfIgBAUIADACIALgWQAGgNgBgOIgQilIgQAhABUC2QAAgegEgNQgDgJgNgQIgNAcQANAOADAHQAFALAAAUIhWAAQgIgBgUgTIgnggQgYgRgRgBQgSAAgLAMQgIAHgFANIARgBQAPAAANAEQAMAFAPAJIAeAVIh+AAIAAgMQAAgSgIgOQgGgOgPgMIgJAaQALANAGAMQAIANAAAMQABACgBABIAAABQAAAPgPAUQgPATgWANQgYANgVABIgugHIgDAHIAyARQANAEAMgBQANAAAUgMQAVgNAOgRQAQgUAAgTIEQAAIAAgqABDEJIgcgOIgNAYIAcAPIANgZEggIgGGQgKgEgDgIIgGASIgEAUIALAFIAPBCQADAWAAASIgCARIgFAQQgPAJgLADQgKADgMABIgZAAIAAAdIGLAAIAAgsQAAgkgKgbQgLghgVAAQgPAAgKAUQgJASABAXQAAAOAJAHQAHAHANgBIAOgCIAOgEQADAOAAAPIhOAAIAAgeQAAgXgHgSQgJgWgRAAQgPAAgLASQgJAQAAASQAAAUATAJQAJAEAdAEIgQADIg8ABIAAgOQAAgWgLgNQgMgNgWAAQgSAAgaAMIgmAVIADgRQADgPgBgMQAAgOgDgVIgKgpIACABQADABADAAIADgMIADgWQgMgBgIgEIAAAAA/yjZQAPgIANgFQAQgFANAAQARAAAJAEQAJAFAAAJQAAANgpAAIhKAAIAXgNA7rlTIANgZIgcgPIgNAZIAcAPA75kcQAHAAAHAIQAGAGACAHIgJAEIgIABQgPAAAAgNQAAgGADgEQADgDAEAAIAAAAA85lWIAOgXIgVgOIgPAXIAWAOA9glLIAOgYIgUgNIgPAXIAVAOA9UkIQAEgDAFAAQAKAAAHAMIAHAVIgWgDQgOgFAAgNQAAgFADgEIAAAAA5yivIJvAAIAAghIgUiGIAIADIAEgPIABgSIgRgHQgLgFAAgKIgDgCQgEAKgCAKIgCAWIAJAFIAUCRIg8AAIAAgMQAAgfgEgNQgDgJgNgPIgNAcQANANADAIQAFAKAAAVIhHAAIAAgEIgUiGIAIADIAEgPIABgSIgRgHQgLgFAAgKIgDgCQgEAKgCAKIgCAWIAJAFIAUCRIg8AAIAAgMQAAgfgEgNQgDgJgNgPIgNAcQANANADAIQAFAKAAAVIhHAAIAAgeQAAgXgHgSQgJgWgSAAQgPAAgLASQgJAQAAASQAAAUAUAJQAJAEAdAEIgQADIg9ABIAAgOQAAgWgLgNQgMgNgWAAQgSAAgaAMIgmAVIADgRQADgPgBgMQAAgOgDgVIgKgpIACABQADABADAAIADgMIADgWQgMgBgIgEQgKgEgDgIIgGASIgEAUIALAFIAPBCQADAWAAASIgCARIgFAQQgPAJgLADQgKADgMABIgZAAIAAAdA1Ak+IAbAPIANgZIgcgOIgMAYA1ZlWIAPgXIgWgOIgOAXIAVAOA2GlwIgOAXIAVAOIANgYIgUgNA1rkLQAKAAAHAMIAIAVIgXgDQgNgFAAgNQAAgFADgEQAEgDAEAAIAAAAAz+k/IAOgYIgdgPIgMAYIAbAPA22jZQAAANgpAAIhKAAIAXgNQAPgIANgFQAQgFANAAQARAAAJAEQAJAFAAAJIAAAAAuIlfIAPCfIgBAUIADACIALgWQAFgMAAgOIgRimIgQAhAxek/IAOgYIgdgPIgMAYIAbAPAygk+IAbAPIANgZIgcgOIgMAYAtOhyIAxARQAOAEAMAAQANAAATgNQAVgMAOgSQAQgUAAgTIAAgpQAAgSgHgPQgHgNgOgNIgKAbQAMANAGAMQAIAOAAAOQAAAQgPATQgQAUgVANQgYANgWAAIgtgHIgDAHAm1kJIgLATIAJALQAHAKAAAKQAAAFgDACQgCADgGAAQgJAAgGgGQgHgIgFgTIgDgQIgHALIACAKIAAALQAAAKgHAEQgGAEgNAAIgLAAQgLAAgIgIQgGgGgGgNIgIgXIgHALIACALIABAKQAAALgKAEQgGADgOAAIgtAAQgFAAgFgHQgFgJgEgeIgDhVQgDgcgHgVIgVAiQAHAGAEAIIAFARIAJBvQAEAQAGAIQAHAJALAAIAtAAQAPAAAHgCIAPgIIAPAHIARADIAMAAQAPAAAIgDQAGgCAIgGQAHAGAIACQAIADALAAIBmAAIAAgpQAAgfgEgNQgDgJgNgPIgNAcQANANADAIQAFAKAAAVIhNAAIAAgMQAAgSgEgNIgKgSArqmTIgzAVQgIAHAAAHIAygUQAJgIAAgHIAAAAAsllWIAygUIAHgGQACgBAAgJIgzAWQgIAHAAAHIAAAAAjcjdQAAgEADgDQAEgEAFAAQAHAAAEAGQAFAHAEAQQgRAAgIgFQgHgEAAgJIAAAAAjsjRQAAATANAIQALAIAXAAIgVAaQgOAQgPAIQgSAKgVAAIgngHIgDAGIAtAOIAXADQAfAAAXgfQAVgbAAgdIAAgTQAAgYgFgOQgHgRgPAAQgPAAgJARQgIAPAAASIAAAAAl3iCIAbAOIAOgYIgdgPIgMAZAmSiLIgMAYIAbAOIANgYIgcgOAmBCVQAEAJAAAOQgOgDgGgDQgHgFAAgIQAAgGADgEQADgDAGAAQAHAAAEAJIAAAAAlrCvQAAgggHgQQgHgUgRAAQgOAAgNAUQgKASAAAQQAAAMAKAJQAKAHAUAFIh+AAQg1AAgZgLQgZgKAAgXIACgOIAKgXIgHgEIgJAVQgIAVgBAPQAAAWAPAOQANANAbAEQAWAFAkAAICdAAIAAgxAm3A9IAbAPIAOgaIgbgOIgOAZAsoAXIgjAAIAAApIAJAwIASAAIAIgwIAAgpAsKBwIATAAIAIgwIAAgpIgjAAIAAApIAIAwAvRCGIgLASIAJALQAHALAAAKQAAAEgDADQgCADgGAAQgJAAgGgHQgHgHgFgTIgDgQIgHAKIACALIAAAKQAAAKgHAEQgGAEgNAAIgLAAQgLAAgIgIQgGgGgGgMIgIgXIgHAKIACALIABAKQAAAMgKAEQgGACgOAAIhnAAIAAAeIBnAAQAPAAAHgCIAPgJIAPAIQAJADAIAAIAMAAQAPAAAIgDQAGgCAIgHQAHAGAIADQAIADALAAIANAAIAAgpQAAgTgEgMIgKgSA1sBAIAAgpIgjAAIAAApIAJAwIASAAIAIgwA07BwIAIgwIAAgpIgjAAIAAApIAIAwIATAA").cp();

	this.addChild(this.shape_63,this.shape_62,this.shape_61,this.shape_60,this.shape_59);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-226,-61.9,452.1,124);


(lib.Symbol2 = function() {
	this.initialize();

	// Layer 1
	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f().s("#FBCC0A").ss(3,1,1).p("AFqFqQiWCWjUAAQjTAAiWiWQiWiWAAjUQAAjTCWiWQCWiWDTAAQDUAACWCWQCWCWAADTQAADUiWCWIAAAA").cp();
	this.shape_64.setTransform(51.2,51.2);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#FFFFFF").s().p("ADHi4QAEBigTAxQgZBAhUBDQiiCDhUg4QhUg5CkgyQDWhSAChDQABhDBJgeIAAAA").cp();
	this.shape_65.setTransform(67.2,78.6);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#FDFFE7").s().p("AFKg4QgDgJgHgLIgMAUQAFAHAEAFQAHAMAAAKQAAAGgDACQgDADgFAAQgKAAgHgHQgIgIgFgUIgDgSIgIALIADAXQAAALgHAFQgHAEgOAAIgMAAQgNAAgIgJQgHgGgGgOIgJgZIgHALIACAMIAAALQAAANgKAEQgHADgPAAIhpAAQAZgMAFgHQAJgKAAgQQAAgLgEgLQgFgJgFgBQgMAAgMAOQgLAMgKATIgOAgIkRAAIgOgVQgKgMgKgIQgLgIgMAAQgPAAgMAOQgIAIgFAOIAJAFIAKgKQAGgDAGgBQAJAAAKAIIAPAOQghAEgRAEQgUAEgKANQgKANAAAXIAdBoIAEgPIABgNQAAgMgEgOIgJgcQgEgNAAgNQAAgOAdgHQAXgFAfgBIEhAAIAAANQAAAgAWARQATAQAWgBQAMAAAFgLQAFgIAAgOQAAgPgKgNQgKgKgLgGIBbAAQARAAAHgCIAQgKIAQAIQAKAEAJAAIAMAAQARAAAJgDQAHgCAIgHQAIAGAIADQAJAEAMgBIAOAAIAAgqQAAgVgEgNIAAAAAFoBXQhJAegCBEQgCBDjYBTQiiAzBUA5QBSA4CkiDQBUhEAZhBQATgygDhiIAAAAAFqFqQiWCWjUAAQjTAAiWiWQiWiWAAjUQAAjTCWiWQCWiWDTAAQDUAACWCWQCWCWAADTQAADUiWCWIAAAAAA5gaQgLAIgRAEIAPgcQALgRAIAAQAHAAAAARQAAAJgNAHIAAAAABLBCIgIACQgXAAgNgQQgJgNAAgVQAQADASAMQAWANAAAPQAAAEgDABIAAAA").cp();
	this.shape_66.setTransform(51.2,51.2);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#CC6600").s().p("AFhhZQAEAMAAAVIAAAtIgOAAQgMAAgJgEQgIgDgIgGQgIAHgHACQgJAEgRAAIgMAAQgJAAgKgEIgQgIIgQAJQgHADgRAAIhbAAQALAGAJAHQALANAAAPQAAAPgFAIQgFALgMAAQgWAAgTgQQgWgRAAgfIAAgLIkhAAQgfAAgXAFQgdAGAAANQAAANAEANIAJAcQAEAOAAAMIgBANIgEAPIgdhnQAAgWAKgNQAKgMAUgGQARgFAhgEIgPgOQgKgHgJAAQgGAAgGAEIgKAKIgJgGQAFgNAIgJQAMgOAPAAQAMABALAIQAKAHAKANIAOAUIERAAIAOggQAKgSALgMQAMgOALAAQAGAAAEAKQAFAKAAALQAAAQgJALQgFAGgZAMIBpAAQAPAAAHgCQAKgEAAgNIAAgLIgCgMIAHgLIAJAZQAGANAHAHQAIAIANAAIAMAAQAOAAAGgEQAIgFAAgKIgDgXIAIgLIADARQAFAVAIAIQAGAHALAAQAFAAADgDQADgDAAgFQAAgKgHgMQgFgFgFgHIANgUQAHALADAJIAAAAABhAhQAEgCAAgEQAAgOgWgNQgSgKgQgDQAAASAJAOQANAQAXAAIAHgCABQg7QANgIAAgIQAAgSgHAAQgIABgLARIgPAcQARgFALgHIAAAA").cp();
	this.shape_67.setTransform(48.9,54.6);

	this.addChild(this.shape_67,this.shape_66,this.shape_65,this.shape_64);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,102.4,102.4);


(lib.Symbol1copy = function() {
	this.initialize();

	// Layer 1
	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f().s("#000000").ss(0.1,1,1).p("AFyjKQAkALAiAPQCPBCAABcQAABbhrA5QhqA5h7AEQh0ADgIgEIg0ANQhrgJjNgpQjOgphDgNQhEgOAAhaQAAhVB5g+ADvinQAFACAEACQCOBCAABcQAABaiOBBQhNAjgwAF");
	this.shape_68.setTransform(-58.2,255.8);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f().s("#C0C0C0").ss(0.1,1,1).p("AH33qQABADABADAmsgdQgmgKgmgKQAAgCABgDAHO2SIACAAAmsgdQACAAACAAAFjXrIgGAA");
	this.shape_69.setTransform(-71.3,89.9);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f().s("#000066").ss(0.1,1,1).p("AiKk3QA4AtAgBIQAZBFgMBGIBpCNQA1BiASCA");
	this.shape_70.setTransform(-35.3,-94.2);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f().s("#34477A").ss(0.1,1,1).p("Ajx9IQALgCAKgDQAPAfANAeQA0B4AWBwQgBgBgBAAQAAAAABABQAGAJAHAJQACAEADAEQABACABACQAWAgAUAhQAEAGAEAGQBUCPAxCOIADAKQABACABACQAAAAAAABIACAGQAAAAAAgBQAyAHAyAFQFgAiFQg7QAQAZAJAaANpqxQgCAIgCAIQAAABAAAAQgIAbgKAaIgGAAQktARksgXQgDAAgDAAQACALACALQBZHWATHbQg+ALg9AIQgBAHgBAIQgIBGgKBGQgCANgCANQAAB0gFBzQgPGlhCGlQgOBcgRBcArpc6QgrgJgsgIQAKhtAGhtQAnqKg+qLIgBAAIgCgBAuWEhQBFjygUk6Qg3m+AHlSQANlrDYlrQACgDABgCQgIgCgHgCIAThgQAHACAHACAORxKQgEgOgFgOANpqxIgGgDAOWwWQACgagHgaABix0QAKAgAHAgQAjAEAiAEQFiAiFRgsQAHAjAEAhANpqxQAkiOgXizAh44pQhjhCjLhBIBID7Alg2tIFwFnIABgBQAVgFAKASIgBAGIACgFIAEABApQ9FQglgHgmgKApQ9FQANADANACQCtAdCYglApR7eIgEgBQgCAAgBgBIgHgBIAAAAIhZEvIgBAHQC3hdCeBXIAGAAApF7bQgGgBgGgCApk7jQgjgJgmgKApf7hQgCgBgDgBAq72qIADgIAq62qQAAAAABgBQgBAAgBABApIujIBKgLQgBgBAAAAIgBgBQgXgTgYgUQgNgLgMgLAn+uuIAAAAIgBgBABix0IgDgKQgBgFgCgFIgBgBIAAAAQAAgBAAAAIAAgBIAAACAA3w6IACACIA6AEAA5w4IgEAAAlg2tIgEgEAn+uuIABAAIAEAEIB2BaQCdBvCjBOQCXAWCaAMAARxHQgdAwgBA4AAvw0QgZAUgHA6Amm6sQhJgYhWgXAn5uqQgDgCgCgCAkwhZQAOAOAZABIFOAAQAUADAOgMQANgLAJgXIgBijIm7AAIgBACIAACXQAEAYAMAOIAAAAAAMDpIk8AAIAAlCAlAkWIAAgCIABAAABnhTIAAE8IhbAAADgFpQABAAACAAIACgMAtHE6QAMACAMAEQH1ByIahJAuWEhIBMAYAric7QFZA7FJgzQADgLADgKQABgEABgFQAIgdAIgeQAUhNAThOQB/oSBNofAgHcjIBcgVQABgEAAgDAgHcjIgkAIIgPADAric7QgEgBgDAA");
	this.shape_71.setTransform(-29.8,55.4);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f().s("#000000").ss(0.1,1,0,4).p("AAAAAIAAAA");
	this.shape_72.setTransform(-5.8,-190.6);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f().s("#330000").ss(0.1,1,0,4).p("AgLhoQgSgRAMgPQALgNAagEQAbgGAXAHQAaAIAGATQhCgGgvAbIAAAAABEAUQAAgBAAgBQAAgWgBgTQgzALgQA7QgBAGgCAGQgBAFAAAEQgIAvAbAZQAQgOALgSQgMASgPALABDAlIAAgBQABgDAAgDQAAgFAAgEABDAlQAAABAAABQgCALgDANABDAlIAAAAAgigZQgUgFgKgEQgRgIgJgLABDgXQgGgrgpAHQghAHgVAbQgHAHgBACQgCADgDAHQgRARgEAkQgDAUACATQABAEAAAEQABAJADAJQAIAgAUAKQAXALAcgZAAqBsQAMgUAIgZAgvgGQgTACgJACQgRACgLgF");
	this.shape_73.setTransform(-12.6,-192.7);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f().s("#532900").ss(0.1,1,0,4).p("AhLFcQgOA5gEhUAheE5QANgpgRgjIgBgBIAAAAQgGgJACACQgThOg8g0Qh0g5hYiXQgEgHgEgHIgBgHABwAlQALAUAUAQQAVAQAVAEQgThSAvhZQASgjBYh5QA4hOAVg6ABwAlQgVgNgSgdQgBgCgagzQgPAAgOAEQgwAMgUA3QgUA6AYA3QAEAJAGAKAhjDsQAAgBgBgBAhdE+QAAABAAACAheE5QAAACABADAhLFcQADgOAEgUQAThzAMg2AAug6QgHgfAFgiQAEggAPge");
	this.shape_74.setTransform(-85.2,-184.6);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f().s("#C0C0C0").ss(0.1,1,0,4).p("AIslTIgDAAAEiliQBgABBkAIQAJABAKABQAPABAQACIAPABIACAAAorFjQABAAAAgBQABABABAAAoXFjQgBgBgBgCAocFcQABACACAC");
	this.shape_75.setTransform(-40.8,-188);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f().s("#282828").ss(0.1,1,0,4).p("AJ7ifQABABACAAIASBnID0BqQAVAVgjADIjzgMArxEzIgoisIgBgCIh3gfQirg+FRi1QGfhqGxkOQAbgRAagRQEvhwDAgFQFQgZgOCUQhaFCj2BAAKQg3QgJAFgJAFQgEACgEADQgNAGgMAGQgIAEgJAEQgtAUgxAPQgcAJgeAIQgdAJgfAHAsVCEQgCABgCACAsaCFIAFgBQD+iUE8hLQBngXBhgRAAnBCQhnANhnAWAFyiqQADAAAEAAQCHgDB7AOACrA1QBmgHBnACAFyiqQi4AEjNAjAAnBCQBCgIBCgFArxEzQAFgDAFgCQEYiKEog/AnJKgQgCgEgBgB");
	this.shape_76.setTransform(-49.4,-228.4);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f().s("#DD9F77").ss(0.1,1,0,4).p("EgBUgoVIgBAAEgBYgoVQgBADgBAGQAAA8guBTQg8BggaAvQgBABAAABQgEAGgCAFQgpBKgDAyQgCAWAGAVQADANAHANQAOAeAfAaQgGAbgkAWQgZAPgDAaQgCAKACALQADANAAAKQAAADgBACQgCASgKAGQgTAKAKAZQAAAFgEADQgCADgDADAk48UIgBAAQgPAOgRAXQgGAIgEAHQgVAcgEAFQgtAzgkgMQgmACgPAAQgTgEgIAAQgBAAgBAAQgngBgvgOQgXgGg+gXQgkAmgYAaAFzukIBQg4IBogMIBAgfQAQAKAHARQAHAPgCAOIgFAJIAAABQACAFACAEQAOAkgeAxIgWAVIgFAmQA1gGAcAMQADABACABQANgUANgPQAagZAdgFQgLgJgDguQAAAAAAgBQgOgugUgTQgCgCgCgCIABAAQAkgGAZASQAVAQAAAQIAUANQA0AigiBcIgFADQAhANACAlIgYA8QgHATgKAQQAYAIgBAlQgLAtgZAeIAHAKEASyAnzQAAAVgPAPAH3mnQhegchFgtAyx6VQAthcgEhKQAFAEgEgHIgDgEEgBUgoVIAAgBAGBtUQASgYAcgKIA3gRIAYgIQBEgkAcg8QAZAVALAUAL7moQABgBACgBQAYgRAXgcQAdgdgJgSIgLgPAL7moQgfAWgfADIiFgHQgigHgfgKAFhsxIAggjAMLtnQgFACgEAAIAAAAAL0ucQgEgvAtARIAEAEANCsoQgRApgiAfQgUARgaAOQguAehQgKAJgtSIgyAuQAYgFAVgDIAAAAAM8qXQgUAfghAWQgEADgEACIhzAbAMvofQgFAFgEAFQgMAMgPAJQgoAihLgHEgEjgjZQAAgBAAAAEgEkgjKQAEAAABAAIAAAAQgBAAgEABEgEpgivQgEARgIAOQgEAIgEAGAk48UQAAAAAAAAEgRjggNQAHAVAXAUQAYATAaAHQAdAHAPgMQATgNgFgjEgP5ggyQgDghgTgGQggAIgNARArK7GQhvg0hMhAQgUgRgSgSQghghgYgkEgRSghuQASgKAUAGQAVAHAIAS");
	this.shape_77.setTransform(23.4,36.1);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f().s("#4B4B4B").ss(0.1,1,0,4).p("Ajg7gQAVgqAbAAQAPAAANANAgs0wQBeACAABiIAAJ0QAGgRANgNQAXgXAhAAQAhAAAYAXQAXAYAAAhIAAABQADgbAUgUQAYgXAhAAQAhAAAXAXQAYAYAAAhIAALyQAAAhgYAYQgWAWggABIAuAAIAAXIAE+b8QgPAPgVAAIAAAAQgVAAgPgPQgPgPAAgVIAA3IIA0AAQgggBgXgWQgXgYAAghIAAgBQgDAbgUAUQgYAXghAAQghAAgXgXQgNgNgGgRIAAI5QAABkhiAAIgiAAQABAEACAEQAXBGADBdQABARAAASQAAAPgBAPQgDBhgXBHQgbBRgmAAQgmAAgbhRQgbhSAAh0QAAh0AbhSQABgEACgEIg6AAQhkAAAAhkIAA/LAhv64QgJgdgLgTQgGgKgHgHAimwCQAIgCAIAAQAsAAAfA9QAgA9AABWQAAAFAAAFQgCBQgeA5QgfA9gsAAQgIAAgIgCQgigJgagyQgfg9AAhWQAAhAARgzQAGgRAIgPQAagyAigJIAAAAAAGsqQACApACA4QAAAAAAABQACBBABBJQAECvAADdQAADGgDCjQgBAgAAAfQgCA5gBA0QAAAAAAABQgHDcgIAAQgKAAgHjcQAAgBAAAAQgCg1gBg5QgEi6AAjtQAAjdADiwQAChIAChBQAAgBAAAAQACg3ACgpQAFh9AIAAQAFAAAGB7IAAABAAypYQgFAMAAAPIAALyQAAAPAFAMADNo8QAAAFAAAFIAALxAEbEQIAEAAAiWAlQAsAAAfA9QAgA9AABWQAABWggA9QgfA9gsAAQgIAAgIgCQgigJgagyQgfg9AAhWQAAhBARgyQAGgRAIgPQAagyAigJQAIgCAIAAIAAAAAjONtIB8AAAE+b8IAPgk");
	this.shape_78.setTransform(110.2,115.6);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#000066").s().p("AiKk3QA4AtAgBIQAZBFgMBGIBpCNQA1BiASCAQgxiPhXiOQgDgHgCgGQgUgegWggQgCgDgBgCQgCgEgDgDQgGgKgGgIIAAgBQgWhwg0h4IAAAA").cp();
	this.shape_79.setTransform(-35.3,-94.2);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#EAEAEA").s().p("AAFgCQABACABAAQABACACABIgDAAQAAgBAAgCQAAACAAABIgMAAQAFgDAFgCIAAAAAgJADQABAAABgBQABABAAAAIgDAA").cp();
	this.shape_80.setTransform(-95.5,-152.8);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#F3B3A3").s().p("AAaApQAAgBAAAAQAAAAAAABQgFgCgTgGQgSgGgogwQAXADAUgGQARgGALgFQAMgFAPAAQAOgBABAFQAAADgBADQgCARgKAHQgTAIAKAZQAAAFgEADQgCACgDADQABAAABABQACABgEgBIAAAA").cp();
	this.shape_81.setTransform(-10.5,-149.3);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#FFFFFF").s().p("AARBcQgcAZgXgLQgUgKgIggQgDgJgBgJQAAgEgBgEQgCgTADgTQAEgjARgTQADgHACgDQABgCAHgHQAVgbAhgHQApgHAGArQgzALgRA8QgBAFgBAGQgBAFAAAEQgIAvAbAZIAAAAAAQAoQADgCADACQADAAABAEQACACgCADQgCADgDABQgDABgDAAQgCgBgBgCQgBAAAAgBQgBgDABgDQACgDADgBIAAAAAAzgLQABABABAAQAAACABABQABADAAACQAAACgBACQgCAGgGADQgGACgGgDQgBAAgBgBQgCgBgBgBQgBgCgCgDQAAgBAAgBQgCgDACgEQACgGAGgCQAGgDAGADQADABACADIAAAA").cp();
	this.shape_82.setTransform(-12.8,-187.9);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#000000").s().p("AGdmtQABACACABQACAAAEgBQADgBACgDQABgDgBgCQgCgEgCAAQgDgCgDACQAFgOALgRQABABABAAQAGADAFgCQAGgDACgGQACgCAAgEQAAgCgCgDQAAgBgBgCQAAAAgBgBQAKgIAFAEQABACACAEIAAAAQAAABAAABQgCALgDANQgFASgHAOQgEAHgEAGQgNASgPALQgKgQAGgWIAAAAAG9mkQAMgUAIgZQgIAZgMAUIAAAAAlfDDQBXAXBJAYIBID7IgHAAQiehXi3BdIABgHIBZkvIAAAAIAHABQABABACAAIAEABIAOAEQgBAAgBgBIAAAAAnTHzQgBAAgBABIADgIIgBAH").cp();
	this.shape_83.setTransform(-52.9,-139.7);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#8A4500").s().p("AkXjEQBmgWBpgNQgVA6g5BOQhYB4gSAjQgvBaAUBSQgVgEgVgQQgUgQgLgUQAOjFAxiNQAGgRAIgRIAAAAADyguQgSgRANgPQAKgNAcgEQAbgGAYAHQAaAIAFATQhBgGgyAbIAAAAAFDBfIAAAAIAAAAIAAAAQgCgEgBgBQgFgFgKAIQgDgDgDgBQgGgDgFADQgGACgCAGQgCAEABAEQAAACABACQABACACACQABACACAAQgLARgFAOQgEABgBADQgCADABADQABABABAAQgGAXAKAPQAPgKANgTQgMATgPAOQgdgaAIgvQAAgEABgFQABgGACgGQASg9AygKQACASAAAYQAAABAAABIAAABQAAAAAAABQAAAEAAAEQgBADAAAEQAEAAABAAIgBAAQgBAAgDAAIAAAA").cp();
	this.shape_84.setTransform(-38.2,-198.5);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#445EA2").s().p("AFvCVQisAvjBhbIkJjIQCeBuCgBNQCaAWCaAMQiagMiagWQighNiehuIh1haIgEgDIgBgBIg2gtQCEBaCMBLQCeBmCsAcQGVA0GpghQgIAbgKAZIgGAAQktASksgXQgDgBgCAAQACALACAMIAAAAEABAAogQABgFACgEQAIgeAHgdQAUhOAThNQCBoTBNoeQAABzgEB0IhZJyQgVBsgdBsQgXBSgcBSQgJAXgIAYIgkAIIgQAEEgJmAosQgDAAgDgBQgsgIgrgJQAJhtAGhsQAnqLg9qLIgBAAIgDgBQACABACAAQgCAAgCgBIhLgYQBFjygVk7Qg2m+AHlQQAMlrDYlsQACgDABgCQgHgCgIgCIAThgQAHACAHACQAmAKAlAHIADAKQghAKAHAdQAGAXAdAiQgGgBgHgCIgDAAQgCgBgCgBIgGgBQgDgBgCgBQgkgJgmgKQAmAKAkAJIAFADIhaEuIgCAIIABAAQifFuA3F4IBQHKQgCEuhbEMQgMgDgMgDQAMADAMADQH0BzIbhJIABAOIoBBIIkKAaQhyAngMA5IgTMmQAAAOABAOQABBqgJBqQgKBzgVBzQgBADgBACIAAAAEAAegorQiwDRA4CxQhiAQhmAYQk9BKj9CXIgFABIh3gfQirg/FQi2QGghqGxkOIAAAAAPykBQgEghgHgiQlRAslhgjQgjgDgigEQgIghgKggIgFgVQAOAkA0AiQA1AjK9gpQAIAagCAaIghAjABCrYIhShSQjkiKgEArQATCvAuAsIFqFlIgCACIgDgBIgCAAQgKgTgVAFIgBABIlwlnIADgEIhIj7QDLBBBgBCQABAAABACQAGAIAGAJQADAEACAEQABACACADQAWAgAUAgIAAAAAnIvqQAAABABABIgOgFQAHACAGABIAAAAAizKXIAAFEIE7AAIlTAdIgGk/QgWAHgDg5IAniuIAACXQADAZANAOIAAAA").cp();
	this.shape_85.setTransform(-42.3,-19.8);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#516CB5").s().p("AAklxIADAKQABACABACQAAAAAAABQABADABACQAyAHAyAFQFgAiFQg7QAQAZAJAaQAFAOAEAOQq+Apg0giQg1gjgOgkIAGAWQAKAgAHAgQAjAEAiAEQFiAiFRgsQAHAjAEAhQAXCzgkCMIgGgDIAGADQgCAIgCAIQAAABAAAAQmpAimTg1QivgcidhlQiMhMiFhZIA2AtIABAAIAEAEIB2BaIEKDHQC/BbCsgvQBZHWATHdQg+ALg9AIQgBAHgBAIQgIBGgKBGQgCANgCANQhNIfh/ISQgTBOgUBNQgIAegIAdQgBAFgBAEQgDAKgDALQlJAzlZg7QAAgDABgDQAVhzAKhzQAJhqgBhqQAAgOAAgOIATslQAMg6BygmIEJgaIIBhIIgBgPQoaBJn1hyQBbkNACkuIhPnJQg3l4CeluIgBAAQABgBABAAQgBABAAAAQAAAAABgBQC3hdCeBXIAGAAIgCAEIFyFnIABgBQAVgFAIASIAAAGIABgFIAEABIACgCIlrllQgtgsgUivQAFgrDkCJIBTBTQAEAGAEAGQBWCPAvCOIAAAAAjwvhQA0B4AWBwQgBgBgBAAQhjhCjLhBQhJgYhWgXQgdgigFgXQgHgeAhgJIgDgKQANADANACQCsAcCZgkQAKgDALgCQAPAfANAeIAAAAEAAmAo2QAAADgBAEIhcAVQAJgYAIgYQAchSAVhSQAehrAUhsIBZpzQgPGlhCGlQgOBcgRBcIAAAAEAB+giTQi2AEjPAkQg4ixCyjRQAbgRAagRQEthwDAgGQFQgYgOCUQhaFBj2BBQh7gPiHADQgEAAgDAAIAAAAAqPuyIgFgCQADABACABIAAAAAp4h0IBKgLQgBgBAAAAIgBgBQgXgTgYgUQgNgLgMgLQAMALANALQAYAUAXATIABABQAAAAABABIhKALAouh/IAAAAIgBgBIABABIAAAAQACACADACQgDgCgCgCIAAAAAApliIACAGQAAAAAAgBQAAABAAAAIgCgGAAylFIgDgKQgBgFgCgFIgBgBIAAAAQAAgBAAAAIAAgBIAAACIAAgCIAAABQAAAAAAABIAAAAIABABQACAFABAFIADAKAAHkLIACACIA6AEIg6gEIgCgCAAJkJIgEAAIAEAAAmQp+IgEgEIAEAEAgdkYQgfAwgBA4QABg4AfgwIAAAAAAAkFQgYAUgHA6QAHg6AYgUIAAAAAlgLUQAOAOAZABIFOAAQAUADAOgMQANgLAJgXIgBijIm7AAIgBACIABgCIG7AAIABCjQgJAXgNALQgOAMgUgDIlOAAQgZgBgOgOIAAAAAlwIXIAAgCIABAAIgBAAIAAACAA3LaIAAE+IhZAAIk+AAIAAlEQgMgOgEgYIAAiXIgnCtQAEA5AVgHIAGFAIFWgeIBZAAIAAk+ACwSYQABAAACAAIACgMIgCAMQgCAAgBAAIAAAA").cp();
	this.shape_86.setTransform(-25,-26);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#F4C5A2").s().p("AhiwkQgBA7guBUQg7BfgbAwQAAABgBAAQgDAGgDAFQgpBKgDAyQgBAWAFAWQAEANAGANQAPAdAfAbQgHAagjAWQgZAQgDAZQgCAKACAMQACANAAAJQAAgFgPABQgPAAgLAFQgMAFgTAGQgTAGgXgDQAoAyAUAGQATAGAEACIAAAAQgPANgSAYQgFAIgFAGQgUAcgFAGQgsAyglgMQgqgQgUgCQgUgCAAgBQAAgBgJgCQjAgchFiQQgLgXgIgaQgNgrgEguQAAgEAAgFQgCgYACgYQAFhwA8h+QBXi4COhZQBlgHBnABQBhABBjAJQAIAFAIAGQADgEAAgFQAQABAQACIAOAAQgHAAABABQADAEAEAFIAAAAAJYKUIgyAtQAYgFAUgCIABAAQA1gHAcAMQACABACABQANgUAOgOQAZgaAdgFQgKgIgDguQgEgvAsARIAFADIATANQA0AjgiBbIgEAEQAhAMABAlIgYA9QgGASgLARQAZAIgBAkQgMAtgZAeIAHAKIALAPQAJATgdAcQgXAcgXASQgCABgCABQgfgCgcgDQh+gNhCgrQgkgYgRghQg3hrATiEQAXhWAogkIAZgIQBEglAcg7QAYAVALAUIAAAAQADAFACAFQAOAjgeAyIgWAVAMCJ/QgFACgDgBIgBAAIABAAQADABAFgCIAAAAAM6K+QgRAogjAfQgUASgaAOQgtAehRgKQBRAKAtgeQAagOAUgSQAjgfARgoIAAAAAMzNPQgUAeghAXQgEACgEADIhyAaIBygaQAEgDAEgCQAhgXAUgeIAAAAAMmPGQgEAGgFAEQgMANgPAJQgnAhhLgHQBLAHAnghQAPgJAMgNQAFgEAEgGIAAAAAl9txQAygbBBAGQgFgTgagIQgYgHgbAGQgcAEgKANQgNAPASARIAAAAAktsgQgFgrgpAHQgkAHgVAbQgGAHgCACQgBADgEAHQgQATgFAkQgDAUADATQAAAEABAEQAAAJADAJQAJAgAUAKQAWALAfgZQAPgOAMgSQAEgGAEgHQAHgOAFgSQADgNACgLQAAgBAAgBQADAAABAAIABgBQgBABgEgBQAAgDABgDQAAgFAAgEQAAAAAAgBIAAAAQAAgBAAgBQAAgYgCgTIAAAAAmUsiQgUgFgJgEQgRgIgKgLQAKALARAIQAJAEAUAFIAAAAAmhsPQgSACgJACQgRACgLgFQALAFARgCQAJgCASgCIAAAA").cp();
	this.shape_87.setTransform(24.2,-115);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#F1B88D").s().p("AArxDQAJABAKABQgBAGgDAEQgIgGgHgGIAAAAABsw0QgDgFgEgEQAAAAAHAAIACAAQgBADgBAGIAAAAAo+iuQiYAkitgcQgNgDgNgCQglgIgmgKQAshcgEhKQAFAEgEgGIgDgFQADgNAEgVQAUhzAMg2QAHAVAXAUQAYATAaAIQAdAGAPgLQATgOgFgjQAFAjgTAOQgPALgdgGQgagIgYgTQgXgUgHgVQgGgJgEgKQgZg2AUg6QAUg6AzgMQANgEAPAAQAaAzACACQASAgAVANQALAUAUAQQAVAPAVAEQgUhRAvhbQASgjBYh6QA5hOAVg6QBCgIBCgFQiOBZhXC4Qg8B/gFBvQgBAZABAYQAAAFABADQADAuANAsQAIAZAMAXQBECQDBAdQAJABAAABQgBACAUACQAUACArAQQgmACgPAAQgTgEgIAAQgBAAgBAAQgngBgvgOQgXgGg+gWQgkAlgYAaIAAAAAsxpaQgDghgTgGQggAJgNAQQANgQAggJQATAGADAhIAAAAAIcPmQAkiOgXiyIAggkQACgagHgaQgEgOgFgOIBQg4IBogLIBAggQAQAKAHARQAHAPgCAOIgFAKQgLgUgZgVQgcA7hEAlIgYAIIg3AQQgcAKgSAYQASgYAcgKIA3gQQgoAkgYBWQgSCEA3BrQARAgAkAYQBBArB/AOQAcADAfACQgfAVgfAEIiFgHQgigIgfgJQhegdhFgtIAAAAAPpIgIgEgDQgtgRAEAvQAAgBAAgBQgOgugTgTQgDgCgCgCIABAAQAlgGAYASQAVARAAAPIAAAAAvUmIQgBgCgCgCQgCgDgCgDQABgEAGAJQAAADAAACIAAAAAMjKrIAAAAQgUACgZAFIAygtIgFAmAoCjtQhvg1hMhAQgUgRgSgSQghghgYgjQAYAjAhAhQASASAUARQBMBABvA1IAAAAAuKqWQASgKAUAGQAVAHAIASQgIgSgVgHQgUgGgSAKIAAAA").cp();
	this.shape_88.setTransform(3.4,-113.5);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#515151").s().p("AhNgSIA7ghIDmBeQANAKgmgBImRgbIAzgPQAqgKAsgSIAAAAAgSgmIhTAlIhXAWIGIAZIjehU").cp();
	this.shape_89.setTransform(18,-227.1);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#333333").s().p("EgDfgkeQkoA/kZCKQgFACgEACIgpisQACgBADgBQD9iXE9hKQBmgYBigQQDNgkC3gEQh0APhwAyQitBmDkAhQB7ANB1gIQgeAIgfAHQAfgHAegIQAdgIAdgKQAwgRAugUQAIgEAJgEQAMgGAMgGQAEgCAEgCQAKgFAJgFIDzBsQAVAVgiACIj0gMIAAAAIgDAAIgDAAIgOAAQgQgCgQgBQgJgBgKgBQhjgJhhgBQhngBhlAHQhDAEhAAJQhpANhmAWIAAAAEgJdAjMQADAAADABQFaA7FHgzQADgLACgKIAQgDQAEACAFACQCOBBAABcQAABdiOBAQhNAjguAFQAugFBNgjQCOhAAAhdQAAhciOhBQgFgCgEgCIAkgIIBegVQAAgEABgDQAkAMAiAPQCOBBAABcQAABdhqA5QhqA6h7ADQhyADgIgEIg0AOQhtgKjOgpQjNgphDgNQhEgNAAhdQAAhVB5g9IAAAAEAIbgmKQgsASgpAMIg0APIGTAbQAnABgOgKIjnhgIg8AhEAJKglFIAAAAIABAAIgBAAEABQAjVIgGAAIAGAA").cp();
	this.shape_90.setTransform(-43.8,15.2);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#414141").s().p("ABLBkQhzAJh7gNQjmgiCvhjQBwgyBygPQAEAAADAAQCHgDB7AOQACABACAAIASBlQgJAFgKAFQgEACgEADQgMAGgMAGQgJAEgIAEQguAUgwARQgdAJgdAIIAAAA").cp();
	this.shape_91.setTransform(-13.3,-235.2);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#663300").s().p("EAUvAoDIAPgkQAAAVgPAPIAAAAEgPXgggQgMA2gTBzQgEAUgDAOQgOA5gEhUIACAAQgBgCgBgBQgBgDAAgCQANgpgRgjIgBgBIAAAAQAAgBgBgBQgCgEgBgBQgThOg8g0Qh0g5hYiZQgEgHgEgHIgBgHQAEgCAFgCQEZiKEog/QgHAQgGASQgyCNgODHQgVgNgSgfQgBgCgagzQgPAAgOAEQgyAMgUA5QgUA6AYA3QAEAJAGAKIAAAAEgOCgjtQgHgfAFgiQAEggAPgeQgPAegEAgQgFAiAHAfIAAAA").cp();
	this.shape_92.setTransform(9.3,38);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#999999").s().p("AhA1fQgOAPgNAUQgCgBgCgBQgBgDgBgEQgGgZAAglQAAgkAGgaQAGgaAIAAQAFAAADAHQAEAGACANQACAIACAKQACAUAAAYQAAAUgBAQIAAAAAg1p9QgLgmAVAAQAWAAAPAmQAKAcADAlQAAAMAAANQAAAOAAAMQgDAlgKAcQgPAlgWAAQgVAAAHglQAGglAEg1QAEg2gKglIAAAAABdonQABApACA4QAAAAAAABQACBBACBJQADCvAADcQAADIgCCiQgBAggBAfQgBA5gCA0QAAABAAABQgHDcgKAAQgKAAgHjcQAAgBAAgBQgBg1gCg4QgEi7AAjuQAAjcAEiwQABhIAChBQAAgBAAAAQACg3ACgpQAGh9AHAAQAIAAAGB7IAAABAgGGeQAKAbADAmQAAAMAAANQAAANAAANQgDAkgKAdQgPAlgWAAQgVAAAHglQAGgmAEg0QAEg2gKglQgLgmAVAAQAWAAAPAmIAAAAAAHUbQAAAQAAARQAAAQAAAQQgCAtgGAjQgLAwgPAAQgPAAgKgwQgLguAAhCQAAhDALgvQAKguAPAAQAPAAALAuQAGAkACAtIAAAA").cp();
	this.shape_93.setTransform(101.6,89.7);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#666666").s().p("ADju6QAHAIAGAKQALATAKAdQAAAAAAABQADAuALAJQgdAEgaAaQACgQAAgUQAAgYgCgUQgCgKgCgIQgCgNgEgGQgDgHgFAAQgIAAgGAaQgGAaAAAkQAAAlAGAZQABAEABADQgdgMg1AGIAFgmIAWgVQAegxgOgkQgCgEgCgFQAWgqAbAAQAPAAANANIgBAAQACABACACIAAAAEALDAoXIgPAkQgPAPgVAAIgBAAQgVAAgPgPQgPgPAAgVIAA3HIA0AAQgggBgWgWQgYgYAAghIAAgBQgDAbgUAUQgXAXghAAQghAAgYgXQgNgNgGgRIAAI5QAABkhkAAIghAAQABAEABAEQAXBFAEBeQAAARAAASQAAAPAAAPQgDBhgYBGQgbBSgmAAQgmAAgbhSQgbhRAAh0QAAh0AbhSQACgEABgEIg5AAQhkAAAAhkIAA/LQAfAKAiAHICFAHQAfgDAfgWQABgBACgBQAYgRAXgcQAdgdgJgSIgLgPQBgACAABiIAAJyQAGgRANgNQAYgXAhAAQAhAAAXAXQAYAYAAAhIAAABQADgbAUgUQAXgXAhAAQAhAAAYAXQAXAYAAAhIAAL0QAAAhgXAYQgXAWgfABIAuAAIAAXHEgI3gpJIDgBVImKgYIBXgZIBTgkADOjCQAHgCAIAAQAtAAAfA9QAfA9AABUQAAAFAAAFQgCBQgdA5QgfA9gtAAQgIAAgHgCQgjgJgagyQgfg9AAhWQAAg+ASgzQAGgRAHgPQAagyAjgJQgjAJgaAyQgHAPgGARQgSAzAAA+QAABWAfA9QAaAyAjAJQAHACAIAAQAtAAAfg9QAdg5AChQQAAgFAAgFQAAhUgfg9Qgfg9gtAAQgIAAgHACIAAAAADohAQAKAlgEA0QgEA1gGAlQgHAlAVAAQAWAAAPglQAMgcADglQAAgMAAgOQAAgNAAgLQgDgkgMgcQgPgmgWAAQgVAAALAmIAAAAAF8AUIAAgBQgGh5gIAAQgHAAgGB7QgCApgCA3QAAAAAAABQgCBBgBBIQgECwAADdQAADvAEC6QACA5ABA1QAAAAAAABQAHDcAKAAQAKAAAHjcQAAgBAAAAQACg0ABg5QABgfABggQACijAAjIQAAjdgDivQgChJgChBQAAgBAAAAQgCg4gBgpIAAAAAGnDmQgEAMAAAPIAAL0QAAAPAEAMQgEgMAAgPIAAr0QAAgPAEgMIAAAAAJDECQgBAFAAAFIAALzIAArzQAAgFABgFIAAAAAKQRQIAFAAIgFAAADdNlQAtAAAfA9QAfA9AABWQAABWgfA9QgfA9gtAAQgIAAgHgCQgjgJgagyQgfg9AAhWQAAhBASgyQAGgRAHgPQAagyAjgJQAHgCAIAAQgIAAgHACQgjAJgaAyQgHAPgGARQgSAyAABBQAABWAfA9QAaAyAjAJQAHACAIAAQAtAAAfg9QAfg9AAhWQAAhWgfg9Qgfg9gtAAIAAAAAEmdYQgCgugIgjQgLgvgPAAQgPAAgKAvQgLAvAABCQAABDALAuQAKAvAPAAQAPAAALgvQAIgjACguQAAgPAAgRQAAgQAAgQIAAAAAEXPaQgPglgWAAQgVAAALAlQAKAmgEA1QgEA1gGAmQgHAlAVAAQAWAAAPgmQAMgcADglQAAgMAAgNQAAgNAAgNQgDglgMgcIAAAAAClatIB9AAIh9AA").cp();
	this.shape_94.setTransform(72.9,32.4);

	this.addChild(this.shape_94,this.shape_93,this.shape_92,this.shape_91,this.shape_90,this.shape_89,this.shape_88,this.shape_87,this.shape_86,this.shape_85,this.shape_84,this.shape_83,this.shape_82,this.shape_81,this.shape_80,this.shape_79,this.shape_78,this.shape_77,this.shape_76,this.shape_75,this.shape_74,this.shape_73,this.shape_72,this.shape_71,this.shape_70,this.shape_69,this.shape_68);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-146.6,-295.8,293.5,591.7);


(lib.Symbol10_1 = function() {
	this.initialize();

	// Layer 1
	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f().s("#0099FF").ss(0.1,1,0,4).p("AAAE8QACgJAIAHQAFAEAQARQArAlA7gPQAXgBAagMQA0gXAQg5IAngCQApgDAKgFQAFgDAJAHQAFAFAOANQAhAYAygNQASgFAOgMQAagZgXgoQAvgIAtgXQBbgugFhIQgHgXgSgaQgjgzgwgQQACgkgUghQgmhEhnAKQgQgtgogfQhQg+h2BGQgig5g4geQhtg8hpCJQgygfg3gGQhugLgaB+QgmgHgpAMQhRAZgMBiIgkAWQgmAdgQAdQgDAIgDAIQgHAXAHAWQAVBCCNA9IADATQAFAWAMANQAlArBVg6IAiAMQAqAKAqgGIAEAPQAHASAMAPQAlAwBKgCIA0gKQA1gOAEgSIAAAAIADgLAAli+QgVAUgbAAQgdAAgUgUQgVgUAAgcQAAgcAVgUQAUgTAdAAQAbAAAVATQAUAUAAAcQAAAcgUAUIAAAAAkjErQAAAKgHAHQgIAHgKAAQgLAAgHgHQgIgHAAgKQAAgJAIgHQAHgHALAAQAKAAAIAHQAHAHAAAJIAAAAAkIE6QAGAAAFADQAEAEAAAGQAAAFgEAEQgFAEgGAAQgGAAgEgEQgFgEAAgFQAAgGAFgEQAEgDAGAAIAAAAAFNEgQAHAHAAAKQAAAJgHAHQgHAHgKAAQgKAAgIgHQgHgHAAgJQAAgKAHgHQAIgGAKAAQAKAAAHAGIAAAAAEOE+QAHAAAEAEQAFAFAAAGQAAAGgFAEQgEAFgHAAQgHAAgFgFQgFgEAAgGQAAgGAFgFQAFgEAHAAIAAAA").cp();

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#5BBCF9").s().p("AAAE8IADgLIgDALIAAAAQgEASg1AOIg0AKQhKACglgwQgMgPgHgSIgEgPQgqAGgqgKIgigMQhVA6glgrQgMgNgFgWIgDgTQiNg9gVhCQgHgWAHgXQADgIADgIQAQgdAmgdIAkgWQAMhiBRgZQApgMAmAHQAah+BuALQA3AGAyAfQBpiJBtA8QA4AeAiA5QB2hGBQA+QAoAfAQAtQBngKAmBEQAUAhgCAkQAwAQAjAzQASAaAHAXQAFBIhbAuQgtAXgvAIQAXAogaAZQgOAMgSAFQgyANghgYQgOgNgFgFQgJgHgFADQgKAFgpADIgnACQgQA5g0AXQgaAMgXABQg7APgrglQgQgRgFgEQgIgHgCAJIAAAAAAli+QAUgUAAgcQAAgcgUgUQgVgTgbAAQgdAAgUATQgVAUAAAcQAAAcAVAUQAUAUAdAAQAbAAAVgUIAAAAAkjErQAAAKgHAHQgIAHgKAAQgLAAgHgHQgIgHAAgKQAAgJAIgHQAHgHALAAQAKAAAIAHQAHAHAAAJIAAAAAkIE6QAGAAAFADQAEAEAAAGQAAAFgEAEQgFAEgGAAQgGAAgEgEQgFgEAAgFQAAgGAFgEQAEgDAGAAIAAAAAFNEgQAHAHAAAKQAAAJgHAHQgHAHgKAAQgKAAgIgHQgHgHAAgJQAAgKAHgHQAIgGAKAAQAKAAAHAGIAAAAAEOE+QAHAAAEAEQAFAFAAAGQAAAGgFAEQgEAFgHAAQgHAAgFgFQgFgEAAgGQAAgGAFgFQAFgEAHAAIAAAA").cp();

	this.addChild(this.shape_96,this.shape_95);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-66.9,-36.1,134,72.4);


(lib.Symbol4 = function() {
	this.initialize();

	// Layer 1
	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#0099FF").s().p("AE+gMQAVAHgCAFQAKANgqANIAOAMQAIAOgaAHQgwAFgEgKIAAgeIj3AAQAcgVApgFQBSgPBUAYIAUgOQAbgOAiAJIAAAAABYgSIgmAJQiGguiNAMQgsAEgnAJIgeAJQB3g3CmAXQAmAGAfAIQAiAHAcAKQAFACAFACIAAAA").cp();
	this.shape_97.setTransform(2.4,0.6);

	this.addChild(this.shape_97);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-31.5,-5.5,67.9,12.3);


(lib.Symbol3 = function() {
	this.initialize();

	// Layer 1
	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#0099FF").s().p("AlGg0QgLAMgFANQgQAkA3AUQgDgFgEgHQgGgNADgEIAdAdQAoAdAyABIAjABQAjgCAEgKQgKgBgNgCQgagFgLgJIAUgIQAagIAfgDQBlgMBvAkQgMgIgMgKQgXgSgDgMIAcgBQAjAAAjAEQByALBJAyQADgLAIgNQAQgbAbgGIAGAQQAHAUABANIAlgfQAwgdA4gCQBEgEAmAYQAmAZgjAiIhfAAQgBgCAAgDQABgGAFgFQAQgOA2AFQADgQgUgIQgmgPhtAhQgKAFgMAGQgWAMgFAHIp7ADIAAgBIm4AAQgggKABgcQAAgEACgEQAEgJAIgHQAagTA6AOIAJAFQAIAJgEAJQgHAKgPABQAGgFADgFQAGgLgOgBQgNgBgGAAIgCAAQgHACgGADQgNAFADAGQAFALALADQAWAGBMAAIAKgHQAMgIAQgGQAygUBBAIQgIgLACgPQAEggAzgNIgLAK").cp();
	this.shape_98.setTransform(0,3.4);

	this.addChild(this.shape_98);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-67.9,-2.9,135.8,12.7);


(lib.Symbol2_1 = function() {
	this.initialize();

	// Layer 1
	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f().s("#B4ECFA").ss(0.1,1,1).p("A/nAqIAeAPQAnAPApADQCCAHBkh7IAhAmQAqAnAxAWQCcBFCgieIAhAfQAsAiAyARQCeA3CgiOIAeAiQAoAkAvATQCVA9CfiRIAkAgQAuAlAyARQCgA3CNihIAUAkQAcAlApAUQCCBBDOiUIAcAhQAmAiAvASQCUA5C5iOIAdAhQAnAjAtASQCTA7CfiRIATAdQAaAfAjAVQAnAYAjALQAHACAHABIABAAQA6AOAxgZIARgHQAVgKASgPQAVgQAPgTAZZBDIAzgfQAbgUAPgQQALgOAHgRQAAAAABAAQAFgMADgNQAEgNABgNIATAaIAEAFQAbAjAaAXQAqAoA6AAQADAABfAe");
	this.shape_99.setTransform(17.6,-25.4);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f().s("#11C1EA").ss(0.1,1,1).p("AZkisIAAAAAaykpQgkA1g0AfQhfAlg5g2QgmglgZgeQgMgPgIgMIgTgjQgbAjgbAbQiBB/h+hDQgogVgjgnQgHgIgHgIIggguQgfAjgfAbQiKB2h+g/QgmgUgigjQgIgJgIgJIgfgsQgcAjgbAbQh+B5iBhBQgngUglgkQgIgIgIgJIghgtQgbAjgbAbQh+B/h8hFQgmgVghglQgIgKgJgKIgfgvQgdAmgdAdQh/B9iBhBQgqgVglgnQgHgIgHgIIgiguQgcAjgcAbQh/B2h9g/QgngUgigjQgJgJgIgJIgggsQgbAjgcAbQh+B5iDhBQgogUglgkQgIgIgIgJIgjgtQgVAkgYAaQhOBRhwgMQgugFgugVIgmgUIASDwA/ihIIAFh9AcWkpQgMgMgNgNIgkgsIgjBAQgCACgCADAf2jWQgLgBgJgBQgKgBgKgBQg9gEAAgBAfOjaQhLgHgagNQgogTgrgoAluFpIHzAGIKcgDQBgAABggBIJCADA/rCiQAGBfAdBGIZaAiA/rCiQgGhYAOhs");
	this.shape_100.setTransform(16.6,-1.3);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#4ACEF4").s().p("A/tCJQgGhYAOhsQABgSAAgTIAFh9IAfAPQAnAPAoACQCCAIBkh9IAhAlQArAqAxAVQCcBFCfifIAiAfQAsAjAxASQCfA3CfiQIAfAiQAoAlAuATQCVA+CgiTIAjAhQAuAlAyARQCgA3COiiIAUAjQAcAnApAVQCCBBDOiWIAcAgQAlAkAvASQCUA6C5iQIAdAhQAnAlAuASQCSA7CgiTIASAcQAaAhAjAWQAnAXAkALQAHACAHACIAAAAQA7ANAwgYIARgHQAVgLASgOQAVgRAPgUQALgPAIgQQAAgBAAAAQAFgMAEgNQADgMACgNIASAZIAEAFQAbAjAaAZQAqAoA7AAQACAABfAeIgeG5QAXB2jHgdQhIAAgaABQgsABglgCQgmgBgoAAIpCgDQhgAAhgABIqcACInygGI5bgiQgdhFgGhgQAGBgAdBFIZbAiI3fgEQguADg8gWQg9gXAGh3QABgRABgRIAAAAAbalCIAXAAIgXAA").cp();
	this.shape_101.setTransform(16.8,1);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#1DC2F2").s().p("AcWhgQArApAoATQAaAMBLAIQg9gFAAgBQAAABA9AFQAKABAKABQAJAAALABIgEAyQhfgegCAAQg7AAgqgmQgagZgbgjIgEgFIAjAAIgjAAIgSgZQgCANgDAMIgqAAIAqAAQgEANgFAMQAAAAAAABQgIAQgLAPQgPASgbATIgyAeIAAAAQgwAYg7gNIAAAAQgHgCgHgCQgkgLgngXQgjgUgaghIgSgcQigCRiSg7QgugQgnglIgdghQi5COiUg6QgvgQglgkIgcggQjOCUiChBQgpgTgcgnIgUgjQiOCgigg3QgygPguglIgjghQigCRiVg+QgugRgoglIgfgiQifCOifg3QgxgQgsgjIgigfQifCdichFQgxgTgrgqIghglQhkB7iCgIQgogCgngPIgfgPIgFB9QAAATgBASIgSjtIAmAUQAuAUAuAFQBwANBOhSIBgAAQAlAlAoAUQCDA/B+h4IBoAAQAiAjAnAUQB9A+B/h1IBoAAQAlAnAqAVQCBA/B/h7IBqAAQAhAlAmAVQB8BDB+h9IBnAAQAlAlAnAUQCBA/B+h4IBmAAQAiAjAmAUQB+A+CKh1IBsAAQAjAnAoAWQB+BBCBh+IBdAAQAZAeAmAlQA5A1BfgkQA0geAkg2QACgCACgDIAjg/IAkArQANAOAMALIAAAAAUmhgQAbgaAbgjIATAiQAIANAMAOIhdAAANwhgQAfgaAfgjIAgAtQAHAIAHAIIhsAAAG6hgQAbgaAcgjIAfArQAIAKAIAIIhmAAAAIhgQAbgaAbgjIAhAsQAIAJAIAIIhnAAAk5hgIhqAAQAdgcAdgmIAfAuQAJALAIAJIAAAAAtahgQAcgaAcgjIAiAtQAHAIAHAIIhoAAA0HhgQAcgaAbgjIAgArQAIAKAJAIIhoAAA61hgQAYgaAVgjIAjAsQAIAJAIAIIhgAA").cp();
	this.shape_102.setTransform(16.6,-21.5);

	this.addChild(this.shape_102,this.shape_101,this.shape_100,this.shape_99);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-187.2,-38.1,407.7,74.1);


(lib.Symbol1 = function() {
	this.initialize();

	// Layer 1
	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f().s("#B4ECFA").ss(0.1,1,1).p("A4EgTQAQgQAPgSIAhAlQAqAoAxAVQAhAPAhAEAxIgSQANgMAOgNIAhAfQAsAhAyASQAfALAgADAqKgbQANgKANgLIAeAiQAoAjAvATQAhAOAjADAjagaQAJgIAKgJIAkAhQAuAjAyARQAgALAfACADYgrQAJgKAJgKIAUAjQAcAlApAVQAiARAnACAKGgrQAGgFAHgFIAcAgQAmAiAuASQAmAPApABARIgvQAEgDAEgDIAeAhQAnAjAtASQAoAQAoABAXwgyQACgBACgCIATAcQAZAfAjAWQApAZAxAHQAQABARAAQBIABBXglA9cAHIBBAmQAfALAfAE");
	this.shape_103.setTransform(-1.4,-24.2);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f().s("#11C1EA").ss(0.1,1,1).p("AdRhlIAWi7QisBeh0hQQglgZgagoIgTgiQicDLiZhRQgwgagpgzIgggtQisDCiahOQgwgYgogxIgfgrQiZDFidhPQgwgZgsgxIghgsQicDLiUhUQgvgagpg0IgfguQicDOiehQQgygZgrgzIgigtQicDCiYhOQgwgYgqgxIgggrQiZDFifhPQgxgZgsgxIgjgsQgcAvgiAeAdQgJIAAAJQAAgBAAgDAdRhgIgBBXAcxFXIAUgYIAAAAQAIggACg4QgBgFgBgEIAChjIABh7AdPB7QACA+gCAuQAIAngSAxAcIFkQgBAAAAAAQgBAAAAABIAAAAQABgBABAAIAAAAAcGFlQACgBABAAQgBAAAAAAAcFFlIABAAIAAAAQAAgBAAAAQAAAAgBAAQAAAAAAABIAAAAAcGFlIgBAAQABAAAAAAAcCFmQACgBABAAQgBAAgBAAAcFFlIAAAAIAAAAAcGFkQABAAAAAAQAFgDAEABAcWFjQAAAAABAAQAKgDAIgDAcCFmQAAAAAAgBQgXACgegEQgkgCg1gCIpIgEQhuABhtAAQiTABiRAAIkbgBIgVAAIgFAAQgDgBgDABAhsFhI7CAZIg4ABIAAgBA9mFGIAAgFA9mjDIAAgnQBegOAuAFQBjALBIg/AcDFkQAAABgBAAQABAAAAAAAZ0FfIBIABQAJABAIACQAjABATAAQABAAABAAAcWFjQgEAAgEABQgCAAgDAAQADgBABAAQAAgBgFACAdFE/QgHAUgVAKAECFbQAIAAAIABAD9FcIAFgBA9jjCQgCgUgBgUA62FWQgKABgKgB");
	this.shape_104.setTransform(-0.4,0);

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.f("#4ACEF4").s().p("A6yjZQBmgNBThlQABAAAAgBIABAAIAeAiIADADQArAqAyAVQA+AbA/gIQBigMBihhIAbAZIAHAGQAtAjAyASQA5ATA6gFQBogKBphdIAUAVIALANQApAlAvATQA3AXA5gGQBjgJBnhdIATARIARAQQAvAlAzARQAyARAvgEQBtgIBlhwIAMAUIAJAPQAcAnAqAVQAuAWA3gDQBogGCJhiIAJAKIATAWQAnAkAvASQAvASA0gCQBvgECBhiIAGAGIAYAbQAoAlAuASQAtASAvgCQBrgCBxhmIACADIARAZQAZAhAkAWQArAaA0AFQAQACARAAQBIABBXglIgBBzIAAAEIgBBXIAAALIAAgLIAAAGQAAADAAACIgCB6IgBBjQABAEABAFQgCA4gIAgIAAAAIgUAYQgFADgEADQgIADgKADQAAAAgBAAQgDAAgDgBQgDgBgFADQgBAAAAAAQAAAAABAAQAFgDADABIgDABQAAgBgFACQAAAAAAAAQgBAAgBABIABAAQgBAAAAAAIAAAAIAAAAIAAAAIAAAAIAAAAQAAgBABAAQgBAAAAAAQAAAAABAAQgBAAAAABIAAAAIAAAAQAAgBAAAAQgCAAgBAAQgSAAgjgBQgJgCgJgBIhHgBIpJgEQhuABhtAAQiSABiRAAIkcgBQgIgBgIAAIgKABQgDgBgCABQgDAAgCAAIhlAAIAPAAIkDAFI7CAZIg4AAIhWABIgBplQAaEogHB3QgGB3A/AXQAGACAFABQAxARAogBQgmgCgugRQgDgBgCgBQg4gbAGhxQAGh3gZkoIBCAmQABAAABABQACAAACABQAlANAmACQAYACAYgEIAAAAAdME/QABAAAAAAQAHABgQAAQADgBAEAAQABAAAAAAIAAAAAc4FBQAAAAABAAIgCABQAAAAABgBIAAAAA6BEyQgJABgLgBQALABAJgBIAAAA").cp();
	this.shape_105.setTransform(-5.7,3.6);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.f("#1DC2F2").s().p("AdRCKIABhzQhXAlhIAAQgRAAgQgCQgwgHgpgZQgjgVgagfIgSgdQgCACgCACIgDgEQhxBkhqADQgpgBgngQQgugSgngjIgdghQgEADgEADIgGgGQiBBhhwAEQgogCgmgOQgvgSglgiIgcghQgHAFgHAFIgJgKQiJBghoAGQgngCghgRQgpgUgcglIgUgkQgJAKgKAKIgLgUQhlBvhsAIQgfgDgggKQgygRgugjIgjgiQgKAJgKAIIgSgRQhoBchjAJQgigEgigNQgugTgogkIgfgiQgNAMgMAKIgUgWQhpBbhpAKQgfgDgggLQgxgRgsgiIgigfQgNANgNAMIgbgZQhjBfhhANQghgFghgOQgxgWgrgnIghgmQgPATgQAQIgegjQAigeAcgvIAjAtQAsAwAxAZQCfBNCZjDIAgArQAqAxAwAZQCYBLCcjAIAiAuQArAzAyAZQCeBOCcjNIAfAvQApAzAvAbQCUBRCcjJIAhAtQAsAwAwAZQCdBNCZjDIAfArQAoAxAwAZQCaBLCsjAIAgAuQApAzAwAZQCZBPCcjJIATAjQAaAnAlAZQB0BOCshcIgWC5A4vg1QhSBihnAOQgfgEgegMIhBgmQBegLAuAFQBjAJBIg9IAAAA").cp();
	this.shape_106.setTransform(-0.4,-24);

	this.addChild(this.shape_106,this.shape_105,this.shape_104,this.shape_103);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-198.6,-37.9,387.8,76);


(lib.Symbol25 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.Symbol2_1();
	this.instance.setTransform(525.2,49,1.318,1.283,0,0,0,211.1,0);
	this.instance.alpha = 0.398;

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,537.4,95.1);


(lib.Symbol16 = function() {
	this.initialize();

	// Layer 1
	this.instance_1 = new lib.Symbol2();
	this.instance_1.setTransform(0,0,1,1,0,0,0,51.2,51.2);

	this.addChild(this.instance_1);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-51.1,-51.1,102.4,102.4);


(lib.Symbol8copy = function() {
	this.initialize();

	// Layer 1
	this.sign = new lib.Symbol22();
	this.sign.setTransform(-3.5,43,0.806,0.806);

	this.timer = new lib.Symbol20();
	this.timer.setTransform(-1.6,-16.1,0.806,0.806);

	this.shape_107 = new cjs.Shape();
	this.shape_107.graphics.f().s("#F5855D").ss(1,1,1).p("AIpIRIxRAAIAAwhIRRAAIAAQh").cp();
	this.shape_107.setTransform(-0.3,-9.9);

	this.shape_108 = new cjs.Shape();
	this.shape_108.graphics.f("#FEFCFC").s().p("AIpIRIxRAAIAAwhIRRAAIAAQh").cp();
	this.shape_108.setTransform(-0.3,-9.9);

	this.shape_109 = new cjs.Shape();
	this.shape_109.graphics.f("#CCCCCC").s().p("AKCkRIhRIjIAAojIBRAAAo5kRIAAIjIhIojIBIAA").cp();
	this.shape_109.setTransform(0,-25.8);

	this.addChild(this.shape_109,this.shape_108,this.shape_107,this.timer,this.sign);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-64.2,-62.8,128.6,125.8);


(lib.Symbol1_1 = function() {
	this.initialize();

	// Layer 1
	this.instance_2 = new lib.Symbol19();
	this.instance_2.setTransform(70.5,74.4,0.224,0.224);

	this.instance_3 = new lib.Symbol1copy();
	this.instance_3.setTransform(63.2,42.7,0.144,0.144);

	this.addChild(this.instance_3,this.instance_2);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,141,109.2);


(lib.Symbol7 = function() {
	this.initialize();

	// Layer 3
	this.shape_110 = new cjs.Shape();
	this.shape_110.graphics.f("#0099FF").s().p("AAKAIQgFAEgFAAQgEAAgFgEQgFgDAAgFQAAgEAFgEQAFgDAEAAQAFAAAFADQAFAEAAAEQAAAFgFADIAAAA").cp();
	this.shape_110.setTransform(163.1,109.5);

	// Layer 2
	this.shape_111 = new cjs.Shape();
	this.shape_111.graphics.f("#FFFFFF").s().p("AI6AAQgRgLgMAAQgMAAgIAIQgGAEgDAIIAMgBQAKAAAKADIASAKIAUAOIhsAAQgEAAgDgFQgFgGgCgUIgCg4QgCgUgEgOIgPAXIAHAKIAEAMIAHBJQABAMAFAFQAFAHAIAAICUAAIAAgVIgHAAQgFAAgOgOIgagVAE6heQgHANAAAQIAGACIAOBqQAAALgTAHQgQAHgUAAQgTAAgKgHQgLgIAAgOIACgQIANgbIgDgCIgKARIgIAVIgDAVQAAASAOAJQANAJAWgBQAUAAANgDQAPgEAIgKQAJgLAAgTIgMhiIAHACIADgXIgOgGIgEgDIgBgHIgCAAAGlAAQgLAAgGAKQgFAKgBAMQAAANAJAGQAIAFAQAAIgOASQgLALgJAFQgNAHgOAAIgNgBIgOgEIgCAEIAfAKIAQACQAVAAAPgVQAPgTAAgTIAAgOQAAgQgEgKQgEgJgKAAIAAAAAGZAYQAAgDADgCIAFgCQAFAAADADQAEAFACALQgLAAgGgDQgEgDgBgGIAAAAAhhg+IgJARIATAKIAJgRIgTgKAjQhbQgCABgDABIgDAAIgKgDQgFgDAAgCQABgCABgBIAFgBQAFAAADAEIACgEQABgCAAgBQAAgCgCgDQgCgBgCAAQgFAAgHAHQgGAGAAAEIACAFIAGAEQgMAEAAAFIAWgHIAHgEQAEgCAAgDIAAAAAjqg2IAKBrIAAAGIgBAIIADABIAHgPQADgIABgKIgMhwIgLAXAhxAHIgHASQgEAMAAAHQAAAIAGADQAGAEAIAAQAKAAAHgDQAJgDAFgHQAFgIAAgRQAAgKgOgKIgZgMIgHASIABAAAhygYIAJgRIgTgKIgJARIATAKAhwAcIADgJQADgDADgEIAMAGQACACACABQAJAGAAADQAAADgIAEQAAAAgBAAQgHAEgGAAQgFAAgEgEQgDgDAAgGIAAAAAAhgLIgHAQQAJAJADAIQAGAKAAAKQAAAKgLAOQgKANgPAJQgOAJgPAAIgfgFIgCAFIAiAMQAJADAIgBQAHAAANgIQAPgIAJgNQAMgNgBgNIANAAQAOAAAHgEQAHgDAHgIQAIAHAMAEIARAEIANAAIAAgVQAAgIgHgNIgNgVQgIADgJAEQgKAIgIAKQgFAIgGAEQgIAFgLAAIgNAAIAAgIQAAgMgFgKQgEgHgKgJIAAAAACHAiIgOgEQgIgEgEgFIAGgIIAJgFIAHALIAFAOIgBABApUABIgFgBQgFAHgDAFIgIAWQgEANAAAMQAAASAMAIQALAJAVgBQAoAAAXgNQAbgPgBgeQAAgHgGgBIgJgCIgWAAIgJgBIgCgDQAAgGAKgMQAMgJAJAAQAGAAAGADQAGADAEADIABgEIAAgHQAAgIgEgFQgEgEgIAAQgMAAgMALQgKALgHAMQgHANAAAIQAAAGAEAEQAEAEAFgBIAcAAQACAAACABQACABAAACQAAAEgNAGQgNAHgQAEQgSAGgOAAQgTAAgKgHQgJgIgBgOQAAgJAEgLQAEgMAIgMIAAAAAlLg9IgIARIATAKIAJgRIgUgKAlhAIQAKAAAJADIATAKIAUAOIhaAAIAAgIQAAgMgFgKQgFgHgKgJIgGAQQAIAJAEAIQAGAKgBAKQAAAKgKAOQgLANgOAJQgRAJgPAAIgWgDIAAAHIAXAIQAJADAJgBQAIAAAOgIQAOgIAKgNQALgNAAgNICCAAIAAgVIgHAAQgFAAgPgOIgagVQgQgLgMAAQgMAAgIAIQgGAEgDAIIAMgB").cp();
	this.shape_111.setTransform(64.6,42.3);

	// Layer 4
	this.instance_4 = new lib.Symbol10_1("synched",0);
	this.instance_4.setTransform(64.1,41.1,1.387,1.387);

	this.addChild(this.instance_4,this.shape_111,this.shape_110);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-28.7,-9,193.4,119.9);


(lib.Symbol4copy = function() {
	this.initialize();

	// Layer 2
	this.shape_112 = new cjs.Shape();
	this.shape_112.graphics.f("#0099FF").s().p("AAYhQQgKgGgOAAQgRAAgMAKQgNAKgGATQgGATAAAcQAAAxAQAVQAPARAXAAQATAAAMgKQAMgJAHgTQAFgTAAgeQAAgYgDgPQgDgPgIgKQgGgLgLgFIAAAAAAAhFQAPAAAJAOQALAPgBAoQAAAqgKAOQgJAOgPAAQgNAAgKgOQgKgOAAgqQAAgoALgQQAJgMANgBIAAAA").cp();
	this.shape_112.setTransform(192.2,163.2);

	this.shape_113 = new cjs.Shape();
	this.shape_113.graphics.f("#0099FF").s().p("AA4AiQAAgRgJgLQgIgJgQgEQAMgFAGgJQAGgJAAgLQAAgMgGgLQgGgJgMgHQgMgGgMAAQgUAAgOAMQgOALgEAWIAVADQADgPAIgIQAIgIAMAAQALAAAIAIQAHAIAAALQAAAPgKAHQgLAHgMAAIgDAAIgCAQIANgCQAOAAAKAJQAKAKgBAOQAAAPgKALQgKAKgNAAQgNAAgIgIQgJgIgEgSIgVADQACAVAPAOQAPAOAXgBQAXAAAQgPQARgQAAgWIAAAA").cp();
	this.shape_113.setTransform(179.3,163.2);

	this.result_txt = new cjs.Text("", "24px Arial", "#FF0000");
	this.result_txt.textAlign = "right";
	this.result_txt.lineHeight = 30;
	this.result_txt.lineWidth = 64;
	this.result_txt.setTransform(286.5,151);

	this.shape_114 = new cjs.Shape();
	this.shape_114.graphics.f("#3399FF").s().p("AgghAIgTgKIgIAQIASALIAJgRAAsAUQAHgDAHgIQAIAHAMAEIARAEIANAAIAAgVQAAgGgHgNIgNgXQgIADgJAGQgKAIgIAKQgFAIgGAEQgIADgLAAIgOAAQAAgOgCgKQgCgJgFgKIgJAYQAFAHADAJQACAIAAAMQAAASgTAJQgRAIgXAAQgTAAgKgHQgLgIAAgPIADgRIALgZIgFgCIgJATIgGATQgDAKAAAKQAAATAOAJQAMAIAYAAQAlAAAQgNQAOgMgBgaIAOAAQAOAAAHgEIAAAAABZgLIAFAMIgBABIgOgCQgIgEgEgFIAGgIIAJgFIAHAL").cp();
	this.shape_114.setTransform(227.9,164.5);

	// Layer 1
	this.instance_5 = new lib.Symbol26();
	this.instance_5.setTransform(245,115);
	this.instance_5.cache(-235,-116,472,234);

	this.shape_115 = new cjs.Shape();
	this.shape_115.graphics.lf(["#FEFCE7","#FFFFFF","#FEFCEA"],[0,0.553,1],74,-160.5,74,55.8).s().p("AAGAAQAAABgCADIgEACQgCgBgCgDQgBADAAgFQAAgDADgBQABgBABAAQAFADABACIAAAA").cp();
	this.shape_115.setTransform(171,167.5);

	this.shape_116 = new cjs.Shape();
	this.shape_116.graphics.lf(["#FEFCE7","#FFFFFF","#FEFCEA"],[0,0.553,1],50,-132,50,84.3).s().p("AAGAAQAAABgCADIgEACQgCgBgCgDQgBADAAgFQAAgDADgBQABgBABAAQAFADABACIAAAA").cp();
	this.shape_116.setTransform(195,139);

	this.shape_117 = new cjs.Shape();
	this.shape_117.graphics.lf(["#FEFCE7","#FFFFFF","#FEFCEA"],[0,0.553,1],64,-151.8,64,64.5).s().p("AAGAAQAAABgCADIgEACQgCgBgCgDQgBADAAgFQAAgDADgBQABgBABAAQAFADABACIAAAA").cp();
	this.shape_117.setTransform(181,158.7);

	this.shape_118 = new cjs.Shape();
	this.shape_118.graphics.lf(["#FEFCE7","#FFFFFF","#FEFCEA"],[0,0.553,1],41.5,-124.5,41.5,91.8).s().p("AAGAAQAAABgCADIgEACQgCgBgCgDQgBADAAgFQAAgDADgBQABgBABAAQAFADABACIAAAA").cp();
	this.shape_118.setTransform(203.5,131.5);

	// Layer 3
	this.shape_119 = new cjs.Shape();
	this.shape_119.graphics.f("#CCCCCC").s().p("EAkugKEICMAAIiMUJIAA0JEgktgKEIAAUJIiM0JICMAA").cp();
	this.shape_119.setTransform(243.4,89.5,0.99,1);

	this.addChild(this.shape_119,this.shape_118,this.shape_117,this.shape_116,this.shape_115,this.instance_5,this.shape_114,this.result_txt,this.shape_113,this.shape_112);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-3.1,0,493.2,230);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;