(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// stage content:
(lib._7rofNa2sa = function() {
	this.initialize();

	// Layer 5
	this.again = new lib.Symbol13();
	this.again.setTransform(280.5,649.5,1,1,0,0,0,75,17.4);
	this.again.alpha = 0;

	// Layer 2
	this.good = new lib.Symbol14();
	this.good.setTransform(274.5,608.4,1,1,0,0,0,132,17.4);
	this.good.alpha = 0;

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("rgba(23,28,33,0.008)").ss(0.1,1,1).p("A0/lTMAp/AAAIAAKnMgp/AAAIAAqn").cp();
	this.shape.setTransform(213.5,752);

	// Layer 7
	this.q = new lib.Symbol12();
	this.q.setTransform(280,632,1,1,0,0,0,219.5,32.8);

	// Layer 3
	this.ans8 = new lib.Symbol11();
	this.ans8.setTransform(274.4,515.6,1,1,0,0,0,16.2,22.8);

	this.ans7 = new lib.Symbol10();
	this.ans7.setTransform(350.4,515.2,1,1,0,0,0,16.6,22.8);

	this.ans6 = new lib.Symbol9();
	this.ans6.setTransform(280.8,341.3,1,1,0,0,0,36.5,22.8);

	this.ans5 = new lib.Symbol7();
	this.ans5.setTransform(354.9,341.8,1,1,0,0,0,16.3,22.8);

	this.ans4 = new lib.Symbol6();
	this.ans4.setTransform(420.2,166.6,1,1,0,0,0,17.2,24.2);

	this.ans3 = new lib.Symbol4();
	this.ans3.setTransform(426.6,516.1,1,1,0,0,0,11,22.8);

	this.ans2 = new lib.Symbol3();
	this.ans2.setTransform(428.9,342.3,1,1,0,0,0,16.7,22.8);

	this.ans1 = new lib.Symbol2();
	this.ans1.setTransform(346.2,166.6,1,1,0,0,0,12.1,24.2);

	// Layer 4
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#11C1EA").ss(0.1,1,1).p("AgCAAIAFAA");
	this.shape_1.setTransform(260.2,277.1);

	this.addChild(this.shape_1,this.ans1,this.ans2,this.ans3,this.ans4,this.ans5,this.ans6,this.ans7,this.ans8,this.q,this.shape,this.good,this.again);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(63.2,146,428.3,640);


// symbols:
(lib.Symbol14 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0099FF").s().p("ASQioQgJAJABAFIADAGIAHAFQgPAGgBAHIAegKIAKgFQAGgDgBgEIgGACIgFAAQgGAAgHgEQgHgEAAgCQAAgCADgCIAHgBQAGAAAFAEIADgFIABgEIgDgGIgFgCQgIAAgJAKIAAAAASMhmIAOCVQAAAEAAAEIgBALIADABIAKgUQAFgMAAgNIgQiaIgPAeAR5AjIgJAAQgHgCgUgRIgkgdQgWgQgRAAQgRAAgLAKQgHAIgFALIARAAQANAAANACQAMAEAOAJIAcAUIh9AAIAAgLQAAgSgEgJIgJgRIgKARIAIAJQAGAKAAAJQAAAEgDADQgCACgFAAQgJAAgFgGQgHgGgEgTIgDgNIgHAKIACAIIAAAKQAAAJgGAEQgGAEgMAAIgLAAQgKAAgIgIQgGgFgFgMIgHgUIgHAKIACASQAAALgJADQgGADgNAAIgTAAIAAgMQAAgagEgNQgDgIgMgOIgMAaQAMAMADAGQAEAKAAATIhJAAIAAgQQAAghgLgSIgJgLIgMAbQAKAHAFAKQAEAMAAARIAAAFIiIAAQgcAAgSgKQgTgKgBgRQAAgJAFgMIAHgOIgFgDIgLAVQgHAQAAANQAAAcAXAOQATALAeAAIDvAAIAAgBIAogBQAHgCAHgGIAOAHIARADIAKAAQAPAAAIgDQAGgCAHgGQAHAFAHADQAHADAKAAIDAAAIAAgcALwhiIgMAYIAaANIAMgXIgagOAJ2hSIgagNIgMAXIAaAOIAMgYAIrg5IAaANIAMgXIgagOIgMAYAFABNIAAAhIAiAAIAAghIgiAAACMBNIAAAhIAiAAIAAghIgiAAADmBNIAAAhIAiAAIAAghIgiAAAgCANIAEASIgBACIgSgGQgLgFgGgGIAJgMQAFgEAIgBIAKAOAgcgMQgOALgKAMQgHALgJAFQgLAIgPAAIgSAAQgHgCgUgRIgkgdQgWgQgRAAQgRAAgLAKQgHAIgFALIARAAQANAAANACQAMAEAOAJIAcAUIi/AAQAWgLAEgFQAHgJAAgMQAAgKgEgJQgDgJgFAAQgKAAgLAMQgJALgJAOIgMAcIgbAAQAAgXgFgMQgGgPgOAAQgOAAgJAPQgHAOAAAQQAAASAMAIQAKAHAWAAIgTAZQgOAPgOAHQgRAKgUAAIglgHIgCAGIAqANIAWADQAcAAAWgdQARgWADgVIAWAAIAAALQAAAbATAPQAQAOATAAQALAAAEgKQAFgHgBgMQAAgOgJgLQgHgIgKgFIDyAAQATAAAKgFQAKgEAJgMQAMALAPAFQAOAFAJAAIARAAIAAgcQAAgLgJgTIgQgdQgLADgNAJIAAAAAmiAjIAAABQgNgBgHgEQgHgDAAgJQAAgEADgDQAEgDAEAAQAGAAAEAFQAGAGADAPIgDAAAlWAVQgLAGgOAFIANgZQAKgNAHAAQAHAAgBAOQAAAHgLAGIAAAAAl1A9QAPADAPAKQATALAAANQAAADgDACIgHABQgVAAgKgNQgIgMAAgSIAAAAAjFB4IAMgWIgZgOIgNAXIAaANApWgnQAYAIAJAVQAJAQAAAdIg/AAQgGAAgEgDQgFgDgCgGIgEAAIgCALIgBALQAAAHAIAFQAHAGAJAAIBIAAIAAgcQAAglgJgYQgLgegcgOIgDAfArrAYQAAgRgHgMQgGgMgNgNIgJAaQAKAJAGAMQAIAOAAAMQAAAPgPATQgOATgUALQgXANgUAAIgrgGIgDAGIAuAQQAOADALAAQAMAAASgLQAUgMANgQQAPgUAAgRIAAgnAu6hmIAOCVQAAAEgBAEIgBALIADABIALgUQAEgMAAgNIgPiaIgPAeAvxhtQgHAAgKAKQgIAJAAAFQAAAEADADIAIAFQgRAGABAHIAegKIAKgFQAEgDABgEQgEABgDABIgFAAQgFAAgIgEQgHgEAAgDQABgCACgBIAHgBQAGAAAFAEIADgFIABgFIgCgFIgGgDAxUgYQgJgGgOAAQgVAAgJAPQgEAGgDAQIADAAQAEgGAEAAIAGACQADADACAGIgYAXQgNAQgHAOQgIATgBAWQAAAhAXASQASAPAfAFQARADAegBIAhgZIgBgCIg0gCQgkgDgVgMQgbgPAAgbQAAgMAJgNQAHgLANgKIAVgQQAJARANAHQAOAIAYAAIBhAAIAAgoQAAgagEgNQgDgIgMgOIgMAaQAMAMADAGQAEAKAAATIhVAAQgMAAgIgFQgIgEgKgLIAJgHQAGgGABgGQAAgMgMgIIAAAA").cp();
	this.shape.setTransform(131.9,15);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(11.9,-2.9,240,36);


(lib.Symbol13 = function() {
	this.initialize();

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#990000").s().p("AFJiDQAAADADADIAIAFQgQAGgBAHIAegKIAKgFQAGgDgBgEIgFACIgFAAQgGAAgHgEQgIgEAAgCQAAgCADgCIAIgBQAFAAAFAEIADgFIABgEIgCgGIgGgCQgHAAgJAKQgKAJABAFIAAAAAJRhPIAPCVQAAAEgBAEIgBALIADABIAKgUQAFgMAAgNIgQiaIgPAeAIuA6IhDAAQAAgngJgWQgMgegbgOIgDAfQAXAIAKATQAJASAAAdIg/AAQgGAAgFgDQgFgDgBgGIgEAAIgDALIAAALQAAAHAIAFQAHAGAJAAICYAAIAAgoQAAgcgFgNQgDgGgLgOIgNAYQAMANADAHQAEAKAAATIAAAAAIeCUIAMgXIgbgOIgMAXIAbAOAFNhPIAPCVQAAAEgBAEIgBALIADABIALgUQAEgMAAgNIgQiaIgPAeACBAyQgLAIgPAAIgKAAQAAgXgDgNQgDgOgJgLIgNAfQAHAJAFANQABAEABAEIAAAcIACAAQgDAUgaAMQgWALgeAAQgaAAgOgKQgOgLgBgUQAAgLAEgNQAEgOALgXIgHgDIgMAbIgJAdQgDANAAAPQAAAZASAMQASAMAfgBQAyAAAWgSQAWgQgBgkIAKAAQATAAAKgFQAKgEAJgMQAMALAPAFQAOAFALAAIARAAIAAgcQAAgLgJgTIgSgdQgLABgMAJQgPALgKAOQgHALgJAFIAAAAAC5AUIAKAQIAHASIgCACIgUgGQgKgFgHgGIAJgMQAFgFAIgCIAAAAAAHgxIgJAWIAYAOIALgXIgagNAk7AWIARgBQANAAANAEQAMAEAOAJIAcAUIh4AAQAAgngJgWQgLgegcgOIgDAfQAYAIAJATQAJASAAAdIg/AAQgGAAgEgDQgFgDgCgGIgEAAIgCALIgBALQAAAHAIAFQAHAGAJAAID2AAIAAgcIgJAAQgHgCgUgRIgkgfQgWgOgRAAQgRAAgLAIQgHAIgFAMIAAAAAkCCPIAMgWIgZgOIgNAXIAaANAnEAFQgDgGgMgOIgMAYQAMANADAHQAEAKAAATIhDAAQAAgngKgWQgLgegcgOIgCAfQAXAIAKATQAIASAAAdIg+AAQgHAAgEgDQgFgDgBgGIgEAAIgDALIAAALQAAAHAHAFQAIAGAJAAICXAAIAAgoQAAgcgEgNIAAAAAnbBoIgMAXIAaAOIAMgXIgagOAnyCbIAMgWIgagOIgMAXIAaAN").cp();
	this.shape_1.setTransform(75,12.7);

	// Layer 2
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("rgba(23,28,33,0.008)").ss(0.1,1,1).p("ARbjMIAAFdIAAA8Mgi0AAAIAAg8IAAld");
	this.shape_2.setTransform(73.7,21.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(153,0,0,0.008)").s().p("ARbDNMgi0AAAIAAldIAAg8MAi0AAAIAAA8IAAFd").cp();
	this.shape_3.setTransform(73.7,15.5);

	this.addChild(this.shape_3,this.shape_2,this.shape_1);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-37.7,-5,223,47);


(lib.Symbol12 = function() {
	this.initialize();

	// Layer 1
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0099FF").s().p("AGckqIAFgBIAIADIACgDQAAgCAAgBQAAgCgCgCQgCgCgBAAQgFAAgHAHQgGAGAAAEIADAEQADADACABQgMAEAAAFIAdgKIADgFQgCAAgCABIgEAAIgJgDQgDgCgCgCQAAgCACgBIAAAAEAhMgCtIAEAMIgBACIgOgEIgLgIIAGgIIAJgFIAHALEAgpgCuQgFAHgGAEQgIAFgKAAIgJAAQAAgPgCgKQgCgJgGgKIgJAYQAFAGADAJQADAIAAAIQAAADAAACIAAABQgBAQgTAJQgQAIgWAAQgSAAgKgIQgKgGAAgPQAAgHADgKQACgJAIgQIgEgCIgPAmIgDAUQAAASANAIQAMAHAXABQAjAAAQgNQAPgLgBgZIAJAAQANAAAHgDQAHgEAGgIQAJAIAKADQAKADAHABIAMAAIAAgUQAAgIgGgNIgMgVQgIACgJAGQgKAIgHAKIAAAAAfAjaIARAKIAJgRIgSgJIgIAQEAgaABHQgFAAgEAGQgFAFAAAIIADAGIAFAFIgLAKIgOAJIAIAAQAGAAAIgIIAIgIIAJAFQAAgBABgDQAAgBAAgDQAAgBgBgCIgEgDIADgJIABgEIgDgIQgCgDgDAAIAAAAAeyCvQgIgFABgDQAAgCALgGIAugQIAAgTIggAMQgVAIgJAKQgJAMgBATQAAADAHAGIAOAKIADgEIAcATQAKAJAIAMIhNAAQAAgIgGgNIgMgVQgIACgJAGQgKAIgHAKQgFAHgGAEQgIAFgKAAIgOAAIgLhbIAHACIADgVIgNgGIgEgDIgCgHIgCAAQgGANAAAPIAFACIAOBoQAAAKgRAHQgRAHgTgBQgSAAgKgHQgJgGgBgOIADgPIAMgcIgEgCIgJASIgHAUIgDAUQAAARANAJQAMAIAWAAQATAAAMgDQAPgFAHgJQAFgGACgIIAPAAQANAAAHgDQAHgEAGgIQAJAIAKADQAKADAHABIDRAAIAAgWIgOhYIAGABIACgJIABgMIgMgFQgGgDgBgGIgCgCIgEANIgBAPIAGADIANBfIgoAAIAAgIQAAgUgDgIIgKgQIgJASIALAOQADAHAAANIgvAAQgIgQgOgPQgNgOgRgNIgJgHEAgbABZIgBADIgFgEIgDgFQAAgBABgBQABgBAAAAIAFADIACAGAf5CVIgIARIASAJIAJgQIgTgKEAgdAClIAJgQIgTgKIgIAQIASAKAd9DWIAHALIAEAMIgBACIgOgEIgLgIIAGgIIAJgFActj+IAKBoQAAADgBADIAAAIIACABIAHgPQADgIAAgJIgKhtIgLAWAcDkaIgCgCIgEANIgBAPIAFADIAOBfIggAAIAAgJQAAgPgHgIQgIgJgPAAQgKAAgIADIgRAIIgTAOQgLAHgNAFQgMAEgKAAQgKAAgHgJQgHgIgEgPIgFAGIACAOQAAAIgHACQgDADgKgBIgOAAQAAgQgDgJQgFgLgKAAQgJAAgGALQgGALAAALQAAANAJAFQAHAFAPAAIgNARQgKAKgJAFQgNAIgNgBIgagEIgCAEIAeAJIAPACQAUAAAPgUQALgPACgQIAegBIAKgFIAKAFIALACICyAAIAAgWIgNhYIAFABIACgJIABgMIgLgFQgHgDAAgGIAAAAAbWivQAHADAAAFQAAAFgGACQgGACgMAAIgzAAIAZgNQAQgHALAAQAJAAAHADIAAAAAYXiwQAFAAADAEQAEAEACALQgLAAgFgDQgFgDAAgGQAAgDACgCIAFgCAXLimQAAgMgFgJQgDgIgKgJIgHARQAJAJADAHQAGAKgBAJQAAALgKAMQgJANgPAJQgPAIgPAAIgegEIgCAEIAhAMIARACQAIAAANgIQAOgIAJgMQAKgNAAgMIAAgcAYHClIAGBIQADALADAFQAFAHAIAAIAWAAQANAAAHgDQAHgEAGgIQAJAIAKADIARAEIAMAAIAAgUQAAgIgGgNIgMgVQgIACgJAGQgKAIgHAKQgFAHgGAEQgIAFgKAAIgWAAQgEAAgDgFQgEgFgCgUIgCg4QgCgSgFgOIgNAWQAEAEACAFIAEAMAT+j+IAJBoQAAADAAADIgBAIIACABIAIgPQADgIAAgJIgLhtIgKAWATNkPIgBAPIAGADIANBfIgoAAIAAgIQAAgUgDgIIgKgQIgJASIALAOQADAHAAANIg5AAQgDAAgCgEQgEgGgCgOIgNhcIgIATIAEATIACAVQAAAWgPARQgNAOgYAKQgPAHgeAJIAAADQAmAAAPgDQASgFAKgNQAJgKAKgfQABACAAACQAAACAAADQAAAZAHAMQAGALAJAAIB1AAIAAgWIgOhYIAGABIACgJIABgMIgMgFQgGgDgBgGIgCgCIgEANASkkDIgIAQIASAKIAJgQIgTgKASgkNIgSgKIgIAQIASAKIAIgQASCjoIASAJIAJgQIgTgKIgIARAROjBQABgDAAgBQAAgRgQgTQgOgQgTgLQgRgKgIAAQgEAAgBAHQAAAKAHAJQAFAGAIAFIAKAEIAEgDQABgDACAAQAIAAAOARQAMAPAGAOIABgEASEDCQgGAAgIAIQgGAHgGAMIgJATIghAAQgEAAgDgFQgEgFgCgUIgCg4QgCgSgFgOIgNAWIAGAJIAEAMIAGBIQADALADAFQAFAHAIAAIAdAAIAAAIQAAASAOALQALAKANgBQAIAAADgGQADgFAAgJQAAgJgHgIQgFgGgHgDICTAAIAAgcQAAgUgDgIIgKgQIgJASIAKAOQADAHAAANIgyAAIAAgCIgNhYIAFABIACgJIABgMIgLgFQgHgDAAgGIgCgCIgEANIgBAPIAFADIAOBfIhVAAQAPgHADgEQAFgGAAgKQAAgHgDgGQgCgGgEAAIAAAAAVOCTIAOAJIAIgPIgNgJIgJAPAUkB6IgNAWIAGAJIAEAMIAGBIQADALADAFQAFAHAIAAICBAAIAAgcQAAgUgDgIIgKgQIgJASIAKAOQADAHAAANIgvAAIAAgTQAAgQgFgLQgGgPgLAAQgKAAgHAMQgGAKAAAMQAAANANAGIAZAFIgLADIgoAAQgFAAgFAAIgFAAQgEAAgDgFQgEgFgCgUIgCg4QgCgSgFgOIAAAAAV+CGIgOgJIgJAPIAOAKIAJgQAVhDPIACgGQADgDADABQAHAAAEAIIAFANIgPgCQgIgDgBgIIAAAAAWGErIASAJIAIgQIgSgJIgIAQAWxEqIAJgQIgSgJIgJAQIASAJAUFEfIgSgKIgJAQIASAKIAJgQASCDdQAAAFgIAFQgHAEgKADIAJgRQAHgLAEAAQAFAAAAALIAAAAASAEhQgOAAgIgKQgGgIAAgMQALABAKAHQAOAJgBAIIgCADQgCACgCAAIAAAAAZ2DhIAEAMIgBACIgOgEIgLgIIAGgIIAJgFIAHALAPvj5IgTgKIgIAQIASAKIAJgQAPYkNIgSgKIgIAQIASAKIAIgQAPijSIgJASIALAOQADAHAAANIhEAAQgDAAgEgMIgNhFIgGAHIgDAJIACAJQgTAJgMAMQgNAMAAAJQAAADAJACIAVABQAGAAAFgDQAFgDAEgHQACARAFAKQAHANAHABIBMAAIAAgcQAAgUgDgIIgKgQAPVjvIgTgKIgIARIASAJIAJgQANrkQIgJAQIASAKIAJgRIgSgJAOEkaIgIAQIASAKIAJgRIgTgJANxi4QAEgGAGgEIAPgHIACAMQgGAIgHgBIgIAAIgGgCALTkcIgEANIgBAPIAGADIANBfIgoAAIAAgIQAAgUgDgIIgKgQIgJASIALAOQADAHAAANIhIAAQgKAAgIADQgLADgHAHQgIAJgBAOQAAAEADACQADABAIABIASABQACAAADABQACABAAABQAAAGgPACQgMADgRAAQgXAAgOgHQgOgGgBgPQAAgHAHgNIAIgOIgEgDIgOAXQgHAPAAANQAAAPAPAJQAPAJAYgBQAiAAAPgKQAPgKgBgUQAAgEgDgCQgEgBgDgBIgUgBQgKAAAAgEQAAgDAJgBICeAAIAAgWIgOhYIAGABIACgJIABgMIgMgFQgGgDgBgGIgCgCAKmkDIgIAQIASAKIAJgQIgTgKAMJiQIgBAIIACABIAIgPQADgIAAgJIgLhtIgKAWIAJBoQAAADAAADIAAAAAKnCIQgWAIgJAKQgJAMAAATQAAADAHAGIANAKIAEgEIAbATQAKAJAIAMIhQAAIAAgCIgNhYIAFABIACgJIABgMIgLgFQgHgDAAgGIgCgCIgEANIgBAPIAFADIAOBfIgkAAQAAgIgGgNIgMgVQgIACgJAGQgKAIgHAKQgFAHgGAEQgIAFgKAAIgWAAQgDAAgEgFQgDgFgDgUIgCg4QgCgSgEgOIgOAWIAHAJIADAMIAHBIQACALADAFQAFAHAIAAIAWAAQANAAAHgDQAHgEAGgIQAJAIAKADQAKADAHABICYAAIAAgUQgIgQgOgPQgMgOgSgNIgJgHQgHgFAAgDQAAgCALgGIAugQIAAgTIgfAMANKCkIgIAQIARAKIAJgRIgSgJAKEjoIASAJIAJgQIgTgKIgIARAIfhBIANAIIALgKIgNgJIgLALAJBhMIgKALIAMAIIALgKIgNgJAF1jIQgHACgJAGQgLAIgGAKQgFAHgGAEQgIAFgLAAIgWAAQgDAAgEgFQgDgFgDgUIgCg4QgCgSgEgOIgOAWIAHAJIADAMIAHBIQACALAEAFQAEAHAIAAIAXAAQANAAAGgDQAIgEAGgIQAIAIALADIARAEIAMAAIAAgUQAAgIgHgNIgMgVAF2itIAFAMIgBACIgOgEIgMgIIAGgIIAJgFIAHALAGYj+IAJBoQAAADAAADIgBAIIACABIAHgPQAEgIAAgJIgLhtIgKAWAFTCvIASAJIAJgQIgSgKIgJARAEvC8IgDgCIgIAPQgFALAAALQAAATAQAKQANAIAVAAIBsAAIAAgfQAAgYgIgNQgDgDgEgEIgIASQAIAGADAIQACAHAAANIAAADIheAAQgUAAgMgGQgOgIAAgNIADgOIAFgLAFtCkIASAKIAJgQIgTgKIgIAQAI3DvIgOgEIgLgIIAGgIIAJgFIAHALIAEAMIgBACAPZDbIgMgVQgIACgJAGQgKAIgHAKQgFAHgGAEQgIAFgKAAIgJAAQAAgPgCgKQgCgJgGgKIgJAYQAFAGADAJQADAIAAAIQAAADAAACIAAABQgBAQgTAJQgQAIgWAAQgSAAgKgIQgKgGAAgPQAAgHADgKQACgJAIgQIgEgCIgPAmIgDAUQAAASANAIQAMAHAXABQAjAAAQgNQAPgLgBgZIAJAAQANAAAHgDQAHgEAGgIQAJAIAKADQAKADAHABIAMAAIAAgUQAAgIgGgNIAAAAAPRDvIgOgEIgLgIIAGgIIAJgFIAHALIAEAMIgBACADqitIAFAMIgBACIgOgEIgMgIIAGgIIAJgFIAHALADIiuQgFAHgGAEQgIAFgLAAIgLAAIAAgCIgNhYIAFABIADgKIABgLIgMgFQgIgDAAgGIgCgCIgEANIgBAPIAGADIAOBfIhIAAQgSAAgKgEQgNgEAAgNIABgJIAFgNIgDgDIgHANQgFANAAAKQAAAQAMAHQAMAGAaABIBfAAQANAAAGgDQAIgEAGgIQAIAIALADQAKADAHABIAMAAIAAgUQAAgIgHgNIgMgVQgHACgJAGQgLAIgGAKIAAAAABxj8QgLAEgKANQgJANgBAJQAAAEACABIAFACIAIgBQACAAACAAQACAAADACIACAEQAAAFgJAEQgKAEgNgBIgRgBIgCADIAPAEIAPACQAPAAAIgHQAIgHAAgMQAAgIgCgDQgCgDgGAAIgGABIgEAAQgCAAgCgBQgCgBAAgBQAAgFAHgFIAMgEIACgPAhGj+IAJBoQAAADAAADIgBAIIACABIAIgPQADgIAAgJIgLhtIgKAWAhsivQAIADgBAFQAAAFgFACQgGACgMAAIg0AAIAZgNQAQgHAMAAQAJAAAGADIAAAAAiDjEIgQAIIgUAOQgKAHgOAFQgMAEgKAAQgJAAgIgJQgGgIgFgPIgEAGIABAOQAAAIgGACQgEADgJgBIgeAAIgIgCQgFgBgCgDIALgLQAEgFAAgFQAAgJgLgEQgHgEgNAAQgPAAgGAFQgGAEAAAMIAAAHIACAAQABgCACgBQADgBABAAQAFAAADAEIAFAHIgSAHIgQACIAAgJQAAgPgHgIQgIgJgPAAQgMAAgQAIIgZAOIADgcIgCgYIgHgbIAGACIACgIIACgPIgOgDQgGgDgCgFIgEAMIgDANIAHAEIAKArIACAaIgBALIgDALIgRAIIgfACIAAAUICNAAQAOgBALgEQAKgDAHgHQAEAHAJAEQAIADAHABIARAAIAAgBIAcgBIAJgFIAKAFIAMACICHAAIAAgdQAAgPgIgIQgHgJgQAAQgJAAgJADIAAAAAi1jhIATAKIAIgRIgSgJIgJAQAlVjsIASAJIAIgQIgSgKIgIARAmUiyQAMAAAFADQAGADAAAFQAAAJgaAAIgxAAIAPgJIASgIQALgDAIAAIAAAAAprjEIANABIAOADIACgCIgNgNQgJgHgOAAQgRAAgMAJQgKAJAAANIACANIAFAMIgWAAIAAgCIgNhYIAGABIACgJIAAgMIgLgFQgGgDgBgGIgCgCIgEANIgBAPIAFADIAOBfIg8AAQgKAAgJADQgKADgHAHQgIAJgBAOQAAAEADACQADABAIABIARABQADAAADABQACABAAABQAAAGgPACQgNADgQAAQgXAAgOgHQgOgGgBgPQAAgHAHgNIAIgOIgEgDIgOAXQgHAPAAANQAAAPAPAJQAPAJAXgBQAjAAAPgKQAPgKgBgUQAAgEgEgCQgDgBgDgBIgUgBQgKAAAAgEQAAgDAJgBIB4AAQATAAAWgFQAXgDAQgHIAIgUIg/AOQgIgFgGgHQgGgHAAgFQAAgGAJgDQAIgEAQAAIAAAAAu3iQIgBAIIACABIAIgPQADgIAAgJIgLhtIgKAWIAJBoQAAADAAADIAAAAAvekBIgOgHQgFgDAAgEIgDgBIgDALIgCANIAHAEQAAAVgDANQgDAQgHAPIgKgTIgdgrIgRgUQgJgJgEAAQgEAAgBAGIgBALIACAIIAFAJIAKAKQAFAGADgBQACAAAAgBQADgBACAAQAEABACADIAHAHIAYAqQgMARgUAKIgDAQIAAADIA0gFIABgHIAAgHIgCgPIgGgMQAJgPAEgQQAEgOAAgPIAAgKIAGADIAGgUAxSieIgGAAQgFgBgOgMIgZgWQgPgLgMAAQgLAAgIAIQgFAEgEAJIAMgBIASADIASAJIAUAOIhYAAIAAgIQAAgUgDgIIgKgQIgJASIALAOQADAHAAANIg0AAIAAgIQAAgUgDgIIgKgQIgJASIALAOQADAHAAANIg9AAQgEAAgDgFQgEgFgCgUIgCg4QgCgSgEgOIgOAWIAGAJIAEAMIAGBIQADALAEAFQAEAHAIAAID+AAIAAgUAv8iUQAAAEgJABIgTABIANgKIAKgKIAEAJIABAFAyZj9IgJARIATAJIAIgQIgSgKAzPj5IgTgKIgIAQIARAKIAKgQA0EjoIASAJIAJgQIgTgKIgIARA0nhtIASAJIAKgQIgTgJIgJAQA0lhqIgTgJIgIAQIASAJIAJgQA2GjMIgGARQAJAJADAHQAGAKgBAJQAAALgKAMQgJANgPAJQgPAIgPAAIgegEIgCAEIAhAMIARACQAIAAAMgIQAPgIAIgMQALgNAAgMIAAgcQAAgMgFgJQgEgIgKgJIAAAAA5Bj+IAKBoQAAADAAADIgBAIIACABIAIgPQADgIAAgJIgLhtIgLAWA5rkaIgCgCIgEANIgBAPIAGADIANBfIgjAAQAAgIgGgNIgMgVQgIACgJAGQgKAIgHAKQgFAHgGAEQgIAFgKAAIgOAAIAAgIQAAgUgDgIIgKgQIgIASIAKAOQADAHAAANIg8AAQgEAAgDgFQgEgFgCgUIgCg4QgCgSgFgOIgOAWIAHAJIADAMIAHBIQACALAEAFQAFAHAIAAIBSAAQANAAAHgDQAHgEAGgIQAIAIALADIARAEIA7AAIAAgWIgOhYIAGABIABgJIACgMIgMgFQgGgDgBgGIAAAAA6UitIAFAMIgBACIgOgEIgMgIIAHgIIAIgFIAHALA8EjrIASAJIAJgQIgTgKIgIARA+ji4IACAIIAAAGQAAAIgHACQgDADgKgBIgJAAIAAgLQAAgYgJgNQgCgDgDgEIgJASQAIAGACAIQAEAHAAANIAAADIhgAAQgTAAgMgGQgOgIAAgNIADgOIAFgLIgEgCIgIAPQgEALAAALQAAATAQAKQANAIAVAAIBsAAIAAgBIAYgBIAKgFIAJAEIAMADIAHAAIAPgCIAKgGIAJAGIANACIAIAAIAAgbQAAgNgCgIIgGgMIgIANIAGAHQAEAHAAAGIgBAFQgCACgDAAQgGAAgEgFQgFgEgDgNIgCgKIgFAGIABAOQAAAGgEADQgDADgJAAIgIAAQgHAAgFgFQgEgEgEgIIgGgPIgEAGEggagBpIASAKIAJgQIgTgKIgIAQ").cp();
	this.shape_4.setTransform(216.8,29.4);

	this.addChild(this.shape_4);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(2.7,-1.4,428.3,61.9);


(lib.Symbol11 = function() {
	this.initialize();

	// Layer 1
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#CC3366").s().p("AB5hSQgIgIgOgBQgXAAgWAXQgSASgOAbQgMAXAAAPQAAALAIAGQAHAIAJAAIAzAAIAJAAQADACgBAEQAAAGgXANQgXAMgfAJQggAKgbAAQghAAgTgNQgTgNAAgbQAAgRAHgVIAVgsIgIgEIgOAbQgLASgFATQgIAZAAAYQAAAgAXAQQAUAPAnABQBJAAAsgbQAwgcAAg3QAAgOgLgCIg6gDQgMAAgFgCQgEgCAAgCQAAgMATgUQAVgWATAAQALAAAKAFQALAGAIAKIACgKIABgPQAAgOgJgJIAAAAAhnh3QgMAMAAAHQAAAFAFAEIAKAHQgVAHgBAKIApgOIAOgGQAHgEAAgGIgJAEIgHAAQgHAAgKgGQgLgFABgEQAAgDAEgBIAKgDQAIAAAGAHIAEgHIABgHQAAgFgDgCQgDgEgEAAQgKAAgNAOIAAAA").cp();
	this.shape_5.setTransform(15.8,22.9);

	// Layer 2
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(102,255,0,0.008)").s("rgba(23,28,33,0.008)").ss(0.1,1,1).p("AFAkNIAAIbIp/AAIAAobIJ/AA").cp();
	this.shape_6.setTransform(17.8,25.2);

	this.addChild(this.shape_6,this.shape_5);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-14.2,-1.8,64,54);


(lib.Symbol10 = function() {
	this.initialize();

	// Layer 1
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#CC3366").s().p("ABBBPIAAgPQAAgngGgRQgDgJgQgUIgSAiQARARAEAKQAGANAAAaIjKAAIAAAmIEzAAIAAgmIhZAAAAAhmQgLAMAAAGQAAAGAFADIAIAHQgTAIgBAKIAngOIAOgGQAHgFAAgFIgJADIgHAAQgHAAgKgGQgJgGAAgDQAAgDADgBQAFgCAFAAQAIAAAGAGIAEgHIACgGQAAgFgDgDQgEgDgEAAQgKAAgMAOIAAAA").cp();
	this.shape_7.setTransform(15.7,16.2);

	// Layer 2
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("rgba(102,255,0,0.008)").s("rgba(23,28,33,0.008)").ss(0.1,1,1).p("AEJjRIAAGjIoRAAIAAmjIIRAA").cp();
	this.shape_8.setTransform(17.7,20.6);

	this.addChild(this.shape_8,this.shape_7);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-8.8,-0.3,53,42);


(lib.Symbol9 = function() {
	this.initialize();

	// Layer 1
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#CC3366").s().p("ABohVQgFgLgPgUIgRAkQAQARAEAKQAHANgBAaIjKAAIAAAlIDbAAIAAg0QAAgngGgRIAAAAABIAwIgQAfIAjASIARgfIgkgSAAqB1IAQgfIgkgTIgQAgIAkAS").cp();
	this.shape_9.setTransform(35.9,25.7);

	// Layer 2
	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("rgba(102,255,0,0.008)").s("rgba(23,28,33,0.008)").ss(0.1,1,1).p("AETDMIolAAIAAmXIIlAAIAAGX").cp();
	this.shape_10.setTransform(32.2,24);

	this.addChild(this.shape_10,this.shape_9);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(4.7,3.5,55,41);


(lib.Symbol7 = function() {
	this.initialize();

	// Layer 1
	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#CC3366").s().p("AB6iLQgJgJgOAAQgWAAgXAWQgSASgOAbQgMAaAAAOQAAAMAHAFQAIAIAJAAIA0AAIAIABQADABAAAFQAAAFgYALQgYAMgdAKQgiAKgaAAQgiAAgSgNQgTgOAAgYQAAgRAHgVQAIgVANgZIgJgEIgOAaQgJAVgHATQgHAZAAAVQAAAhAWAQQAVAPAnAAQBKAAAsgaQAvgcABg1QAAgPgMgCIg6gCQgMAAgFgCQgEgCgBgFQAAgMAUgUQAVgVATgBQAMAAAKAGQAKAGAIAJIACgKIABgOQAAgPgIgIIAAAAAAeCCIARggIgjgSIgPAfIAhATAgkBkIgRAfIAjATIARggIgjgS").cp();
	this.shape_11.setTransform(15.9,28.7);

	// Layer 2
	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("rgba(102,255,0,0.008)").s("rgba(23,28,33,0.008)").ss(0.1,1,1).p("ADXDDImtAAIAAmFIGtAAIAAGF").cp();
	this.shape_12.setTransform(17.9,29.5);

	this.addChild(this.shape_12,this.shape_11);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-3.6,10,43,39);


(lib.Symbol6 = function() {
	this.initialize();

	// Layer 1
	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#CC3366").s().p("AAUg/QAJAIAEAWIgCAAIAAAAQgVAAgKgFQgIgGgBgLQAAgIAFgEQAEgDAFgBQAKAAAFAIIAAAAAgUhUQgLAUAAAYQAAAaASALQAOAIAfABIgcAjQgSAVgUALQgZAPgdAAQgLAAgOgEIgbgGIgFAIIA+ATQAQAEAPAAQAqAAAdgqQAXgfAEgfIBkAAIAAgmIhjAAQAAghgHgTQgIgXgUAAQgSAAgOAYIAAAA").cp();
	this.shape_13.setTransform(17.6,29.1);

	// Layer 2
	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("rgba(102,255,0,0.008)").s("rgba(23,28,33,0.008)").ss(0.1,1,1).p("ADrDrInVAAIAAnVIHVAAIAAHV").cp();
	this.shape_14.setTransform(21.5,27.2);

	this.addChild(this.shape_14,this.shape_13);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-2,3.7,47,47);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{},true);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Layer 1
	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#CC3366").s().p("AglgSQAAgHAMgGQAMgGAKAAQAGAAAOAJQAEACAFAEIAMgdIgMgMQgKgJgQAAQgQAAgSATQgNAPgLAVQgJARABAGQAAAKALAHIAZAOIgKANIgHATIAGAEQAVgTAXgMQAVgKAhgIIALgiQggAJgeAMQgSgHgLgFQgOgHAAgKIAAAA").cp();
	this.shape_15.setTransform(11.2,23.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#0066FF").s().p("AARgcQAEACAFAEIAMgdIgMgMQgKgJgQAAQgQAAgSATQgNAPgLAVQgJARABAGQAAAKALAHIAZAOIgKANIgHATIAGAEQAVgTAXgMQAVgKAhgIIALgiQggAJgeAMQgSgHgLgFQgOgHAAgKQAAgHAMgGQAMgGAKAAQAGAAAOAJIAAAA").cp();
	this.shape_16.setTransform(-94.2,-58.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15}]}).to({state:[{t:this.shape_16}]},1).wait(1));

	// Layer 2
	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("ADcC+Im3AAIAAl7IG3AAIAAF7").cp();
	this.shape_17.setTransform(11.4,21.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AC+ieIAAE9Il7AAIAAk9IF7AA").cp();
	this.shape_18.setTransform(-103.5,-59.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17}]}).to({state:[{t:this.shape_18}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-10.5,2.7,44,38);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{},true);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Layer 1
	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#CC3366").s().p("ABCgOIAAgPQAAgngGgRQgFgLgPgUIgRAkQAQARAEAKQAHANgBAaIjKAAIAAAlIEzAAIAAglIhYAAAAMBPIAjASIARgfIgkgSIgQAfAgkBjIAkASIAOgfIgigTIgQAg").cp();
	this.shape_19.setTransform(15.7,25.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#0066FF").s().p("AAxgOIjKAAIAAAlIEzAAIAAglIhYAAIAAgPQAAgngGgRQgFgLgPgUIgRAkQAQARAEAKQAHANgBAaIAAAAAAvBhIARgfIgkgSIgQAfIAjASAAAB1IAOgfIgigTIgQAgIAkAS").cp();
	this.shape_20.setTransform(-25.9,-53.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19}]}).to({state:[{t:this.shape_20}]},1).wait(1));

	// Layer 2
	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("rgba(255,255,255,0.008)").s().p("AEdDvIo5AAIAAndII5AAIAAHd").cp();
	this.shape_21.setTransform(18.3,24.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("ADnA0IAACvInNAAIAAivIBOAAIAAkWIE2AAIAAEWIBJAA").cp();
	this.shape_22.setTransform(-26.2,-56.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21}]}).to({state:[{t:this.shape_22}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-10.2,0.6,57,48);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{},true);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Layer 1
	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#CC3366").s().p("AArhDQAFgDAGgBQAKAAAFAIQAJAIAEAWQgXAAgLgFQgJgGgBgLQAAgIAFgEIAAAAAAbhUQgLAUAAAYQAAAaASALQAQAIAfABIgcAjQgUAVgUALQgXAPgdAAQgLAAgOgEIgbgGIgFAIIA+ATQAQAEAPAAQAoAAAfgqQAdgmgBgkIAAgaQAAghgHgTQgIgXgUAAQgUAAgOAYIAAAA").cp();
	this.shape_23.setTransform(12.7,29.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#0066FF").s().p("AArhDQAFgDAGgBQAKAAAFAIQAJAIAEAWQgXAAgLgFQgJgGgBgLQAAgIAFgEIAAAAAA9hsQgUAAgOAYQgLAUAAAYQAAAaASALQAQAIAfABIgcAjQgUAVgUALQgXAPgdAAQgLAAgOgEIgbgGIgFAIIA+ATQAQAEAPAAQAoAAAfgqQAdgmgBgkIAAgaQAAghgHgTQgIgXgUAAIAAAA").cp();
	this.shape_24.setTransform(38.6,-56.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_23}]}).to({state:[{t:this.shape_24}]},1).wait(1));

	// Layer 3
	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("rgba(171,171,171,0.008)").s().p("AEXDJIotAAIAAmRIItAAIAAGR").cp();
	this.shape_25.setTransform(17,28.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f().s("rgba(255,255,255,0.008)").ss(0.1,1,1).p("AAAACIAAgD");
	this.shape_26.setTransform(21.9,-44);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AiVCLIg8AAIAAkVIGjAAIAAEVIlnAA").cp();
	this.shape_27.setTransform(36.9,-58.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_25}]}).to({state:[{t:this.shape_27},{t:this.shape_26}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-10.9,8,55.9,40.4);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;